;copyright 2018 the mitre corporation. all rights reserved. approved for public release. distribution unlimited 17-2122.
; for more information on caldera, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; this has 5 hosts, 2 user, 2 admin per host, 2 active account per host
(define (problem p5_hosts_trial_2)
(:domain caldera)
(:objects
    id_adomain - observeddomain
    id_caschtask id_cdschtask id_ceschtask id_ccschtask id_cbschtask - observedschtask
    id_gdomainuser id_cdomainuser - observeddomainuser
    num__19 num__12 num__34 num__13 num__27 num__41 num__33 num__20 num__26 num__40 - num
    id_cffile id_cjfile id_chfile id_cgfile id_cifile - observedfile
    id_bvrat id_bwrat id_byrat id_bxrat id_bzrat id_btrat - observedrat
    id_ddomaincredential id_hdomaincredential - observeddomaincredential
    id_ztimedelta id_ltimedelta id_bntimedelta id_stimedelta id_bgtimedelta - observedtimedelta
    str__q str__bj str__e str__o str__j str__p str__f str__b str__bd str__be str__x str__w str__bs str__alpha str__bc str__james str__i str__mary str__bu str__bq str__bk str__bl str__br str__v - string
    id_yhost id_khost id_rhost id_bmhost id_bfhost - observedhost
    id_ckshare id_cmshare id_cnshare id_clshare id_coshare - observedshare
)
(:init
    (knows id_btrat)
    (knows id_khost)
    (knows_property id_btrat pexecutable)
    (knows_property id_btrat phost)
    (knows_property id_khost pfqdn)
    (mem_cached_domain_creds id_bfhost id_ddomaincredential)
    (mem_cached_domain_creds id_bfhost id_hdomaincredential)
    (mem_cached_domain_creds id_bmhost id_ddomaincredential)
    (mem_cached_domain_creds id_bmhost id_hdomaincredential)
    (mem_cached_domain_creds id_khost id_ddomaincredential)
    (mem_cached_domain_creds id_khost id_hdomaincredential)
    (mem_cached_domain_creds id_rhost id_ddomaincredential)
    (mem_cached_domain_creds id_rhost id_hdomaincredential)
    (mem_cached_domain_creds id_yhost id_ddomaincredential)
    (mem_cached_domain_creds id_yhost id_hdomaincredential)
    (mem_domain_user_admins id_bfhost id_cdomainuser)
    (mem_domain_user_admins id_bfhost id_gdomainuser)
    (mem_domain_user_admins id_bmhost id_cdomainuser)
    (mem_domain_user_admins id_bmhost id_gdomainuser)
    (mem_domain_user_admins id_khost id_cdomainuser)
    (mem_domain_user_admins id_khost id_gdomainuser)
    (mem_domain_user_admins id_rhost id_cdomainuser)
    (mem_domain_user_admins id_rhost id_gdomainuser)
    (mem_domain_user_admins id_yhost id_cdomainuser)
    (mem_domain_user_admins id_yhost id_gdomainuser)
    (mem_hosts id_adomain id_bfhost)
    (mem_hosts id_adomain id_bmhost)
    (mem_hosts id_adomain id_khost)
    (mem_hosts id_adomain id_rhost)
    (mem_hosts id_adomain id_yhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_dc id_bfhost yes)
    (prop_dc id_bmhost no)
    (prop_dc id_khost no)
    (prop_dc id_rhost yes)
    (prop_dc id_yhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bfhost str__bk)
    (prop_dns_domain_name id_bmhost str__br)
    (prop_dns_domain_name id_khost str__p)
    (prop_dns_domain_name id_rhost str__w)
    (prop_dns_domain_name id_yhost str__bd)
    (prop_domain id_bfhost id_adomain)
    (prop_domain id_bmhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_khost id_adomain)
    (prop_domain id_rhost id_adomain)
    (prop_domain id_yhost id_adomain)
    (prop_elevated id_btrat yes)
    (prop_executable id_btrat str__bu)
    (prop_fqdn id_bfhost str__bj)
    (prop_fqdn id_bmhost str__bq)
    (prop_fqdn id_khost str__o)
    (prop_fqdn id_rhost str__v)
    (prop_fqdn id_yhost str__bc)
    (prop_host id_bgtimedelta id_bfhost)
    (prop_host id_bntimedelta id_bmhost)
    (prop_host id_btrat id_khost)
    (prop_host id_ltimedelta id_khost)
    (prop_host id_stimedelta id_rhost)
    (prop_host id_ztimedelta id_yhost)
    (prop_hostname id_bfhost str__bl)
    (prop_hostname id_bmhost str__bs)
    (prop_hostname id_khost str__q)
    (prop_hostname id_rhost str__x)
    (prop_hostname id_yhost str__be)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_microseconds id_bgtimedelta num__33)
    (prop_microseconds id_bntimedelta num__40)
    (prop_microseconds id_ltimedelta num__12)
    (prop_microseconds id_stimedelta num__19)
    (prop_microseconds id_ztimedelta num__26)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_seconds id_bgtimedelta num__34)
    (prop_seconds id_bntimedelta num__41)
    (prop_seconds id_ltimedelta num__13)
    (prop_seconds id_stimedelta num__20)
    (prop_seconds id_ztimedelta num__27)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_timedelta id_bfhost id_bgtimedelta)
    (prop_timedelta id_bmhost id_bntimedelta)
    (prop_timedelta id_khost id_ltimedelta)
    (prop_timedelta id_rhost id_stimedelta)
    (prop_timedelta id_yhost id_ztimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_windows_domain id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_bxrat id_bmhost)
    (prop_host id_bvrat id_yhost)
    (prop_host id_bzrat id_bfhost)
    (prop_host id_byrat id_rhost)
)
)
)