;copyright 2018 the mitre corporation. all rights reserved. approved for public release. distribution unlimited 17-2122.
; for more information on caldera, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; this has 5 hosts, 2 user, 1 admin per host, 1 active account per host
(define (problem p5_hosts_trial_6)
(:domain caldera)
(:objects
    str__b str__bk str__e str__james str__x str__j str__o str__p str__bl str__br str__bq str__f str__q str__i str__bd str__bj str__v str__w str__bc str__bs str__mary str__bu str__alpha str__be - string
    num__27 num__19 num__13 num__40 num__20 num__41 num__34 num__12 num__33 num__26 - num
    id_gdomainuser id_cdomainuser - observeddomainuser
    id_cjrat id_cfrat id_btrat id_chrat id_cirat id_cgrat - observedrat
    id_bfhost id_yhost id_rhost id_khost id_bmhost - observedhost
    id_bzshare id_byshare id_bxshare id_bvshare id_bwshare - observedshare
    id_adomain - observeddomain
    id_ddomaincredential id_hdomaincredential - observeddomaincredential
    id_bntimedelta id_bgtimedelta id_stimedelta id_ztimedelta id_ltimedelta - observedtimedelta
    id_cdfile id_cafile id_cefile id_cbfile id_ccfile - observedfile
    id_clschtask id_cmschtask id_ckschtask id_coschtask id_cnschtask - observedschtask
)
(:init
    (knows id_btrat)
    (knows id_rhost)
    (knows_property id_btrat pexecutable)
    (knows_property id_btrat phost)
    (knows_property id_rhost pfqdn)
    (mem_cached_domain_creds id_bfhost id_ddomaincredential)
    (mem_cached_domain_creds id_bmhost id_hdomaincredential)
    (mem_cached_domain_creds id_khost id_ddomaincredential)
    (mem_cached_domain_creds id_rhost id_ddomaincredential)
    (mem_cached_domain_creds id_yhost id_hdomaincredential)
    (mem_domain_user_admins id_bfhost id_cdomainuser)
    (mem_domain_user_admins id_bmhost id_cdomainuser)
    (mem_domain_user_admins id_khost id_gdomainuser)
    (mem_domain_user_admins id_rhost id_gdomainuser)
    (mem_domain_user_admins id_yhost id_gdomainuser)
    (mem_hosts id_adomain id_bfhost)
    (mem_hosts id_adomain id_bmhost)
    (mem_hosts id_adomain id_khost)
    (mem_hosts id_adomain id_rhost)
    (mem_hosts id_adomain id_yhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_dc id_bfhost no)
    (prop_dc id_bmhost no)
    (prop_dc id_khost no)
    (prop_dc id_rhost no)
    (prop_dc id_yhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bfhost str__bk)
    (prop_dns_domain_name id_bmhost str__br)
    (prop_dns_domain_name id_khost str__p)
    (prop_dns_domain_name id_rhost str__w)
    (prop_dns_domain_name id_yhost str__bd)
    (prop_domain id_bfhost id_adomain)
    (prop_domain id_bmhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_khost id_adomain)
    (prop_domain id_rhost id_adomain)
    (prop_domain id_yhost id_adomain)
    (prop_elevated id_btrat yes)
    (prop_executable id_btrat str__bu)
    (prop_fqdn id_bfhost str__bl)
    (prop_fqdn id_bmhost str__bs)
    (prop_fqdn id_khost str__q)
    (prop_fqdn id_rhost str__x)
    (prop_fqdn id_yhost str__be)
    (prop_host id_bgtimedelta id_bfhost)
    (prop_host id_bntimedelta id_bmhost)
    (prop_host id_btrat id_rhost)
    (prop_host id_ltimedelta id_khost)
    (prop_host id_stimedelta id_rhost)
    (prop_host id_ztimedelta id_yhost)
    (prop_hostname id_bfhost str__bj)
    (prop_hostname id_bmhost str__bq)
    (prop_hostname id_khost str__o)
    (prop_hostname id_rhost str__v)
    (prop_hostname id_yhost str__bc)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_microseconds id_bgtimedelta num__33)
    (prop_microseconds id_bntimedelta num__40)
    (prop_microseconds id_ltimedelta num__12)
    (prop_microseconds id_stimedelta num__19)
    (prop_microseconds id_ztimedelta num__26)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_seconds id_bgtimedelta num__34)
    (prop_seconds id_bntimedelta num__41)
    (prop_seconds id_ltimedelta num__13)
    (prop_seconds id_stimedelta num__20)
    (prop_seconds id_ztimedelta num__27)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_timedelta id_bfhost id_bgtimedelta)
    (prop_timedelta id_bmhost id_bntimedelta)
    (prop_timedelta id_khost id_ltimedelta)
    (prop_timedelta id_rhost id_stimedelta)
    (prop_timedelta id_yhost id_ztimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_windows_domain id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_cgrat id_bmhost)
    (prop_host id_cjrat id_khost)
    (prop_host id_chrat id_bfhost)
    (prop_host id_cfrat id_yhost)
)
)
)