;copyright 2018 the mitre corporation. all rights reserved. approved for public release. distribution unlimited 17-2122.
; for more information on caldera, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; this has 9 hosts, 4 user, 2 admin per host, 2 active account per host
(define (problem p9_hosts_trial_3)
(:domain caldera)
(:objects
    id_dzrat id_earat id_ebrat id_dxrat id_ddrat id_eerat id_efrat id_ecrat id_edrat id_dyrat - observedrat
    id_dkschtask id_dischtask id_dmschtask id_dnschtask id_dhschtask id_dgschtask id_djschtask id_dlschtask id_dfschtask - observedschtask
    num__76 num__34 num__55 num__69 num__42 num__27 num__70 num__77 num__62 num__56 num__21 num__41 num__63 num__48 num__28 num__20 num__35 num__49 - num
    id_adomain - observeddomain
    str__db str__j str__n str__bs str__x str__e str__co str__by str__bz str__john str__bt str__dc str__be str__bd str__q str__mary str__ca str__da str__bm str__cm str__bf str__b str__alpha str__cn str__cu str__patricia str__cg str__r str__ch str__ct str__w str__bl str__bk str__f str__cf str__cv str__james str__i str__m str__y str__de str__br - string
    id_pdomaincredential id_hdomaincredential id_ddomaincredential id_ldomaincredential - observeddomaincredential
    id_drfile id_dpfile id_dvfile id_dqfile id_dtfile id_dofile id_dufile id_dsfile id_dwfile - observedfile
    id_shost id_cbhost id_cihost id_bnhost id_bghost id_cphost id_buhost id_cwhost id_zhost - observedhost
    id_emshare id_ejshare id_elshare id_eishare id_egshare id_ehshare id_eoshare id_ekshare id_enshare - observedshare
    id_gdomainuser id_kdomainuser id_odomainuser id_cdomainuser - observeddomainuser
    id_cqtimedelta id_cxtimedelta id_cctimedelta id_bhtimedelta id_bvtimedelta id_ttimedelta id_cjtimedelta id_botimedelta id_batimedelta - observedtimedelta
)
(:init
    (knows id_ddrat)
    (knows id_zhost)
    (knows_property id_ddrat pexecutable)
    (knows_property id_ddrat phost)
    (knows_property id_zhost pfqdn)
    (mem_cached_domain_creds id_bghost id_ddomaincredential)
    (mem_cached_domain_creds id_bghost id_hdomaincredential)
    (mem_cached_domain_creds id_bnhost id_hdomaincredential)
    (mem_cached_domain_creds id_bnhost id_pdomaincredential)
    (mem_cached_domain_creds id_buhost id_ddomaincredential)
    (mem_cached_domain_creds id_buhost id_ldomaincredential)
    (mem_cached_domain_creds id_cbhost id_ddomaincredential)
    (mem_cached_domain_creds id_cbhost id_hdomaincredential)
    (mem_cached_domain_creds id_cihost id_ddomaincredential)
    (mem_cached_domain_creds id_cihost id_ldomaincredential)
    (mem_cached_domain_creds id_cphost id_hdomaincredential)
    (mem_cached_domain_creds id_cphost id_pdomaincredential)
    (mem_cached_domain_creds id_cwhost id_ddomaincredential)
    (mem_cached_domain_creds id_cwhost id_pdomaincredential)
    (mem_cached_domain_creds id_shost id_ldomaincredential)
    (mem_cached_domain_creds id_shost id_pdomaincredential)
    (mem_cached_domain_creds id_zhost id_hdomaincredential)
    (mem_cached_domain_creds id_zhost id_ldomaincredential)
    (mem_domain_user_admins id_bghost id_gdomainuser)
    (mem_domain_user_admins id_bghost id_odomainuser)
    (mem_domain_user_admins id_bnhost id_gdomainuser)
    (mem_domain_user_admins id_bnhost id_kdomainuser)
    (mem_domain_user_admins id_buhost id_gdomainuser)
    (mem_domain_user_admins id_buhost id_odomainuser)
    (mem_domain_user_admins id_cbhost id_kdomainuser)
    (mem_domain_user_admins id_cbhost id_odomainuser)
    (mem_domain_user_admins id_cihost id_cdomainuser)
    (mem_domain_user_admins id_cihost id_odomainuser)
    (mem_domain_user_admins id_cphost id_cdomainuser)
    (mem_domain_user_admins id_cphost id_gdomainuser)
    (mem_domain_user_admins id_cwhost id_cdomainuser)
    (mem_domain_user_admins id_cwhost id_odomainuser)
    (mem_domain_user_admins id_shost id_cdomainuser)
    (mem_domain_user_admins id_shost id_gdomainuser)
    (mem_domain_user_admins id_zhost id_cdomainuser)
    (mem_domain_user_admins id_zhost id_kdomainuser)
    (mem_hosts id_adomain id_bghost)
    (mem_hosts id_adomain id_bnhost)
    (mem_hosts id_adomain id_buhost)
    (mem_hosts id_adomain id_cbhost)
    (mem_hosts id_adomain id_cihost)
    (mem_hosts id_adomain id_cphost)
    (mem_hosts id_adomain id_cwhost)
    (mem_hosts id_adomain id_shost)
    (mem_hosts id_adomain id_zhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_dc id_bghost yes)
    (prop_dc id_bnhost no)
    (prop_dc id_buhost no)
    (prop_dc id_cbhost no)
    (prop_dc id_cihost no)
    (prop_dc id_cphost yes)
    (prop_dc id_cwhost no)
    (prop_dc id_shost no)
    (prop_dc id_zhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bghost str__bk)
    (prop_dns_domain_name id_bnhost str__br)
    (prop_dns_domain_name id_buhost str__by)
    (prop_dns_domain_name id_cbhost str__cf)
    (prop_dns_domain_name id_cihost str__cm)
    (prop_dns_domain_name id_cphost str__ct)
    (prop_dns_domain_name id_cwhost str__da)
    (prop_dns_domain_name id_shost str__w)
    (prop_dns_domain_name id_zhost str__bd)
    (prop_domain id_bghost id_adomain)
    (prop_domain id_bnhost id_adomain)
    (prop_domain id_buhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_cbhost id_adomain)
    (prop_domain id_cihost id_adomain)
    (prop_domain id_cphost id_adomain)
    (prop_domain id_cwhost id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_shost id_adomain)
    (prop_domain id_zhost id_adomain)
    (prop_elevated id_ddrat yes)
    (prop_executable id_ddrat str__de)
    (prop_fqdn id_bghost str__bm)
    (prop_fqdn id_bnhost str__bt)
    (prop_fqdn id_buhost str__ca)
    (prop_fqdn id_cbhost str__ch)
    (prop_fqdn id_cihost str__co)
    (prop_fqdn id_cphost str__cv)
    (prop_fqdn id_cwhost str__dc)
    (prop_fqdn id_shost str__y)
    (prop_fqdn id_zhost str__bf)
    (prop_host id_batimedelta id_zhost)
    (prop_host id_bhtimedelta id_bghost)
    (prop_host id_botimedelta id_bnhost)
    (prop_host id_bvtimedelta id_buhost)
    (prop_host id_cctimedelta id_cbhost)
    (prop_host id_cjtimedelta id_cihost)
    (prop_host id_cqtimedelta id_cphost)
    (prop_host id_cxtimedelta id_cwhost)
    (prop_host id_ddrat id_zhost)
    (prop_host id_ttimedelta id_shost)
    (prop_hostname id_bghost str__bl)
    (prop_hostname id_bnhost str__bs)
    (prop_hostname id_buhost str__bz)
    (prop_hostname id_cbhost str__cg)
    (prop_hostname id_cihost str__cn)
    (prop_hostname id_cphost str__cu)
    (prop_hostname id_cwhost str__db)
    (prop_hostname id_shost str__x)
    (prop_hostname id_zhost str__be)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_microseconds id_batimedelta num__28)
    (prop_microseconds id_bhtimedelta num__35)
    (prop_microseconds id_botimedelta num__42)
    (prop_microseconds id_bvtimedelta num__49)
    (prop_microseconds id_cctimedelta num__56)
    (prop_microseconds id_cjtimedelta num__63)
    (prop_microseconds id_cqtimedelta num__70)
    (prop_microseconds id_cxtimedelta num__77)
    (prop_microseconds id_ttimedelta num__21)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_seconds id_batimedelta num__27)
    (prop_seconds id_bhtimedelta num__34)
    (prop_seconds id_botimedelta num__41)
    (prop_seconds id_bvtimedelta num__48)
    (prop_seconds id_cctimedelta num__55)
    (prop_seconds id_cjtimedelta num__62)
    (prop_seconds id_cqtimedelta num__69)
    (prop_seconds id_cxtimedelta num__76)
    (prop_seconds id_ttimedelta num__20)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_timedelta id_bghost id_bhtimedelta)
    (prop_timedelta id_bnhost id_botimedelta)
    (prop_timedelta id_buhost id_bvtimedelta)
    (prop_timedelta id_cbhost id_cctimedelta)
    (prop_timedelta id_cihost id_cjtimedelta)
    (prop_timedelta id_cphost id_cqtimedelta)
    (prop_timedelta id_cwhost id_cxtimedelta)
    (prop_timedelta id_shost id_ttimedelta)
    (prop_timedelta id_zhost id_batimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_windows_domain id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_dyrat id_cwhost)
    (prop_host id_dzrat id_shost)
    (prop_host id_earat id_cbhost)
    (prop_host id_ebrat id_cihost)
    (prop_host id_dxrat id_bnhost)
    (prop_host id_eerat id_bghost)
    (prop_host id_efrat id_cphost)
    (prop_host id_ecrat id_buhost)
)
)
)