;copyright 2018 the mitre corporation. all rights reserved. approved for public release. distribution unlimited 17-2122.
; for more information on caldera, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; this has 11 hosts, 5 user, 2 admin per host, 2 active account per host
(define (problem p11_hosts_trial_5)
(:domain caldera)
(:objects
    id_edshare id_dyshare id_efshare id_dzshare id_dxshare id_ebshare id_eashare id_ehshare id_egshare id_ecshare id_eeshare - observedshare
    id_ldomaincredential id_tdomaincredential id_hdomaincredential id_ddomaincredential id_pdomaincredential - observeddomaincredential
    id_kdomainuser id_gdomainuser id_cdomainuser id_odomainuser id_sdomainuser - observeddomainuser
    id_bztimedelta id_dptimedelta id_cgtimedelta id_betimedelta id_xtimedelta id_cutimedelta id_dbtimedelta id_bstimedelta id_ditimedelta id_cntimedelta id_bltimedelta - observedtimedelta
    id_byhost id_brhost id_dhhost id_dahost id_bdhost id_cmhost id_cthost id_bkhost id_dohost id_whost id_cfhost - observedhost
    num__80 num__87 num__32 num__39 num__81 num__24 num__59 num__73 num__45 num__60 num__88 num__53 num__52 num__94 num__46 num__25 num__66 num__38 num__31 num__74 num__67 num__95 - num
    id_erfile id_ejfile id_ekfile id_elfile id_emfile id_eqfile id_eifile id_eofile id_epfile id_esfile id_enfile - observedfile
    id_adomain - observeddomain
    id_etrat id_fbrat id_exrat id_dvrat id_eurat id_ewrat id_farat id_evrat id_ezrat id_fdrat id_eyrat id_fcrat - observedrat
    str__e str__ba str__john str__cq str__ce str__de str__b str__bw str__du str__bb str__v str__bq str__ds str__q str__j str__bh str__mary str__f str__bp str__cc str__cl str__cs str__df str__dw str__ck str__alpha str__dg str__cd str__cx str__r str__robert str__i str__u str__james str__bv str__dt str__n str__dl str__dm str__bc str__cj str__cy str__cr str__cz str__patricia str__bj str__bx str__bo str__bi str__dn str__m - string
    id_fgschtask id_fhschtask id_foschtask id_feschtask id_fmschtask id_fjschtask id_ffschtask id_fkschtask id_fnschtask id_flschtask id_fischtask - observedschtask
)
(:init
    (knows id_dohost)
    (knows id_dvrat)
    (knows_property id_dohost pfqdn)
    (knows_property id_dvrat pexecutable)
    (knows_property id_dvrat phost)
    (mem_cached_domain_creds id_bdhost id_ldomaincredential)
    (mem_cached_domain_creds id_bdhost id_pdomaincredential)
    (mem_cached_domain_creds id_bkhost id_hdomaincredential)
    (mem_cached_domain_creds id_bkhost id_ldomaincredential)
    (mem_cached_domain_creds id_brhost id_ddomaincredential)
    (mem_cached_domain_creds id_brhost id_ldomaincredential)
    (mem_cached_domain_creds id_byhost id_ddomaincredential)
    (mem_cached_domain_creds id_byhost id_ldomaincredential)
    (mem_cached_domain_creds id_cfhost id_ldomaincredential)
    (mem_cached_domain_creds id_cfhost id_tdomaincredential)
    (mem_cached_domain_creds id_cmhost id_hdomaincredential)
    (mem_cached_domain_creds id_cmhost id_pdomaincredential)
    (mem_cached_domain_creds id_cthost id_ldomaincredential)
    (mem_cached_domain_creds id_cthost id_pdomaincredential)
    (mem_cached_domain_creds id_dahost id_ddomaincredential)
    (mem_cached_domain_creds id_dahost id_hdomaincredential)
    (mem_cached_domain_creds id_dhhost id_pdomaincredential)
    (mem_cached_domain_creds id_dhhost id_tdomaincredential)
    (mem_cached_domain_creds id_dohost id_hdomaincredential)
    (mem_cached_domain_creds id_dohost id_ldomaincredential)
    (mem_cached_domain_creds id_whost id_ddomaincredential)
    (mem_cached_domain_creds id_whost id_pdomaincredential)
    (mem_domain_user_admins id_bdhost id_cdomainuser)
    (mem_domain_user_admins id_bdhost id_odomainuser)
    (mem_domain_user_admins id_bkhost id_gdomainuser)
    (mem_domain_user_admins id_bkhost id_kdomainuser)
    (mem_domain_user_admins id_brhost id_gdomainuser)
    (mem_domain_user_admins id_brhost id_kdomainuser)
    (mem_domain_user_admins id_byhost id_cdomainuser)
    (mem_domain_user_admins id_byhost id_kdomainuser)
    (mem_domain_user_admins id_cfhost id_cdomainuser)
    (mem_domain_user_admins id_cfhost id_sdomainuser)
    (mem_domain_user_admins id_cmhost id_cdomainuser)
    (mem_domain_user_admins id_cmhost id_kdomainuser)
    (mem_domain_user_admins id_cthost id_gdomainuser)
    (mem_domain_user_admins id_cthost id_sdomainuser)
    (mem_domain_user_admins id_dahost id_cdomainuser)
    (mem_domain_user_admins id_dahost id_kdomainuser)
    (mem_domain_user_admins id_dhhost id_cdomainuser)
    (mem_domain_user_admins id_dhhost id_gdomainuser)
    (mem_domain_user_admins id_dohost id_cdomainuser)
    (mem_domain_user_admins id_dohost id_kdomainuser)
    (mem_domain_user_admins id_whost id_cdomainuser)
    (mem_domain_user_admins id_whost id_odomainuser)
    (mem_hosts id_adomain id_bdhost)
    (mem_hosts id_adomain id_bkhost)
    (mem_hosts id_adomain id_brhost)
    (mem_hosts id_adomain id_byhost)
    (mem_hosts id_adomain id_cfhost)
    (mem_hosts id_adomain id_cmhost)
    (mem_hosts id_adomain id_cthost)
    (mem_hosts id_adomain id_dahost)
    (mem_hosts id_adomain id_dhhost)
    (mem_hosts id_adomain id_dohost)
    (mem_hosts id_adomain id_whost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_dc id_bdhost yes)
    (prop_dc id_bkhost no)
    (prop_dc id_brhost no)
    (prop_dc id_byhost no)
    (prop_dc id_cfhost no)
    (prop_dc id_cmhost no)
    (prop_dc id_cthost yes)
    (prop_dc id_dahost no)
    (prop_dc id_dhhost no)
    (prop_dc id_dohost no)
    (prop_dc id_whost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bdhost str__bh)
    (prop_dns_domain_name id_bkhost str__bo)
    (prop_dns_domain_name id_brhost str__bv)
    (prop_dns_domain_name id_byhost str__cc)
    (prop_dns_domain_name id_cfhost str__cj)
    (prop_dns_domain_name id_cmhost str__cq)
    (prop_dns_domain_name id_cthost str__cx)
    (prop_dns_domain_name id_dahost str__de)
    (prop_dns_domain_name id_dhhost str__dl)
    (prop_dns_domain_name id_dohost str__ds)
    (prop_dns_domain_name id_whost str__ba)
    (prop_domain id_bdhost id_adomain)
    (prop_domain id_bkhost id_adomain)
    (prop_domain id_brhost id_adomain)
    (prop_domain id_byhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_cfhost id_adomain)
    (prop_domain id_cmhost id_adomain)
    (prop_domain id_cthost id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_dahost id_adomain)
    (prop_domain id_dhhost id_adomain)
    (prop_domain id_dohost id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_whost id_adomain)
    (prop_elevated id_dvrat yes)
    (prop_executable id_dvrat str__dw)
    (prop_fqdn id_bdhost str__bi)
    (prop_fqdn id_bkhost str__bp)
    (prop_fqdn id_brhost str__bw)
    (prop_fqdn id_byhost str__cd)
    (prop_fqdn id_cfhost str__ck)
    (prop_fqdn id_cmhost str__cr)
    (prop_fqdn id_cthost str__cy)
    (prop_fqdn id_dahost str__df)
    (prop_fqdn id_dhhost str__dm)
    (prop_fqdn id_dohost str__dt)
    (prop_fqdn id_whost str__bb)
    (prop_host id_betimedelta id_bdhost)
    (prop_host id_bltimedelta id_bkhost)
    (prop_host id_bstimedelta id_brhost)
    (prop_host id_bztimedelta id_byhost)
    (prop_host id_cgtimedelta id_cfhost)
    (prop_host id_cntimedelta id_cmhost)
    (prop_host id_cutimedelta id_cthost)
    (prop_host id_dbtimedelta id_dahost)
    (prop_host id_ditimedelta id_dhhost)
    (prop_host id_dptimedelta id_dohost)
    (prop_host id_dvrat id_dohost)
    (prop_host id_xtimedelta id_whost)
    (prop_hostname id_bdhost str__bj)
    (prop_hostname id_bkhost str__bq)
    (prop_hostname id_brhost str__bx)
    (prop_hostname id_byhost str__ce)
    (prop_hostname id_cfhost str__cl)
    (prop_hostname id_cmhost str__cs)
    (prop_hostname id_cthost str__cz)
    (prop_hostname id_dahost str__dg)
    (prop_hostname id_dhhost str__dn)
    (prop_hostname id_dohost str__du)
    (prop_hostname id_whost str__bc)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_microseconds id_betimedelta num__31)
    (prop_microseconds id_bltimedelta num__38)
    (prop_microseconds id_bstimedelta num__45)
    (prop_microseconds id_bztimedelta num__52)
    (prop_microseconds id_cgtimedelta num__59)
    (prop_microseconds id_cntimedelta num__66)
    (prop_microseconds id_cutimedelta num__73)
    (prop_microseconds id_dbtimedelta num__80)
    (prop_microseconds id_ditimedelta num__87)
    (prop_microseconds id_dptimedelta num__94)
    (prop_microseconds id_xtimedelta num__24)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_seconds id_betimedelta num__32)
    (prop_seconds id_bltimedelta num__39)
    (prop_seconds id_bstimedelta num__46)
    (prop_seconds id_bztimedelta num__53)
    (prop_seconds id_cgtimedelta num__60)
    (prop_seconds id_cntimedelta num__67)
    (prop_seconds id_cutimedelta num__74)
    (prop_seconds id_dbtimedelta num__81)
    (prop_seconds id_ditimedelta num__88)
    (prop_seconds id_dptimedelta num__95)
    (prop_seconds id_xtimedelta num__25)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_timedelta id_bdhost id_betimedelta)
    (prop_timedelta id_bkhost id_bltimedelta)
    (prop_timedelta id_brhost id_bstimedelta)
    (prop_timedelta id_byhost id_bztimedelta)
    (prop_timedelta id_cfhost id_cgtimedelta)
    (prop_timedelta id_cmhost id_cntimedelta)
    (prop_timedelta id_cthost id_cutimedelta)
    (prop_timedelta id_dahost id_dbtimedelta)
    (prop_timedelta id_dhhost id_ditimedelta)
    (prop_timedelta id_dohost id_dptimedelta)
    (prop_timedelta id_whost id_xtimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_windows_domain id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_fcrat id_cfhost)
    (prop_host id_etrat id_byhost)
    (prop_host id_fbrat id_brhost)
    (prop_host id_exrat id_dhhost)
    (prop_host id_eurat id_dahost)
    (prop_host id_ewrat id_bdhost)
    (prop_host id_farat id_cmhost)
    (prop_host id_evrat id_cthost)
    (prop_host id_ezrat id_bkhost)
    (prop_host id_fdrat id_whost)
)
)
)