common: # added to all solvers
  - benchmark_name
  - algorithm
#  - domain
#  - problem
cpt:
  - num_fluents
  - num_actions
  - ort_variables
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - is_plan_valid
  - is_plan_found
  - is_plan_optimal
  - makespan
  - booleans
  - conflicts
  - branches
  - propagations
  - integer_propagations
  - validate_exit_code
  - run_dir
popf2:
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - is_plan_valid
  - is_plan_found
  - is_plan_optimal
  - makespan
  - validate_exit_code
  - run_dir
optic:
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - is_plan_valid
  - is_plan_found
  - is_plan_optimal
  - makespan
  - validate_exit_code
  - run_dir
plan.py:
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - is_plan_valid
  - is_plan_found
  - is_plan_optimal
  - makespan
  - validate_exit_code
  - run_dir
