common: # added to all solvers
  - benchmark_name
  - algorithm
#  - domain
#  - problem
cpt:
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - run_dir
  - validate_exit_code
  - lab_exit_code
  - is_plan_valid
  - makespan
  - booleans
  - conflicts
  - branches
  - propagations
  - integer_propagations
popf2:
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - run_dir
  - validate_exit_code
  - lab_exit_code
  - is_plan_valid
  - makespan
optic:
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - run_dir
  - validate_exit_code
  - lab_exit_code
  - is_plan_valid
  - makespan
plan.py:
  - solver_exit_code
  - runtime_solver
  - runtime_total
  - time_limit
  - memory
  - memory_limit
  - run_dir
  - validate_exit_code
  - lab_exit_code
  - is_plan_valid
  - makespan
