;copyright 2018 the mitre corporation. all rights reserved. approved for public release. distribution unlimited 17-2122.
; for more information on caldera, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; this has 3 hosts, 6 user, 2 admin per host, 3 active account per host
(define (problem p3_hosts_trial_13)
(:domain caldera)
(:objects
    id_bbtimedelta id_bptimedelta id_bitimedelta - observedtimedelta
    id_adomain - observeddomain
    id_ccfile id_cafile id_cbfile - observedfile
    id_bohost id_bhhost id_bahost - observedhost
    id_bvrat id_cdrat id_cerat id_cfrat - observedrat
    id_cgshare id_chshare id_cishare - observedshare
    id_pdomaincredential id_tdomaincredential id_xdomaincredential id_ddomaincredential id_hdomaincredential id_ldomaincredential - observeddomaincredential
    id_bzschtask id_byschtask id_bxschtask - observedschtask
    num__42 num__43 num__35 num__28 num__29 num__36 - num
    id_odomainuser id_gdomainuser id_sdomainuser id_wdomainuser id_kdomainuser id_cdomainuser - observeddomainuser
    str__bt str__mary str__bl str__bg str__y str__be str__i str__bs str__f str__v str__m str__n str__u str__q str__linda str__bm str__z str__patricia str__alpha str__john str__james str__e str__b str__robert str__bw str__j str__bf str__r str__bu str__bn - string
)
(:init
    (knows id_bahost)
    (knows id_bvrat)
    (knows_property id_bahost pfqdn)
    (knows_property id_bvrat pexecutable)
    (knows_property id_bvrat phost)
    (mem_cached_domain_creds id_bahost id_ddomaincredential)
    (mem_cached_domain_creds id_bahost id_ldomaincredential)
    (mem_cached_domain_creds id_bahost id_tdomaincredential)
    (mem_cached_domain_creds id_bhhost id_ddomaincredential)
    (mem_cached_domain_creds id_bhhost id_pdomaincredential)
    (mem_cached_domain_creds id_bhhost id_xdomaincredential)
    (mem_cached_domain_creds id_bohost id_ddomaincredential)
    (mem_cached_domain_creds id_bohost id_pdomaincredential)
    (mem_cached_domain_creds id_bohost id_xdomaincredential)
    (mem_domain_user_admins id_bahost id_gdomainuser)
    (mem_domain_user_admins id_bahost id_odomainuser)
    (mem_domain_user_admins id_bhhost id_gdomainuser)
    (mem_domain_user_admins id_bhhost id_sdomainuser)
    (mem_domain_user_admins id_bohost id_gdomainuser)
    (mem_domain_user_admins id_bohost id_kdomainuser)
    (mem_hosts id_adomain id_bahost)
    (mem_hosts id_adomain id_bhhost)
    (mem_hosts id_adomain id_bohost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_bahost no)
    (prop_dc id_bhhost no)
    (prop_dc id_bohost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bahost str__be)
    (prop_dns_domain_name id_bhhost str__bl)
    (prop_dns_domain_name id_bohost str__bs)
    (prop_domain id_bahost id_adomain)
    (prop_domain id_bhhost id_adomain)
    (prop_domain id_bohost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_bvrat yes)
    (prop_executable id_bvrat str__bw)
    (prop_fqdn id_bahost str__bf)
    (prop_fqdn id_bhhost str__bm)
    (prop_fqdn id_bohost str__bt)
    (prop_host id_bbtimedelta id_bahost)
    (prop_host id_bitimedelta id_bhhost)
    (prop_host id_bptimedelta id_bohost)
    (prop_host id_bvrat id_bahost)
    (prop_hostname id_bahost str__bg)
    (prop_hostname id_bhhost str__bn)
    (prop_hostname id_bohost str__bu)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_bbtimedelta num__29)
    (prop_microseconds id_bitimedelta num__36)
    (prop_microseconds id_bptimedelta num__43)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_bbtimedelta num__28)
    (prop_seconds id_bitimedelta num__35)
    (prop_seconds id_bptimedelta num__42)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_bahost id_bbtimedelta)
    (prop_timedelta id_bhhost id_bitimedelta)
    (prop_timedelta id_bohost id_bptimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_cfrat id_bhhost)
    (prop_host id_cdrat id_bohost)
)
)
)