;copyright 2018 the mitre corporation. all rights reserved. approved for public release. distribution unlimited 17-2122.
; for more information on caldera, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; this has 4 hosts, 5 user, 5 admin per host, 3 active account per host
(define (problem p4_hosts_trial_10)
(:domain caldera)
(:objects
    id_ccschtask id_caschtask id_cbschtask id_cdschtask - observedschtask
    id_cdomainuser id_kdomainuser id_odomainuser id_sdomainuser id_gdomainuser - observeddomainuser
    id_bstimedelta id_bltimedelta id_betimedelta id_xtimedelta - observedtimedelta
    id_cefile id_chfile id_cffile id_cgfile - observedfile
    id_cjshare id_cishare id_clshare id_ckshare - observedshare
    id_cprat id_byrat id_corat id_cnrat id_cmrat - observedrat
    id_ddomaincredential id_pdomaincredential id_tdomaincredential id_ldomaincredential id_hdomaincredential - observeddomaincredential
    num__46 num__31 num__45 num__39 num__32 num__24 num__25 num__38 - num
    str__bj str__bp str__bc str__patricia str__bq str__ba str__john str__r str__bz str__alpha str__q str__james str__n str__j str__e str__bv str__m str__bo str__bh str__bx str__f str__bb str__b str__mary str__bw str__u str__bi str__v str__i str__robert - string
    id_adomain - observeddomain
    id_bkhost id_brhost id_whost id_bdhost - observedhost
)
(:init
    (knows id_bdhost)
    (knows id_byrat)
    (knows_property id_bdhost pfqdn)
    (knows_property id_byrat pexecutable)
    (knows_property id_byrat phost)
    (mem_cached_domain_creds id_bdhost id_ldomaincredential)
    (mem_cached_domain_creds id_bdhost id_pdomaincredential)
    (mem_cached_domain_creds id_bdhost id_tdomaincredential)
    (mem_cached_domain_creds id_bkhost id_ddomaincredential)
    (mem_cached_domain_creds id_bkhost id_pdomaincredential)
    (mem_cached_domain_creds id_bkhost id_tdomaincredential)
    (mem_cached_domain_creds id_brhost id_ddomaincredential)
    (mem_cached_domain_creds id_brhost id_hdomaincredential)
    (mem_cached_domain_creds id_brhost id_ldomaincredential)
    (mem_cached_domain_creds id_whost id_hdomaincredential)
    (mem_cached_domain_creds id_whost id_pdomaincredential)
    (mem_cached_domain_creds id_whost id_tdomaincredential)
    (mem_domain_user_admins id_bdhost id_cdomainuser)
    (mem_domain_user_admins id_bdhost id_gdomainuser)
    (mem_domain_user_admins id_bdhost id_kdomainuser)
    (mem_domain_user_admins id_bdhost id_odomainuser)
    (mem_domain_user_admins id_bdhost id_sdomainuser)
    (mem_domain_user_admins id_bkhost id_cdomainuser)
    (mem_domain_user_admins id_bkhost id_gdomainuser)
    (mem_domain_user_admins id_bkhost id_kdomainuser)
    (mem_domain_user_admins id_bkhost id_odomainuser)
    (mem_domain_user_admins id_bkhost id_sdomainuser)
    (mem_domain_user_admins id_brhost id_cdomainuser)
    (mem_domain_user_admins id_brhost id_gdomainuser)
    (mem_domain_user_admins id_brhost id_kdomainuser)
    (mem_domain_user_admins id_brhost id_odomainuser)
    (mem_domain_user_admins id_brhost id_sdomainuser)
    (mem_domain_user_admins id_whost id_cdomainuser)
    (mem_domain_user_admins id_whost id_gdomainuser)
    (mem_domain_user_admins id_whost id_kdomainuser)
    (mem_domain_user_admins id_whost id_odomainuser)
    (mem_domain_user_admins id_whost id_sdomainuser)
    (mem_hosts id_adomain id_bdhost)
    (mem_hosts id_adomain id_bkhost)
    (mem_hosts id_adomain id_brhost)
    (mem_hosts id_adomain id_whost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_dc id_bdhost no)
    (prop_dc id_bkhost yes)
    (prop_dc id_brhost no)
    (prop_dc id_whost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bdhost str__bh)
    (prop_dns_domain_name id_bkhost str__bo)
    (prop_dns_domain_name id_brhost str__bv)
    (prop_dns_domain_name id_whost str__ba)
    (prop_domain id_bdhost id_adomain)
    (prop_domain id_bkhost id_adomain)
    (prop_domain id_brhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_whost id_adomain)
    (prop_elevated id_byrat yes)
    (prop_executable id_byrat str__bz)
    (prop_fqdn id_bdhost str__bj)
    (prop_fqdn id_bkhost str__bq)
    (prop_fqdn id_brhost str__bx)
    (prop_fqdn id_whost str__bc)
    (prop_host id_betimedelta id_bdhost)
    (prop_host id_bltimedelta id_bkhost)
    (prop_host id_bstimedelta id_brhost)
    (prop_host id_byrat id_bdhost)
    (prop_host id_xtimedelta id_whost)
    (prop_hostname id_bdhost str__bi)
    (prop_hostname id_bkhost str__bp)
    (prop_hostname id_brhost str__bw)
    (prop_hostname id_whost str__bb)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_microseconds id_betimedelta num__32)
    (prop_microseconds id_bltimedelta num__39)
    (prop_microseconds id_bstimedelta num__46)
    (prop_microseconds id_xtimedelta num__25)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_seconds id_betimedelta num__31)
    (prop_seconds id_bltimedelta num__38)
    (prop_seconds id_bstimedelta num__45)
    (prop_seconds id_xtimedelta num__24)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_timedelta id_bdhost id_betimedelta)
    (prop_timedelta id_bkhost id_bltimedelta)
    (prop_timedelta id_brhost id_bstimedelta)
    (prop_timedelta id_whost id_xtimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_windows_domain id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_cmrat id_whost)
    (prop_host id_cprat id_bkhost)
    (prop_host id_cnrat id_brhost)
)
)
)