;copyright 2018 the mitre corporation. all rights reserved. approved for public release. distribution unlimited 17-2122.
; for more information on caldera, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; this has 6 hosts, 2 user, 2 admin per host, 2 active account per host
(define (problem p6_hosts_trial_2)
(:domain caldera)
(:objects
    id_hdomaincredential id_ddomaincredential - observeddomaincredential
    id_carat id_cerat id_chrat id_cdrat id_cgrat id_cfrat id_ccrat - observedrat
    id_bntimedelta id_ztimedelta id_stimedelta id_butimedelta id_bgtimedelta id_ltimedelta - observedtimedelta
    str__f str__b str__mary str__j str__bj str__bz str__bs str__q str__br str__x str__cb str__w str__bd str__p str__o str__e str__bc str__by str__bk str__alpha str__james str__bq str__be str__i str__bx str__v str__bl - string
    id_rhost id_bthost id_khost id_yhost id_bmhost id_bfhost - observedhost
    id_cdomainuser id_gdomainuser - observeddomainuser
    num__19 num__34 num__47 num__20 num__27 num__12 num__48 num__13 num__41 num__33 num__26 num__40 - num
    id_cjschtask id_cmschtask id_cnschtask id_ckschtask id_clschtask id_cischtask - observedschtask
    id_crfile id_ctfile id_cpfile id_csfile id_cqfile id_cofile - observedfile
    id_adomain - observeddomain
    id_czshare id_cxshare id_cvshare id_cyshare id_cwshare id_cushare - observedshare
)
(:init
    (knows id_bfhost)
    (knows id_carat)
    (knows_property id_bfhost pfqdn)
    (knows_property id_carat pexecutable)
    (knows_property id_carat phost)
    (mem_cached_domain_creds id_bfhost id_ddomaincredential)
    (mem_cached_domain_creds id_bfhost id_hdomaincredential)
    (mem_cached_domain_creds id_bmhost id_ddomaincredential)
    (mem_cached_domain_creds id_bmhost id_hdomaincredential)
    (mem_cached_domain_creds id_bthost id_ddomaincredential)
    (mem_cached_domain_creds id_bthost id_hdomaincredential)
    (mem_cached_domain_creds id_khost id_ddomaincredential)
    (mem_cached_domain_creds id_khost id_hdomaincredential)
    (mem_cached_domain_creds id_rhost id_ddomaincredential)
    (mem_cached_domain_creds id_rhost id_hdomaincredential)
    (mem_cached_domain_creds id_yhost id_ddomaincredential)
    (mem_cached_domain_creds id_yhost id_hdomaincredential)
    (mem_domain_user_admins id_bfhost id_cdomainuser)
    (mem_domain_user_admins id_bfhost id_gdomainuser)
    (mem_domain_user_admins id_bmhost id_cdomainuser)
    (mem_domain_user_admins id_bmhost id_gdomainuser)
    (mem_domain_user_admins id_bthost id_cdomainuser)
    (mem_domain_user_admins id_bthost id_gdomainuser)
    (mem_domain_user_admins id_khost id_cdomainuser)
    (mem_domain_user_admins id_khost id_gdomainuser)
    (mem_domain_user_admins id_rhost id_cdomainuser)
    (mem_domain_user_admins id_rhost id_gdomainuser)
    (mem_domain_user_admins id_yhost id_cdomainuser)
    (mem_domain_user_admins id_yhost id_gdomainuser)
    (mem_hosts id_adomain id_bfhost)
    (mem_hosts id_adomain id_bmhost)
    (mem_hosts id_adomain id_bthost)
    (mem_hosts id_adomain id_khost)
    (mem_hosts id_adomain id_rhost)
    (mem_hosts id_adomain id_yhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_dc id_bfhost yes)
    (prop_dc id_bmhost no)
    (prop_dc id_bthost no)
    (prop_dc id_khost no)
    (prop_dc id_rhost no)
    (prop_dc id_yhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bfhost str__bl)
    (prop_dns_domain_name id_bmhost str__bs)
    (prop_dns_domain_name id_bthost str__bz)
    (prop_dns_domain_name id_khost str__q)
    (prop_dns_domain_name id_rhost str__x)
    (prop_dns_domain_name id_yhost str__be)
    (prop_domain id_bfhost id_adomain)
    (prop_domain id_bmhost id_adomain)
    (prop_domain id_bthost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_khost id_adomain)
    (prop_domain id_rhost id_adomain)
    (prop_domain id_yhost id_adomain)
    (prop_elevated id_carat yes)
    (prop_executable id_carat str__cb)
    (prop_fqdn id_bfhost str__bk)
    (prop_fqdn id_bmhost str__br)
    (prop_fqdn id_bthost str__by)
    (prop_fqdn id_khost str__p)
    (prop_fqdn id_rhost str__w)
    (prop_fqdn id_yhost str__bd)
    (prop_host id_bgtimedelta id_bfhost)
    (prop_host id_bntimedelta id_bmhost)
    (prop_host id_butimedelta id_bthost)
    (prop_host id_carat id_bfhost)
    (prop_host id_ltimedelta id_khost)
    (prop_host id_stimedelta id_rhost)
    (prop_host id_ztimedelta id_yhost)
    (prop_hostname id_bfhost str__bj)
    (prop_hostname id_bmhost str__bq)
    (prop_hostname id_bthost str__bx)
    (prop_hostname id_khost str__o)
    (prop_hostname id_rhost str__v)
    (prop_hostname id_yhost str__bc)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_microseconds id_bgtimedelta num__34)
    (prop_microseconds id_bntimedelta num__41)
    (prop_microseconds id_butimedelta num__48)
    (prop_microseconds id_ltimedelta num__13)
    (prop_microseconds id_stimedelta num__20)
    (prop_microseconds id_ztimedelta num__27)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_seconds id_bgtimedelta num__33)
    (prop_seconds id_bntimedelta num__40)
    (prop_seconds id_butimedelta num__47)
    (prop_seconds id_ltimedelta num__12)
    (prop_seconds id_stimedelta num__19)
    (prop_seconds id_ztimedelta num__26)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_timedelta id_bfhost id_bgtimedelta)
    (prop_timedelta id_bmhost id_bntimedelta)
    (prop_timedelta id_bthost id_butimedelta)
    (prop_timedelta id_khost id_ltimedelta)
    (prop_timedelta id_rhost id_stimedelta)
    (prop_timedelta id_yhost id_ztimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_windows_domain id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_chrat id_yhost)
    (prop_host id_ccrat id_rhost)
    (prop_host id_cerat id_khost)
    (prop_host id_cdrat id_bthost)
    (prop_host id_cgrat id_bmhost)
)
)
)