(define (problem p3_hosts_trial_9)
(:domain caldera-split)
(:objects
    num__85 - num
    num__92 - num
    num__98 - num
    num__84 - num
    num__99 - num
    num__91 - num
    id_dlhost - observedhost
    id_dehost - observedhost
    id_dshost - observedhost
    str__cz - string
    str__thomas - string
    str__richard - string
    str__n - string
    str__z - string
    str__david - string
    str__john - string
    str__r - string
    str__patricia - string
    str__bc - string
    str__cm - string
    str__jennifer - string
    str__mary - string
    str__cu - string
    str__dd - string
    str__bw - string
    str__cv - string
    str__dorothy - string
    str__cq - string
    str__linda - string
    str__dy - string
    str__dw - string
    str__j - string
    str__maria - string
    str__ci - string
    str__bh - string
    str__ca - string
    str__cb - string
    str__y - string
    str__bs - string
    str__william - string
    str__dr - string
    str__di - string
    str__bg - string
    str__dp - string
    str__ea - string
    str__v - string
    str__joseph - string
    str__margaret - string
    str__bt - string
    str__i - string
    str__q - string
    str__bp - string
    str__cf - string
    str__cr - string
    str__dc - string
    str__m - string
    str__f - string
    str__robert - string
    str__dj - string
    str__michael - string
    str__ce - string
    str__cy - string
    str__alpha - string
    str__barbara - string
    str__dk - string
    str__bk - string
    str__dx - string
    str__e - string
    str__u - string
    str__bo - string
    str__charles - string
    str__cn - string
    str__bx - string
    str__susan - string
    str__james - string
    str__dq - string
    str__bd - string
    str__b - string
    str__elizabeth - string
    str__bl - string
    str__cj - string
    id_eirat - observedrat
    id_ehrat - observedrat
    id_ejrat - observedrat
    id_dzrat - observedrat
    id_adomain - observeddomain
    id_edfile - observedfile
    id_ebfile - observedfile
    id_ecfile - observedfile
    id_bidomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_ckdomainuser - observeddomainuser
    id_cwdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_csdomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_cgdomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_codomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_dadomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_dftimedelta - observedtimedelta
    id_dmtimedelta - observedtimedelta
    id_dttimedelta - observedtimedelta
    id_egshare - observedshare
    id_efshare - observedshare
    id_eeshare - observedshare
    id_cddomaincredential - observeddomaincredential
    id_cldomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_brdomaincredential - observeddomaincredential
    id_cxdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_dbdomaincredential - observeddomaincredential
    id_bvdomaincredential - observeddomaincredential
    id_chdomaincredential - observeddomaincredential
    id_cpdomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_ctdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_emschtask - observedschtask
    id_elschtask - observedschtask
    id_ekschtask - observedschtask
)
(:init
    (knows id_dehost)
    (knows id_dzrat)
    (knows_property id_dehost pfqdn)
    (knows_property id_dzrat pexecutable)
    (knows_property id_dzrat phost)
    (mem_cached_domain_creds id_dehost id_ctdomaincredential)
    (mem_cached_domain_creds id_dehost id_dbdomaincredential)
    (mem_cached_domain_creds id_dlhost id_bvdomaincredential)
    (mem_cached_domain_creds id_dlhost id_cxdomaincredential)
    (mem_cached_domain_creds id_dshost id_bvdomaincredential)
    (mem_cached_domain_creds id_dshost id_pdomaincredential)
    (mem_domain_user_admins id_dehost id_codomainuser)
    (mem_domain_user_admins id_dehost id_csdomainuser)
    (mem_domain_user_admins id_dehost id_sdomainuser)
    (mem_domain_user_admins id_dehost id_wdomainuser)
    (mem_domain_user_admins id_dlhost id_bidomainuser)
    (mem_domain_user_admins id_dlhost id_csdomainuser)
    (mem_domain_user_admins id_dlhost id_kdomainuser)
    (mem_domain_user_admins id_dlhost id_odomainuser)
    (mem_domain_user_admins id_dshost id_bidomainuser)
    (mem_domain_user_admins id_dshost id_budomainuser)
    (mem_domain_user_admins id_dshost id_cgdomainuser)
    (mem_domain_user_admins id_dshost id_codomainuser)
    (mem_hosts id_adomain id_dehost)
    (mem_hosts id_adomain id_dlhost)
    (mem_hosts id_adomain id_dshost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_cgdomainuser id_chdomaincredential)
    (prop_cred id_ckdomainuser id_cldomaincredential)
    (prop_cred id_codomainuser id_cpdomaincredential)
    (prop_cred id_csdomainuser id_ctdomaincredential)
    (prop_cred id_cwdomainuser id_cxdomaincredential)
    (prop_cred id_dadomainuser id_dbdomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_dehost no)
    (prop_dc id_dlhost no)
    (prop_dc id_dshost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_dehost str__dj)
    (prop_dns_domain_name id_dlhost str__dq)
    (prop_dns_domain_name id_dshost str__dx)
    (prop_domain id_badomainuser id_adomain)
    (prop_domain id_bbdomaincredential id_adomain)
    (prop_domain id_bedomainuser id_adomain)
    (prop_domain id_bfdomaincredential id_adomain)
    (prop_domain id_bidomainuser id_adomain)
    (prop_domain id_bjdomaincredential id_adomain)
    (prop_domain id_bmdomainuser id_adomain)
    (prop_domain id_bndomaincredential id_adomain)
    (prop_domain id_bqdomainuser id_adomain)
    (prop_domain id_brdomaincredential id_adomain)
    (prop_domain id_budomainuser id_adomain)
    (prop_domain id_bvdomaincredential id_adomain)
    (prop_domain id_bydomainuser id_adomain)
    (prop_domain id_bzdomaincredential id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ccdomainuser id_adomain)
    (prop_domain id_cddomaincredential id_adomain)
    (prop_domain id_cgdomainuser id_adomain)
    (prop_domain id_chdomaincredential id_adomain)
    (prop_domain id_ckdomainuser id_adomain)
    (prop_domain id_cldomaincredential id_adomain)
    (prop_domain id_codomainuser id_adomain)
    (prop_domain id_cpdomaincredential id_adomain)
    (prop_domain id_csdomainuser id_adomain)
    (prop_domain id_ctdomaincredential id_adomain)
    (prop_domain id_cwdomainuser id_adomain)
    (prop_domain id_cxdomaincredential id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_dadomainuser id_adomain)
    (prop_domain id_dbdomaincredential id_adomain)
    (prop_domain id_dehost id_adomain)
    (prop_domain id_dlhost id_adomain)
    (prop_domain id_dshost id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_dzrat yes)
    (prop_executable id_dzrat str__ea)
    (prop_fqdn id_dehost str__dk)
    (prop_fqdn id_dlhost str__dr)
    (prop_fqdn id_dshost str__dy)
    (prop_host id_dftimedelta id_dehost)
    (prop_host id_dmtimedelta id_dlhost)
    (prop_host id_dttimedelta id_dshost)
    (prop_host id_dzrat id_dehost)
    (prop_hostname id_dehost str__di)
    (prop_hostname id_dlhost str__dp)
    (prop_hostname id_dshost str__dw)
    (prop_is_group id_badomainuser no)
    (prop_is_group id_bedomainuser no)
    (prop_is_group id_bidomainuser no)
    (prop_is_group id_bmdomainuser no)
    (prop_is_group id_bqdomainuser no)
    (prop_is_group id_budomainuser no)
    (prop_is_group id_bydomainuser no)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_ccdomainuser no)
    (prop_is_group id_cgdomainuser no)
    (prop_is_group id_ckdomainuser no)
    (prop_is_group id_codomainuser no)
    (prop_is_group id_csdomainuser no)
    (prop_is_group id_cwdomainuser no)
    (prop_is_group id_dadomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_dftimedelta num__84)
    (prop_microseconds id_dmtimedelta num__91)
    (prop_microseconds id_dttimedelta num__98)
    (prop_password id_bbdomaincredential str__bc)
    (prop_password id_bfdomaincredential str__bg)
    (prop_password id_bjdomaincredential str__bk)
    (prop_password id_bndomaincredential str__bo)
    (prop_password id_brdomaincredential str__bs)
    (prop_password id_bvdomaincredential str__bw)
    (prop_password id_bzdomaincredential str__ca)
    (prop_password id_cddomaincredential str__ce)
    (prop_password id_chdomaincredential str__ci)
    (prop_password id_cldomaincredential str__cm)
    (prop_password id_cpdomaincredential str__cq)
    (prop_password id_ctdomaincredential str__cu)
    (prop_password id_cxdomaincredential str__cy)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_dbdomaincredential str__dc)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_dftimedelta num__85)
    (prop_seconds id_dmtimedelta num__92)
    (prop_seconds id_dttimedelta num__99)
    (prop_sid id_badomainuser str__bd)
    (prop_sid id_bedomainuser str__bh)
    (prop_sid id_bidomainuser str__bl)
    (prop_sid id_bmdomainuser str__bp)
    (prop_sid id_bqdomainuser str__bt)
    (prop_sid id_budomainuser str__bx)
    (prop_sid id_bydomainuser str__cb)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_ccdomainuser str__cf)
    (prop_sid id_cgdomainuser str__cj)
    (prop_sid id_ckdomainuser str__cn)
    (prop_sid id_codomainuser str__cr)
    (prop_sid id_csdomainuser str__cv)
    (prop_sid id_cwdomainuser str__cz)
    (prop_sid id_dadomainuser str__dd)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_dehost id_dftimedelta)
    (prop_timedelta id_dlhost id_dmtimedelta)
    (prop_timedelta id_dshost id_dttimedelta)
    (prop_user id_bbdomaincredential id_badomainuser)
    (prop_user id_bfdomaincredential id_bedomainuser)
    (prop_user id_bjdomaincredential id_bidomainuser)
    (prop_user id_bndomaincredential id_bmdomainuser)
    (prop_user id_brdomaincredential id_bqdomainuser)
    (prop_user id_bvdomaincredential id_budomainuser)
    (prop_user id_bzdomaincredential id_bydomainuser)
    (prop_user id_cddomaincredential id_ccdomainuser)
    (prop_user id_chdomaincredential id_cgdomainuser)
    (prop_user id_cldomaincredential id_ckdomainuser)
    (prop_user id_cpdomaincredential id_codomainuser)
    (prop_user id_ctdomaincredential id_csdomainuser)
    (prop_user id_cxdomaincredential id_cwdomainuser)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_dbdomaincredential id_dadomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_badomainuser str__michael)
    (prop_username id_bedomainuser str__barbara)
    (prop_username id_bidomainuser str__william)
    (prop_username id_bmdomainuser str__elizabeth)
    (prop_username id_bqdomainuser str__david)
    (prop_username id_budomainuser str__jennifer)
    (prop_username id_bydomainuser str__richard)
    (prop_username id_cdomainuser str__james)
    (prop_username id_ccdomainuser str__maria)
    (prop_username id_cgdomainuser str__charles)
    (prop_username id_ckdomainuser str__susan)
    (prop_username id_codomainuser str__joseph)
    (prop_username id_csdomainuser str__margaret)
    (prop_username id_cwdomainuser str__thomas)
    (prop_username id_dadomainuser str__dorothy)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_eirat id_dlhost)
    (prop_host id_ejrat id_dshost)
)
)
(:metric minimize (total-cost))
)