(define (problem p3_hosts_trial_16)
(:domain caldera-split)
(:objects
    id_bitimedelta - observedtimedelta
    id_bbtimedelta - observedtimedelta
    id_bptimedelta - observedtimedelta
    id_cdfile - observedfile
    id_cefile - observedfile
    id_cffile - observedfile
    id_cashare - observedshare
    id_cbshare - observedshare
    id_ccshare - observedshare
    id_kdomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    str__q - string
    str__bs - string
    str__bf - string
    str__bw - string
    str__bt - string
    str__r - string
    str__bu - string
    str__i - string
    str__v - string
    str__u - string
    str__f - string
    str__bm - string
    str__linda - string
    str__bl - string
    str__b - string
    str__john - string
    str__e - string
    str__be - string
    str__bn - string
    str__mary - string
    str__robert - string
    str__j - string
    str__bg - string
    str__alpha - string
    str__patricia - string
    str__m - string
    str__y - string
    str__james - string
    str__n - string
    str__z - string
    id_cgschtask - observedschtask
    id_chschtask - observedschtask
    id_cischtask - observedschtask
    id_byrat - observedrat
    id_bzrat - observedrat
    id_bxrat - observedrat
    id_bvrat - observedrat
    id_bhhost - observedhost
    id_bohost - observedhost
    id_bahost - observedhost
    num__42 - num
    num__43 - num
    num__36 - num
    num__29 - num
    num__28 - num
    num__35 - num
    id_adomain - observeddomain
    id_tdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
)
(:init
    (knows id_bhhost)
    (knows id_bvrat)
    (knows_property id_bhhost pfqdn)
    (knows_property id_bvrat pexecutable)
    (knows_property id_bvrat phost)
    (mem_cached_domain_creds id_bahost id_tdomaincredential)
    (mem_cached_domain_creds id_bhhost id_xdomaincredential)
    (mem_cached_domain_creds id_bohost id_ddomaincredential)
    (mem_domain_user_admins id_bahost id_wdomainuser)
    (mem_domain_user_admins id_bhhost id_odomainuser)
    (mem_domain_user_admins id_bohost id_sdomainuser)
    (mem_hosts id_adomain id_bahost)
    (mem_hosts id_adomain id_bhhost)
    (mem_hosts id_adomain id_bohost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_bahost no)
    (prop_dc id_bhhost yes)
    (prop_dc id_bohost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bahost str__be)
    (prop_dns_domain_name id_bhhost str__bl)
    (prop_dns_domain_name id_bohost str__bs)
    (prop_domain id_bahost id_adomain)
    (prop_domain id_bhhost id_adomain)
    (prop_domain id_bohost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_bvrat yes)
    (prop_executable id_bvrat str__bw)
    (prop_fqdn id_bahost str__bg)
    (prop_fqdn id_bhhost str__bn)
    (prop_fqdn id_bohost str__bu)
    (prop_host id_bbtimedelta id_bahost)
    (prop_host id_bitimedelta id_bhhost)
    (prop_host id_bptimedelta id_bohost)
    (prop_host id_bvrat id_bhhost)
    (prop_hostname id_bahost str__bf)
    (prop_hostname id_bhhost str__bm)
    (prop_hostname id_bohost str__bt)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_bbtimedelta num__28)
    (prop_microseconds id_bitimedelta num__35)
    (prop_microseconds id_bptimedelta num__42)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_bbtimedelta num__29)
    (prop_seconds id_bitimedelta num__36)
    (prop_seconds id_bptimedelta num__43)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_bahost id_bbtimedelta)
    (prop_timedelta id_bhhost id_bitimedelta)
    (prop_timedelta id_bohost id_bptimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_byrat id_bohost)
    (prop_host id_bxrat id_bahost)
)
)
(:metric minimize (total-cost))
)