(define (problem p5_hosts_trial_15)
(:domain caldera-split)
(:objects
    id_deschtask - observedschtask
    id_dbschtask - observedschtask
    id_dcschtask - observedschtask
    id_dfschtask - observedschtask
    id_ddschtask - observedschtask
    num__52 - num
    num__44 - num
    num__59 - num
    num__45 - num
    num__66 - num
    num__58 - num
    num__73 - num
    num__65 - num
    num__51 - num
    num__72 - num
    id_pdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_dhfile - observedfile
    id_dgfile - observedfile
    id_difile - observedfile
    id_dkfile - observedfile
    id_djfile - observedfile
    id_bytimedelta - observedtimedelta
    id_cmtimedelta - observedtimedelta
    id_cftimedelta - observedtimedelta
    id_brtimedelta - observedtimedelta
    id_cttimedelta - observedtimedelta
    id_adomain - observeddomain
    str__e - string
    str__y - string
    str__robert - string
    str__cw - string
    str__j - string
    str__john - string
    str__n - string
    str__q - string
    str__u - string
    str__v - string
    str__bh - string
    str__william - string
    str__cx - string
    str__cc - string
    str__bu - string
    str__ci - string
    str__michael - string
    str__r - string
    str__da - string
    str__cj - string
    str__bo - string
    str__m - string
    str__bc - string
    str__bl - string
    str__patricia - string
    str__james - string
    str__ck - string
    str__linda - string
    str__mary - string
    str__elizabeth - string
    str__cd - string
    str__f - string
    str__bp - string
    str__bd - string
    str__cr - string
    str__bg - string
    str__cp - string
    str__cy - string
    str__z - string
    str__i - string
    str__bv - string
    str__bw - string
    str__cq - string
    str__b - string
    str__cb - string
    str__barbara - string
    str__alpha - string
    str__bk - string
    id_dnshare - observedshare
    id_dpshare - observedshare
    id_dmshare - observedshare
    id_doshare - observedshare
    id_dlshare - observedshare
    id_cehost - observedhost
    id_clhost - observedhost
    id_bxhost - observedhost
    id_bqhost - observedhost
    id_cshost - observedhost
    id_sdomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_dsrat - observedrat
    id_durat - observedrat
    id_drrat - observedrat
    id_dtrat - observedrat
    id_dqrat - observedrat
    id_czrat - observedrat
)
(:init
    (knows id_bqhost)
    (knows id_czrat)
    (knows_property id_bqhost pfqdn)
    (knows_property id_czrat pexecutable)
    (knows_property id_czrat phost)
    (mem_cached_domain_creds id_bqhost id_ddomaincredential)
    (mem_cached_domain_creds id_bqhost id_tdomaincredential)
    (mem_cached_domain_creds id_bxhost id_bbdomaincredential)
    (mem_cached_domain_creds id_bxhost id_ldomaincredential)
    (mem_cached_domain_creds id_cehost id_ddomaincredential)
    (mem_cached_domain_creds id_cehost id_xdomaincredential)
    (mem_cached_domain_creds id_clhost id_ldomaincredential)
    (mem_cached_domain_creds id_clhost id_pdomaincredential)
    (mem_cached_domain_creds id_cshost id_ldomaincredential)
    (mem_cached_domain_creds id_cshost id_pdomaincredential)
    (mem_domain_user_admins id_bqhost id_bidomainuser)
    (mem_domain_user_admins id_bqhost id_bmdomainuser)
    (mem_domain_user_admins id_bxhost id_bidomainuser)
    (mem_domain_user_admins id_bxhost id_wdomainuser)
    (mem_domain_user_admins id_cehost id_bedomainuser)
    (mem_domain_user_admins id_cehost id_cdomainuser)
    (mem_domain_user_admins id_clhost id_odomainuser)
    (mem_domain_user_admins id_clhost id_sdomainuser)
    (mem_domain_user_admins id_cshost id_cdomainuser)
    (mem_domain_user_admins id_cshost id_sdomainuser)
    (mem_hosts id_adomain id_bqhost)
    (mem_hosts id_adomain id_bxhost)
    (mem_hosts id_adomain id_cehost)
    (mem_hosts id_adomain id_clhost)
    (mem_hosts id_adomain id_cshost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_bqhost no)
    (prop_dc id_bxhost yes)
    (prop_dc id_cehost no)
    (prop_dc id_clhost no)
    (prop_dc id_cshost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bqhost str__bw)
    (prop_dns_domain_name id_bxhost str__cd)
    (prop_dns_domain_name id_cehost str__ck)
    (prop_dns_domain_name id_clhost str__cr)
    (prop_dns_domain_name id_cshost str__cy)
    (prop_domain id_badomainuser id_adomain)
    (prop_domain id_bbdomaincredential id_adomain)
    (prop_domain id_bedomainuser id_adomain)
    (prop_domain id_bfdomaincredential id_adomain)
    (prop_domain id_bidomainuser id_adomain)
    (prop_domain id_bjdomaincredential id_adomain)
    (prop_domain id_bmdomainuser id_adomain)
    (prop_domain id_bndomaincredential id_adomain)
    (prop_domain id_bqhost id_adomain)
    (prop_domain id_bxhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_cehost id_adomain)
    (prop_domain id_clhost id_adomain)
    (prop_domain id_cshost id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_czrat yes)
    (prop_executable id_czrat str__da)
    (prop_fqdn id_bqhost str__bu)
    (prop_fqdn id_bxhost str__cb)
    (prop_fqdn id_cehost str__ci)
    (prop_fqdn id_clhost str__cp)
    (prop_fqdn id_cshost str__cw)
    (prop_host id_brtimedelta id_bqhost)
    (prop_host id_bytimedelta id_bxhost)
    (prop_host id_cftimedelta id_cehost)
    (prop_host id_cmtimedelta id_clhost)
    (prop_host id_cttimedelta id_cshost)
    (prop_host id_czrat id_bqhost)
    (prop_hostname id_bqhost str__bv)
    (prop_hostname id_bxhost str__cc)
    (prop_hostname id_cehost str__cj)
    (prop_hostname id_clhost str__cq)
    (prop_hostname id_cshost str__cx)
    (prop_is_group id_badomainuser no)
    (prop_is_group id_bedomainuser no)
    (prop_is_group id_bidomainuser no)
    (prop_is_group id_bmdomainuser no)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_brtimedelta num__44)
    (prop_microseconds id_bytimedelta num__51)
    (prop_microseconds id_cftimedelta num__58)
    (prop_microseconds id_cmtimedelta num__65)
    (prop_microseconds id_cttimedelta num__72)
    (prop_password id_bbdomaincredential str__bc)
    (prop_password id_bfdomaincredential str__bg)
    (prop_password id_bjdomaincredential str__bk)
    (prop_password id_bndomaincredential str__bo)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_brtimedelta num__45)
    (prop_seconds id_bytimedelta num__52)
    (prop_seconds id_cftimedelta num__59)
    (prop_seconds id_cmtimedelta num__66)
    (prop_seconds id_cttimedelta num__73)
    (prop_sid id_badomainuser str__bd)
    (prop_sid id_bedomainuser str__bh)
    (prop_sid id_bidomainuser str__bl)
    (prop_sid id_bmdomainuser str__bp)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_bqhost id_brtimedelta)
    (prop_timedelta id_bxhost id_bytimedelta)
    (prop_timedelta id_cehost id_cftimedelta)
    (prop_timedelta id_clhost id_cmtimedelta)
    (prop_timedelta id_cshost id_cttimedelta)
    (prop_user id_bbdomaincredential id_badomainuser)
    (prop_user id_bfdomaincredential id_bedomainuser)
    (prop_user id_bjdomaincredential id_bidomainuser)
    (prop_user id_bndomaincredential id_bmdomainuser)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_badomainuser str__michael)
    (prop_username id_bedomainuser str__barbara)
    (prop_username id_bidomainuser str__william)
    (prop_username id_bmdomainuser str__elizabeth)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_durat id_bxhost)
    (prop_host id_dqrat id_clhost)
    (prop_host id_dsrat id_cehost)
    (prop_host id_dtrat id_cshost)
)
)
(:metric minimize (total-cost))
)