(define (problem p5_hosts_trial_4)
(:domain caldera-split)
(:objects
    id_bstimedelta - observedtimedelta
    id_betimedelta - observedtimedelta
    id_bltimedelta - observedtimedelta
    id_bztimedelta - observedtimedelta
    id_xtimedelta - observedtimedelta
    id_sdomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_cwschtask - observedschtask
    id_czschtask - observedschtask
    id_daschtask - observedschtask
    id_cxschtask - observedschtask
    id_cyschtask - observedschtask
    id_cpshare - observedshare
    id_cnshare - observedshare
    id_cqshare - observedshare
    id_coshare - observedshare
    id_cmshare - observedshare
    id_csrat - observedrat
    id_curat - observedrat
    id_ctrat - observedrat
    id_cvrat - observedrat
    id_crrat - observedrat
    id_cfrat - observedrat
    id_tdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    str__james - string
    str__bh - string
    str__john - string
    str__mary - string
    str__bx - string
    str__r - string
    str__ba - string
    str__bp - string
    str__bw - string
    str__cd - string
    str__i - string
    str__u - string
    str__bi - string
    str__e - string
    str__b - string
    str__q - string
    str__robert - string
    str__m - string
    str__v - string
    str__bj - string
    str__cc - string
    str__ce - string
    str__f - string
    str__bc - string
    str__alpha - string
    str__bb - string
    str__n - string
    str__j - string
    str__cg - string
    str__bo - string
    str__bq - string
    str__patricia - string
    str__bv - string
    id_cjfile - observedfile
    id_clfile - observedfile
    id_chfile - observedfile
    id_ckfile - observedfile
    id_cifile - observedfile
    id_brhost - observedhost
    id_byhost - observedhost
    id_whost - observedhost
    id_bdhost - observedhost
    id_bkhost - observedhost
    id_adomain - observeddomain
    num__53 - num
    num__46 - num
    num__39 - num
    num__24 - num
    num__38 - num
    num__52 - num
    num__32 - num
    num__45 - num
    num__25 - num
    num__31 - num
)
(:init
    (knows id_byhost)
    (knows id_cfrat)
    (knows_property id_byhost pfqdn)
    (knows_property id_cfrat pexecutable)
    (knows_property id_cfrat phost)
    (mem_cached_domain_creds id_bdhost id_hdomaincredential)
    (mem_cached_domain_creds id_bdhost id_tdomaincredential)
    (mem_cached_domain_creds id_bkhost id_pdomaincredential)
    (mem_cached_domain_creds id_bkhost id_tdomaincredential)
    (mem_cached_domain_creds id_brhost id_hdomaincredential)
    (mem_cached_domain_creds id_brhost id_pdomaincredential)
    (mem_cached_domain_creds id_byhost id_ldomaincredential)
    (mem_cached_domain_creds id_byhost id_tdomaincredential)
    (mem_cached_domain_creds id_whost id_hdomaincredential)
    (mem_cached_domain_creds id_whost id_ldomaincredential)
    (mem_domain_user_admins id_bdhost id_kdomainuser)
    (mem_domain_user_admins id_bdhost id_sdomainuser)
    (mem_domain_user_admins id_bkhost id_odomainuser)
    (mem_domain_user_admins id_bkhost id_sdomainuser)
    (mem_domain_user_admins id_brhost id_cdomainuser)
    (mem_domain_user_admins id_brhost id_sdomainuser)
    (mem_domain_user_admins id_byhost id_cdomainuser)
    (mem_domain_user_admins id_byhost id_gdomainuser)
    (mem_domain_user_admins id_whost id_odomainuser)
    (mem_domain_user_admins id_whost id_sdomainuser)
    (mem_hosts id_adomain id_bdhost)
    (mem_hosts id_adomain id_bkhost)
    (mem_hosts id_adomain id_brhost)
    (mem_hosts id_adomain id_byhost)
    (mem_hosts id_adomain id_whost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_dc id_bdhost yes)
    (prop_dc id_bkhost no)
    (prop_dc id_brhost no)
    (prop_dc id_byhost no)
    (prop_dc id_whost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bdhost str__bh)
    (prop_dns_domain_name id_bkhost str__bo)
    (prop_dns_domain_name id_brhost str__bv)
    (prop_dns_domain_name id_byhost str__cc)
    (prop_dns_domain_name id_whost str__ba)
    (prop_domain id_bdhost id_adomain)
    (prop_domain id_bkhost id_adomain)
    (prop_domain id_brhost id_adomain)
    (prop_domain id_byhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_whost id_adomain)
    (prop_elevated id_cfrat yes)
    (prop_executable id_cfrat str__cg)
    (prop_fqdn id_bdhost str__bi)
    (prop_fqdn id_bkhost str__bp)
    (prop_fqdn id_brhost str__bw)
    (prop_fqdn id_byhost str__cd)
    (prop_fqdn id_whost str__bb)
    (prop_host id_betimedelta id_bdhost)
    (prop_host id_bltimedelta id_bkhost)
    (prop_host id_bstimedelta id_brhost)
    (prop_host id_bztimedelta id_byhost)
    (prop_host id_cfrat id_byhost)
    (prop_host id_xtimedelta id_whost)
    (prop_hostname id_bdhost str__bj)
    (prop_hostname id_bkhost str__bq)
    (prop_hostname id_brhost str__bx)
    (prop_hostname id_byhost str__ce)
    (prop_hostname id_whost str__bc)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_microseconds id_betimedelta num__32)
    (prop_microseconds id_bltimedelta num__39)
    (prop_microseconds id_bstimedelta num__46)
    (prop_microseconds id_bztimedelta num__53)
    (prop_microseconds id_xtimedelta num__25)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_seconds id_betimedelta num__31)
    (prop_seconds id_bltimedelta num__38)
    (prop_seconds id_bstimedelta num__45)
    (prop_seconds id_bztimedelta num__52)
    (prop_seconds id_xtimedelta num__24)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_timedelta id_bdhost id_betimedelta)
    (prop_timedelta id_bkhost id_bltimedelta)
    (prop_timedelta id_brhost id_bstimedelta)
    (prop_timedelta id_byhost id_bztimedelta)
    (prop_timedelta id_whost id_xtimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_curat id_bdhost)
    (prop_host id_ctrat id_whost)
    (prop_host id_csrat id_brhost)
    (prop_host id_cvrat id_bkhost)
)
)
(:metric minimize (total-cost))
)