(define (problem p5_hosts_trial_6)
(:domain caldera-split)
(:objects
    str__b - string
    str__bk - string
    str__e - string
    str__james - string
    str__x - string
    str__j - string
    str__o - string
    str__p - string
    str__bl - string
    str__br - string
    str__bq - string
    str__f - string
    str__q - string
    str__i - string
    str__bd - string
    str__bj - string
    str__v - string
    str__w - string
    str__bc - string
    str__bs - string
    str__mary - string
    str__bu - string
    str__alpha - string
    str__be - string
    num__27 - num
    num__19 - num
    num__13 - num
    num__40 - num
    num__20 - num
    num__41 - num
    num__34 - num
    num__12 - num
    num__33 - num
    num__26 - num
    id_gdomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_cjrat - observedrat
    id_cfrat - observedrat
    id_btrat - observedrat
    id_chrat - observedrat
    id_cirat - observedrat
    id_cgrat - observedrat
    id_bfhost - observedhost
    id_yhost - observedhost
    id_rhost - observedhost
    id_khost - observedhost
    id_bmhost - observedhost
    id_bzshare - observedshare
    id_byshare - observedshare
    id_bxshare - observedshare
    id_bvshare - observedshare
    id_bwshare - observedshare
    id_adomain - observeddomain
    id_ddomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_bntimedelta - observedtimedelta
    id_bgtimedelta - observedtimedelta
    id_stimedelta - observedtimedelta
    id_ztimedelta - observedtimedelta
    id_ltimedelta - observedtimedelta
    id_cdfile - observedfile
    id_cafile - observedfile
    id_cefile - observedfile
    id_cbfile - observedfile
    id_ccfile - observedfile
    id_clschtask - observedschtask
    id_cmschtask - observedschtask
    id_ckschtask - observedschtask
    id_coschtask - observedschtask
    id_cnschtask - observedschtask
)
(:init
    (knows id_btrat)
    (knows id_rhost)
    (knows_property id_btrat pexecutable)
    (knows_property id_btrat phost)
    (knows_property id_rhost pfqdn)
    (mem_cached_domain_creds id_bfhost id_ddomaincredential)
    (mem_cached_domain_creds id_bmhost id_hdomaincredential)
    (mem_cached_domain_creds id_khost id_ddomaincredential)
    (mem_cached_domain_creds id_rhost id_ddomaincredential)
    (mem_cached_domain_creds id_yhost id_hdomaincredential)
    (mem_domain_user_admins id_bfhost id_cdomainuser)
    (mem_domain_user_admins id_bmhost id_cdomainuser)
    (mem_domain_user_admins id_khost id_gdomainuser)
    (mem_domain_user_admins id_rhost id_gdomainuser)
    (mem_domain_user_admins id_yhost id_gdomainuser)
    (mem_hosts id_adomain id_bfhost)
    (mem_hosts id_adomain id_bmhost)
    (mem_hosts id_adomain id_khost)
    (mem_hosts id_adomain id_rhost)
    (mem_hosts id_adomain id_yhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_dc id_bfhost no)
    (prop_dc id_bmhost no)
    (prop_dc id_khost no)
    (prop_dc id_rhost no)
    (prop_dc id_yhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bfhost str__bk)
    (prop_dns_domain_name id_bmhost str__br)
    (prop_dns_domain_name id_khost str__p)
    (prop_dns_domain_name id_rhost str__w)
    (prop_dns_domain_name id_yhost str__bd)
    (prop_domain id_bfhost id_adomain)
    (prop_domain id_bmhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_khost id_adomain)
    (prop_domain id_rhost id_adomain)
    (prop_domain id_yhost id_adomain)
    (prop_elevated id_btrat yes)
    (prop_executable id_btrat str__bu)
    (prop_fqdn id_bfhost str__bl)
    (prop_fqdn id_bmhost str__bs)
    (prop_fqdn id_khost str__q)
    (prop_fqdn id_rhost str__x)
    (prop_fqdn id_yhost str__be)
    (prop_host id_bgtimedelta id_bfhost)
    (prop_host id_bntimedelta id_bmhost)
    (prop_host id_btrat id_rhost)
    (prop_host id_ltimedelta id_khost)
    (prop_host id_stimedelta id_rhost)
    (prop_host id_ztimedelta id_yhost)
    (prop_hostname id_bfhost str__bj)
    (prop_hostname id_bmhost str__bq)
    (prop_hostname id_khost str__o)
    (prop_hostname id_rhost str__v)
    (prop_hostname id_yhost str__bc)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_microseconds id_bgtimedelta num__33)
    (prop_microseconds id_bntimedelta num__40)
    (prop_microseconds id_ltimedelta num__12)
    (prop_microseconds id_stimedelta num__19)
    (prop_microseconds id_ztimedelta num__26)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_seconds id_bgtimedelta num__34)
    (prop_seconds id_bntimedelta num__41)
    (prop_seconds id_ltimedelta num__13)
    (prop_seconds id_stimedelta num__20)
    (prop_seconds id_ztimedelta num__27)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_timedelta id_bfhost id_bgtimedelta)
    (prop_timedelta id_bmhost id_bntimedelta)
    (prop_timedelta id_khost id_ltimedelta)
    (prop_timedelta id_rhost id_stimedelta)
    (prop_timedelta id_yhost id_ztimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_cfrat id_yhost)
    (prop_host id_chrat id_bfhost)
    (prop_host id_cjrat id_khost)
    (prop_host id_cgrat id_bmhost)
)
)
(:metric minimize (total-cost))
)