(define (problem p7_hosts_trial_11)
(:domain caldera-split)
(:objects
    id_kdomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_esfile - observedfile
    id_enfile - observedfile
    id_eofile - observedfile
    id_eqfile - observedfile
    id_epfile - observedfile
    id_emfile - observedfile
    id_erfile - observedfile
    id_dbhost - observedhost
    id_dihost - observedhost
    id_dphost - observedhost
    id_cghost - observedhost
    id_cnhost - observedhost
    id_cuhost - observedhost
    id_dwhost - observedhost
    id_etshare - observedshare
    id_eyshare - observedshare
    id_evshare - observedshare
    id_ezshare - observedshare
    id_exshare - observedshare
    id_ewshare - observedshare
    id_eushare - observedshare
    id_ekrat - observedrat
    id_eirat - observedrat
    id_elrat - observedrat
    id_edrat - observedrat
    id_egrat - observedrat
    id_ehrat - observedrat
    id_ejrat - observedrat
    id_efrat - observedrat
    id_cotimedelta - observedtimedelta
    id_djtimedelta - observedtimedelta
    id_dqtimedelta - observedtimedelta
    id_dctimedelta - observedtimedelta
    id_chtimedelta - observedtimedelta
    id_dxtimedelta - observedtimedelta
    id_cvtimedelta - observedtimedelta
    id_adomain - observeddomain
    str__bp - string
    str__ce - string
    str__df - string
    str__bs - string
    str__cm - string
    str__bt - string
    str__james - string
    str__z - string
    str__bh - string
    str__william - string
    str__cz - string
    str__m - string
    str__dv - string
    str__bk - string
    str__cf - string
    str__maria - string
    str__bw - string
    str__dg - string
    str__cs - string
    str__ee - string
    str__bc - string
    str__bo - string
    str__dh - string
    str__david - string
    str__eb - string
    str__ca - string
    str__dt - string
    str__patricia - string
    str__alpha - string
    str__dm - string
    str__linda - string
    str__michael - string
    str__do - string
    str__u - string
    str__cr - string
    str__du - string
    str__r - string
    str__jennifer - string
    str__elizabeth - string
    str__cb - string
    str__dn - string
    str__i - string
    str__cl - string
    str__y - string
    str__j - string
    str__mary - string
    str__bd - string
    str__b - string
    str__v - string
    str__f - string
    str__n - string
    str__john - string
    str__bl - string
    str__cy - string
    str__ea - string
    str__barbara - string
    str__e - string
    str__ck - string
    str__robert - string
    str__ct - string
    str__da - string
    str__bx - string
    str__bg - string
    str__ec - string
    str__q - string
    str__richard - string
    id_bvdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_brdomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_cddomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_fdschtask - observedschtask
    id_ffschtask - observedschtask
    id_feschtask - observedschtask
    id_fbschtask - observedschtask
    id_faschtask - observedschtask
    id_fcschtask - observedschtask
    id_fgschtask - observedschtask
    num__102 - num
    num__74 - num
    num__89 - num
    num__95 - num
    num__67 - num
    num__75 - num
    num__88 - num
    num__103 - num
    num__82 - num
    num__81 - num
    num__61 - num
    num__96 - num
    num__68 - num
    num__60 - num
)
(:init
    (knows id_dphost)
    (knows id_edrat)
    (knows_property id_dphost pfqdn)
    (knows_property id_edrat pexecutable)
    (knows_property id_edrat phost)
    (mem_cached_domain_creds id_cghost id_pdomaincredential)
    (mem_cached_domain_creds id_cghost id_tdomaincredential)
    (mem_cached_domain_creds id_cnhost id_bzdomaincredential)
    (mem_cached_domain_creds id_cnhost id_cddomaincredential)
    (mem_cached_domain_creds id_cuhost id_brdomaincredential)
    (mem_cached_domain_creds id_cuhost id_xdomaincredential)
    (mem_cached_domain_creds id_dbhost id_bfdomaincredential)
    (mem_cached_domain_creds id_dbhost id_pdomaincredential)
    (mem_cached_domain_creds id_dihost id_bfdomaincredential)
    (mem_cached_domain_creds id_dihost id_cddomaincredential)
    (mem_cached_domain_creds id_dphost id_bbdomaincredential)
    (mem_cached_domain_creds id_dphost id_bndomaincredential)
    (mem_cached_domain_creds id_dwhost id_bbdomaincredential)
    (mem_cached_domain_creds id_dwhost id_ldomaincredential)
    (mem_domain_user_admins id_cghost id_bidomainuser)
    (mem_domain_user_admins id_cghost id_bmdomainuser)
    (mem_domain_user_admins id_cnhost id_odomainuser)
    (mem_domain_user_admins id_cnhost id_wdomainuser)
    (mem_domain_user_admins id_cuhost id_bmdomainuser)
    (mem_domain_user_admins id_cuhost id_bydomainuser)
    (mem_domain_user_admins id_dbhost id_bidomainuser)
    (mem_domain_user_admins id_dbhost id_ccdomainuser)
    (mem_domain_user_admins id_dihost id_bqdomainuser)
    (mem_domain_user_admins id_dihost id_cdomainuser)
    (mem_domain_user_admins id_dphost id_bqdomainuser)
    (mem_domain_user_admins id_dphost id_sdomainuser)
    (mem_domain_user_admins id_dwhost id_bedomainuser)
    (mem_domain_user_admins id_dwhost id_cdomainuser)
    (mem_hosts id_adomain id_cghost)
    (mem_hosts id_adomain id_cnhost)
    (mem_hosts id_adomain id_cuhost)
    (mem_hosts id_adomain id_dbhost)
    (mem_hosts id_adomain id_dihost)
    (mem_hosts id_adomain id_dphost)
    (mem_hosts id_adomain id_dwhost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_cghost no)
    (prop_dc id_cnhost no)
    (prop_dc id_cuhost no)
    (prop_dc id_dbhost no)
    (prop_dc id_dihost no)
    (prop_dc id_dphost no)
    (prop_dc id_dwhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_cghost str__cl)
    (prop_dns_domain_name id_cnhost str__cs)
    (prop_dns_domain_name id_cuhost str__cz)
    (prop_dns_domain_name id_dbhost str__dg)
    (prop_dns_domain_name id_dihost str__dn)
    (prop_dns_domain_name id_dphost str__du)
    (prop_dns_domain_name id_dwhost str__eb)
    (prop_domain id_badomainuser id_adomain)
    (prop_domain id_bbdomaincredential id_adomain)
    (prop_domain id_bedomainuser id_adomain)
    (prop_domain id_bfdomaincredential id_adomain)
    (prop_domain id_bidomainuser id_adomain)
    (prop_domain id_bjdomaincredential id_adomain)
    (prop_domain id_bmdomainuser id_adomain)
    (prop_domain id_bndomaincredential id_adomain)
    (prop_domain id_bqdomainuser id_adomain)
    (prop_domain id_brdomaincredential id_adomain)
    (prop_domain id_budomainuser id_adomain)
    (prop_domain id_bvdomaincredential id_adomain)
    (prop_domain id_bydomainuser id_adomain)
    (prop_domain id_bzdomaincredential id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ccdomainuser id_adomain)
    (prop_domain id_cddomaincredential id_adomain)
    (prop_domain id_cghost id_adomain)
    (prop_domain id_cnhost id_adomain)
    (prop_domain id_cuhost id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_dbhost id_adomain)
    (prop_domain id_dihost id_adomain)
    (prop_domain id_dphost id_adomain)
    (prop_domain id_dwhost id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_edrat yes)
    (prop_executable id_edrat str__ee)
    (prop_fqdn id_cghost str__ck)
    (prop_fqdn id_cnhost str__cr)
    (prop_fqdn id_cuhost str__cy)
    (prop_fqdn id_dbhost str__df)
    (prop_fqdn id_dihost str__dm)
    (prop_fqdn id_dphost str__dt)
    (prop_fqdn id_dwhost str__ea)
    (prop_host id_chtimedelta id_cghost)
    (prop_host id_cotimedelta id_cnhost)
    (prop_host id_cvtimedelta id_cuhost)
    (prop_host id_dctimedelta id_dbhost)
    (prop_host id_djtimedelta id_dihost)
    (prop_host id_dqtimedelta id_dphost)
    (prop_host id_dxtimedelta id_dwhost)
    (prop_host id_edrat id_dphost)
    (prop_hostname id_cghost str__cm)
    (prop_hostname id_cnhost str__ct)
    (prop_hostname id_cuhost str__da)
    (prop_hostname id_dbhost str__dh)
    (prop_hostname id_dihost str__do)
    (prop_hostname id_dphost str__dv)
    (prop_hostname id_dwhost str__ec)
    (prop_is_group id_badomainuser no)
    (prop_is_group id_bedomainuser no)
    (prop_is_group id_bidomainuser no)
    (prop_is_group id_bmdomainuser no)
    (prop_is_group id_bqdomainuser no)
    (prop_is_group id_budomainuser no)
    (prop_is_group id_bydomainuser no)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_ccdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_chtimedelta num__61)
    (prop_microseconds id_cotimedelta num__68)
    (prop_microseconds id_cvtimedelta num__75)
    (prop_microseconds id_dctimedelta num__82)
    (prop_microseconds id_djtimedelta num__89)
    (prop_microseconds id_dqtimedelta num__96)
    (prop_microseconds id_dxtimedelta num__103)
    (prop_password id_bbdomaincredential str__bc)
    (prop_password id_bfdomaincredential str__bg)
    (prop_password id_bjdomaincredential str__bk)
    (prop_password id_bndomaincredential str__bo)
    (prop_password id_brdomaincredential str__bs)
    (prop_password id_bvdomaincredential str__bw)
    (prop_password id_bzdomaincredential str__ca)
    (prop_password id_cddomaincredential str__ce)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_chtimedelta num__60)
    (prop_seconds id_cotimedelta num__67)
    (prop_seconds id_cvtimedelta num__74)
    (prop_seconds id_dctimedelta num__81)
    (prop_seconds id_djtimedelta num__88)
    (prop_seconds id_dqtimedelta num__95)
    (prop_seconds id_dxtimedelta num__102)
    (prop_sid id_badomainuser str__bd)
    (prop_sid id_bedomainuser str__bh)
    (prop_sid id_bidomainuser str__bl)
    (prop_sid id_bmdomainuser str__bp)
    (prop_sid id_bqdomainuser str__bt)
    (prop_sid id_budomainuser str__bx)
    (prop_sid id_bydomainuser str__cb)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_ccdomainuser str__cf)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_cghost id_chtimedelta)
    (prop_timedelta id_cnhost id_cotimedelta)
    (prop_timedelta id_cuhost id_cvtimedelta)
    (prop_timedelta id_dbhost id_dctimedelta)
    (prop_timedelta id_dihost id_djtimedelta)
    (prop_timedelta id_dphost id_dqtimedelta)
    (prop_timedelta id_dwhost id_dxtimedelta)
    (prop_user id_bbdomaincredential id_badomainuser)
    (prop_user id_bfdomaincredential id_bedomainuser)
    (prop_user id_bjdomaincredential id_bidomainuser)
    (prop_user id_bndomaincredential id_bmdomainuser)
    (prop_user id_brdomaincredential id_bqdomainuser)
    (prop_user id_bvdomaincredential id_budomainuser)
    (prop_user id_bzdomaincredential id_bydomainuser)
    (prop_user id_cddomaincredential id_ccdomainuser)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_badomainuser str__michael)
    (prop_username id_bedomainuser str__barbara)
    (prop_username id_bidomainuser str__william)
    (prop_username id_bmdomainuser str__elizabeth)
    (prop_username id_bqdomainuser str__david)
    (prop_username id_budomainuser str__jennifer)
    (prop_username id_bydomainuser str__richard)
    (prop_username id_cdomainuser str__james)
    (prop_username id_ccdomainuser str__maria)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_ehrat id_cuhost)
    (prop_host id_egrat id_cnhost)
    (prop_host id_elrat id_cghost)
    (prop_host id_eirat id_dihost)
    (prop_host id_ekrat id_dbhost)
    (prop_host id_efrat id_dwhost)
)
)
(:metric minimize (total-cost))
)