(define (problem p8_hosts_trial_8)
(:domain caldera-split)
(:objects
    num__238 - num
    num__211 - num
    num__231 - num
    num__203 - num
    num__239 - num
    num__232 - num
    num__196 - num
    num__217 - num
    num__204 - num
    num__197 - num
    num__218 - num
    num__224 - num
    num__225 - num
    num__245 - num
    num__246 - num
    num__210 - num
    id_cgdomainuser - observeddomainuser
    id_fedomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_ckdomainuser - observeddomainuser
    id_hidomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_fmdomainuser - observeddomainuser
    id_dydomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_dudomainuser - observeddomainuser
    id_fydomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_hadomainuser - observeddomainuser
    id_dqdomainuser - observeddomainuser
    id_esdomainuser - observeddomainuser
    id_eodomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_dmdomainuser - observeddomainuser
    id_fudomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_codomainuser - observeddomainuser
    id_fqdomainuser - observeddomainuser
    id_godomainuser - observeddomainuser
    id_gwdomainuser - observeddomainuser
    id_ggdomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_gcdomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_gsdomainuser - observeddomainuser
    id_fadomainuser - observeddomainuser
    id_csdomainuser - observeddomainuser
    id_fidomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_gkdomainuser - observeddomainuser
    id_ewdomainuser - observeddomainuser
    id_hedomainuser - observeddomainuser
    id_egdomainuser - observeddomainuser
    id_cwdomainuser - observeddomainuser
    id_didomainuser - observeddomainuser
    id_ekdomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_dedomainuser - observeddomainuser
    id_ecdomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_dadomainuser - observeddomainuser
    id_jdtimedelta - observedtimedelta
    id_iitimedelta - observedtimedelta
    id_iptimedelta - observedtimedelta
    id_hutimedelta - observedtimedelta
    id_ibtimedelta - observedtimedelta
    id_jktimedelta - observedtimedelta
    id_iwtimedelta - observedtimedelta
    id_hntimedelta - observedtimedelta
    id_iahost - observedhost
    id_jjhost - observedhost
    id_jchost - observedhost
    id_ivhost - observedhost
    id_hthost - observedhost
    id_ihhost - observedhost
    id_iohost - observedhost
    id_hmhost - observedhost
    id_gpdomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_ctdomaincredential - observeddomaincredential
    id_fndomaincredential - observeddomaincredential
    id_gldomaincredential - observeddomaincredential
    id_cldomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_dvdomaincredential - observeddomaincredential
    id_dzdomaincredential - observeddomaincredential
    id_eldomaincredential - observeddomaincredential
    id_epdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_frdomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_gxdomaincredential - observeddomaincredential
    id_dbdomaincredential - observeddomaincredential
    id_gtdomaincredential - observeddomaincredential
    id_drdomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_fbdomaincredential - observeddomaincredential
    id_cddomaincredential - observeddomaincredential
    id_ffdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_ehdomaincredential - observeddomaincredential
    id_brdomaincredential - observeddomaincredential
    id_djdomaincredential - observeddomaincredential
    id_hfdomaincredential - observeddomaincredential
    id_hjdomaincredential - observeddomaincredential
    id_cxdomaincredential - observeddomaincredential
    id_dndomaincredential - observeddomaincredential
    id_eddomaincredential - observeddomaincredential
    id_fvdomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_hbdomaincredential - observeddomaincredential
    id_chdomaincredential - observeddomaincredential
    id_fzdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_bvdomaincredential - observeddomaincredential
    id_cpdomaincredential - observeddomaincredential
    id_dfdomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_gddomaincredential - observeddomaincredential
    id_etdomaincredential - observeddomaincredential
    id_ghdomaincredential - observeddomaincredential
    id_fjdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_exdomaincredential - observeddomaincredential
    str__jennifer - string
    str__hz - string
    str__sandra - string
    str__hl - string
    str__ce - string
    str__cm - string
    str__ja - string
    str__cn - string
    str__nancy - string
    str__christopher - string
    str__bx - string
    str__is - string
    str__ef - string
    str__dl - string
    str__edward - string
    str__dt - string
    str__helen - string
    str__fl - string
    str__ei - string
    str__steven - string
    str__ej - string
    str__margaret - string
    str__barbara - string
    str__it - string
    str__ie - string
    str__ruth - string
    str__bl - string
    str__david - string
    str__dg - string
    str__ee - string
    str__ci - string
    str__jo - string
    str__george - string
    str__gz - string
    str__hh - string
    str__robert - string
    str__dd - string
    str__ev - string
    str__gn - string
    str__fk - string
    str__anthony - string
    str__dc - string
    str__fo - string
    str__gj - string
    str__ge - string
    str__kimberly - string
    str__eu - string
    str__jason - string
    str__im - string
    str__fs - string
    str__carol - string
    str__dk - string
    str__hd - string
    str__cr - string
    str__i - string
    str__ft - string
    str__james - string
    str__dh - string
    str__patricia - string
    str__gr - string
    str__hc - string
    str__eb - string
    str__u - string
    str__thomas - string
    str__hq - string
    str__dp - string
    str__b - string
    str__jr - string
    str__joseph - string
    str__jp - string
    str__n - string
    str__elizabeth - string
    str__q - string
    str__gb - string
    str__hx - string
    str__gq - string
    str__iz - string
    str__hs - string
    str__fg - string
    str__kevin - string
    str__alpha - string
    str__ig - string
    str__john - string
    str__gm - string
    str__ez - string
    str__laura - string
    str__kenneth - string
    str__bo - string
    str__gy - string
    str__iu - string
    str__if - string
    str__donald - string
    str__cb - string
    str__karen - string
    str__fc - string
    str__donna - string
    str__mary - string
    str__cj - string
    str__bd - string
    str__em - string
    str__fw - string
    str__gi - string
    str__sharon - string
    str__fp - string
    str__dorothy - string
    str__betty - string
    str__cz - string
    str__v - string
    str__ea - string
    str__e - string
    str__in - string
    str__ds - string
    str__fd - string
    str__ey - string
    str__hg - string
    str__cu - string
    str__cq - string
    str__hr - string
    str__bp - string
    str__fh - string
    str__bw - string
    str__ca - string
    str__jh - string
    str__cf - string
    str__gu - string
    str__eq - string
    str__linda - string
    str__paul - string
    str__jb - string
    str__y - string
    str__hy - string
    str__fx - string
    str__dx - string
    str__jn - string
    str__charles - string
    str__ji - string
    str__bg - string
    str__daniel - string
    str__brian - string
    str__r - string
    str__do - string
    str__dw - string
    str__m - string
    str__hk - string
    str__richard - string
    str__gv - string
    str__bs - string
    str__cy - string
    str__sarah - string
    str__bk - string
    str__cv - string
    str__gf - string
    str__z - string
    str__susan - string
    str__michael - string
    str__en - string
    str__ronald - string
    str__bc - string
    str__mark - string
    str__ga - string
    str__bh - string
    str__j - string
    str__william - string
    str__f - string
    str__jg - string
    str__maria - string
    str__er - string
    str__lisa - string
    str__il - string
    str__michelle - string
    str__bt - string
    id_adomain - observeddomain
    id_jqrat - observedrat
    id_jxrat - observedrat
    id_jvrat - observedrat
    id_jsrat - observedrat
    id_jurat - observedrat
    id_jwrat - observedrat
    id_jtrat - observedrat
    id_jyrat - observedrat
    id_jzrat - observedrat
    id_kcschtask - observedschtask
    id_kfschtask - observedschtask
    id_kbschtask - observedschtask
    id_kgschtask - observedschtask
    id_khschtask - observedschtask
    id_kaschtask - observedschtask
    id_kdschtask - observedschtask
    id_keschtask - observedschtask
    id_ktshare - observedshare
    id_ksshare - observedshare
    id_kqshare - observedshare
    id_kvshare - observedshare
    id_kushare - observedshare
    id_kxshare - observedshare
    id_kwshare - observedshare
    id_krshare - observedshare
    id_knfile - observedfile
    id_kmfile - observedfile
    id_kkfile - observedfile
    id_kifile - observedfile
    id_kjfile - observedfile
    id_kofile - observedfile
    id_kpfile - observedfile
    id_klfile - observedfile
)
(:init
    (knows id_hthost)
    (knows id_jqrat)
    (knows_property id_hthost pfqdn)
    (knows_property id_jqrat pexecutable)
    (knows_property id_jqrat phost)
    (mem_cached_domain_creds id_hmhost id_cpdomaincredential)
    (mem_cached_domain_creds id_hmhost id_dzdomaincredential)
    (mem_cached_domain_creds id_hmhost id_gpdomaincredential)
    (mem_cached_domain_creds id_hmhost id_hfdomaincredential)
    (mem_cached_domain_creds id_hthost id_bjdomaincredential)
    (mem_cached_domain_creds id_hthost id_dzdomaincredential)
    (mem_cached_domain_creds id_hthost id_eddomaincredential)
    (mem_cached_domain_creds id_hthost id_pdomaincredential)
    (mem_cached_domain_creds id_iahost id_cddomaincredential)
    (mem_cached_domain_creds id_iahost id_dfdomaincredential)
    (mem_cached_domain_creds id_iahost id_fvdomaincredential)
    (mem_cached_domain_creds id_iahost id_hfdomaincredential)
    (mem_cached_domain_creds id_ihhost id_ddomaincredential)
    (mem_cached_domain_creds id_ihhost id_exdomaincredential)
    (mem_cached_domain_creds id_ihhost id_fvdomaincredential)
    (mem_cached_domain_creds id_ihhost id_pdomaincredential)
    (mem_cached_domain_creds id_iohost id_cldomaincredential)
    (mem_cached_domain_creds id_iohost id_cpdomaincredential)
    (mem_cached_domain_creds id_iohost id_dvdomaincredential)
    (mem_cached_domain_creds id_iohost id_eldomaincredential)
    (mem_cached_domain_creds id_ivhost id_cxdomaincredential)
    (mem_cached_domain_creds id_ivhost id_fndomaincredential)
    (mem_cached_domain_creds id_ivhost id_gtdomaincredential)
    (mem_cached_domain_creds id_ivhost id_hbdomaincredential)
    (mem_cached_domain_creds id_jchost id_cldomaincredential)
    (mem_cached_domain_creds id_jchost id_drdomaincredential)
    (mem_cached_domain_creds id_jchost id_dzdomaincredential)
    (mem_cached_domain_creds id_jchost id_exdomaincredential)
    (mem_cached_domain_creds id_jjhost id_cxdomaincredential)
    (mem_cached_domain_creds id_jjhost id_dbdomaincredential)
    (mem_cached_domain_creds id_jjhost id_gldomaincredential)
    (mem_cached_domain_creds id_jjhost id_pdomaincredential)
    (mem_domain_user_admins id_hmhost id_cwdomainuser)
    (mem_domain_user_admins id_hmhost id_dedomainuser)
    (mem_domain_user_admins id_hmhost id_ecdomainuser)
    (mem_domain_user_admins id_hmhost id_gwdomainuser)
    (mem_domain_user_admins id_hmhost id_kdomainuser)
    (mem_domain_user_admins id_hthost id_csdomainuser)
    (mem_domain_user_admins id_hthost id_dydomainuser)
    (mem_domain_user_admins id_hthost id_fadomainuser)
    (mem_domain_user_admins id_hthost id_fqdomainuser)
    (mem_domain_user_admins id_hthost id_hadomainuser)
    (mem_domain_user_admins id_iahost id_bedomainuser)
    (mem_domain_user_admins id_iahost id_fydomainuser)
    (mem_domain_user_admins id_iahost id_kdomainuser)
    (mem_domain_user_admins id_iahost id_odomainuser)
    (mem_domain_user_admins id_iahost id_wdomainuser)
    (mem_domain_user_admins id_ihhost id_bidomainuser)
    (mem_domain_user_admins id_ihhost id_cwdomainuser)
    (mem_domain_user_admins id_ihhost id_dudomainuser)
    (mem_domain_user_admins id_ihhost id_fqdomainuser)
    (mem_domain_user_admins id_ihhost id_wdomainuser)
    (mem_domain_user_admins id_iohost id_badomainuser)
    (mem_domain_user_admins id_iohost id_cdomainuser)
    (mem_domain_user_admins id_iohost id_codomainuser)
    (mem_domain_user_admins id_iohost id_dedomainuser)
    (mem_domain_user_admins id_iohost id_didomainuser)
    (mem_domain_user_admins id_ivhost id_bedomainuser)
    (mem_domain_user_admins id_ivhost id_codomainuser)
    (mem_domain_user_admins id_ivhost id_dmdomainuser)
    (mem_domain_user_admins id_ivhost id_gsdomainuser)
    (mem_domain_user_admins id_ivhost id_hidomainuser)
    (mem_domain_user_admins id_jchost id_cdomainuser)
    (mem_domain_user_admins id_jchost id_codomainuser)
    (mem_domain_user_admins id_jchost id_csdomainuser)
    (mem_domain_user_admins id_jchost id_kdomainuser)
    (mem_domain_user_admins id_jchost id_odomainuser)
    (mem_domain_user_admins id_jjhost id_bmdomainuser)
    (mem_domain_user_admins id_jjhost id_bydomainuser)
    (mem_domain_user_admins id_jjhost id_codomainuser)
    (mem_domain_user_admins id_jjhost id_ewdomainuser)
    (mem_domain_user_admins id_jjhost id_kdomainuser)
    (mem_hosts id_adomain id_hmhost)
    (mem_hosts id_adomain id_hthost)
    (mem_hosts id_adomain id_iahost)
    (mem_hosts id_adomain id_ihhost)
    (mem_hosts id_adomain id_iohost)
    (mem_hosts id_adomain id_ivhost)
    (mem_hosts id_adomain id_jchost)
    (mem_hosts id_adomain id_jjhost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_cgdomainuser id_chdomaincredential)
    (prop_cred id_ckdomainuser id_cldomaincredential)
    (prop_cred id_codomainuser id_cpdomaincredential)
    (prop_cred id_csdomainuser id_ctdomaincredential)
    (prop_cred id_cwdomainuser id_cxdomaincredential)
    (prop_cred id_dadomainuser id_dbdomaincredential)
    (prop_cred id_dedomainuser id_dfdomaincredential)
    (prop_cred id_didomainuser id_djdomaincredential)
    (prop_cred id_dmdomainuser id_dndomaincredential)
    (prop_cred id_dqdomainuser id_drdomaincredential)
    (prop_cred id_dudomainuser id_dvdomaincredential)
    (prop_cred id_dydomainuser id_dzdomaincredential)
    (prop_cred id_ecdomainuser id_eddomaincredential)
    (prop_cred id_egdomainuser id_ehdomaincredential)
    (prop_cred id_ekdomainuser id_eldomaincredential)
    (prop_cred id_eodomainuser id_epdomaincredential)
    (prop_cred id_esdomainuser id_etdomaincredential)
    (prop_cred id_ewdomainuser id_exdomaincredential)
    (prop_cred id_fadomainuser id_fbdomaincredential)
    (prop_cred id_fedomainuser id_ffdomaincredential)
    (prop_cred id_fidomainuser id_fjdomaincredential)
    (prop_cred id_fmdomainuser id_fndomaincredential)
    (prop_cred id_fqdomainuser id_frdomaincredential)
    (prop_cred id_fudomainuser id_fvdomaincredential)
    (prop_cred id_fydomainuser id_fzdomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_gcdomainuser id_gddomaincredential)
    (prop_cred id_ggdomainuser id_ghdomaincredential)
    (prop_cred id_gkdomainuser id_gldomaincredential)
    (prop_cred id_godomainuser id_gpdomaincredential)
    (prop_cred id_gsdomainuser id_gtdomaincredential)
    (prop_cred id_gwdomainuser id_gxdomaincredential)
    (prop_cred id_hadomainuser id_hbdomaincredential)
    (prop_cred id_hedomainuser id_hfdomaincredential)
    (prop_cred id_hidomainuser id_hjdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_hmhost yes)
    (prop_dc id_hthost yes)
    (prop_dc id_iahost no)
    (prop_dc id_ihhost no)
    (prop_dc id_iohost no)
    (prop_dc id_ivhost no)
    (prop_dc id_jchost no)
    (prop_dc id_jjhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_hmhost str__hr)
    (prop_dns_domain_name id_hthost str__hy)
    (prop_dns_domain_name id_iahost str__if)
    (prop_dns_domain_name id_ihhost str__im)
    (prop_dns_domain_name id_iohost str__it)
    (prop_dns_domain_name id_ivhost str__ja)
    (prop_dns_domain_name id_jchost str__jh)
    (prop_dns_domain_name id_jjhost str__jo)
    (prop_domain id_badomainuser id_adomain)
    (prop_domain id_bbdomaincredential id_adomain)
    (prop_domain id_bedomainuser id_adomain)
    (prop_domain id_bfdomaincredential id_adomain)
    (prop_domain id_bidomainuser id_adomain)
    (prop_domain id_bjdomaincredential id_adomain)
    (prop_domain id_bmdomainuser id_adomain)
    (prop_domain id_bndomaincredential id_adomain)
    (prop_domain id_bqdomainuser id_adomain)
    (prop_domain id_brdomaincredential id_adomain)
    (prop_domain id_budomainuser id_adomain)
    (prop_domain id_bvdomaincredential id_adomain)
    (prop_domain id_bydomainuser id_adomain)
    (prop_domain id_bzdomaincredential id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ccdomainuser id_adomain)
    (prop_domain id_cddomaincredential id_adomain)
    (prop_domain id_cgdomainuser id_adomain)
    (prop_domain id_chdomaincredential id_adomain)
    (prop_domain id_ckdomainuser id_adomain)
    (prop_domain id_cldomaincredential id_adomain)
    (prop_domain id_codomainuser id_adomain)
    (prop_domain id_cpdomaincredential id_adomain)
    (prop_domain id_csdomainuser id_adomain)
    (prop_domain id_ctdomaincredential id_adomain)
    (prop_domain id_cwdomainuser id_adomain)
    (prop_domain id_cxdomaincredential id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_dadomainuser id_adomain)
    (prop_domain id_dbdomaincredential id_adomain)
    (prop_domain id_dedomainuser id_adomain)
    (prop_domain id_dfdomaincredential id_adomain)
    (prop_domain id_didomainuser id_adomain)
    (prop_domain id_djdomaincredential id_adomain)
    (prop_domain id_dmdomainuser id_adomain)
    (prop_domain id_dndomaincredential id_adomain)
    (prop_domain id_dqdomainuser id_adomain)
    (prop_domain id_drdomaincredential id_adomain)
    (prop_domain id_dudomainuser id_adomain)
    (prop_domain id_dvdomaincredential id_adomain)
    (prop_domain id_dydomainuser id_adomain)
    (prop_domain id_dzdomaincredential id_adomain)
    (prop_domain id_ecdomainuser id_adomain)
    (prop_domain id_eddomaincredential id_adomain)
    (prop_domain id_egdomainuser id_adomain)
    (prop_domain id_ehdomaincredential id_adomain)
    (prop_domain id_ekdomainuser id_adomain)
    (prop_domain id_eldomaincredential id_adomain)
    (prop_domain id_eodomainuser id_adomain)
    (prop_domain id_epdomaincredential id_adomain)
    (prop_domain id_esdomainuser id_adomain)
    (prop_domain id_etdomaincredential id_adomain)
    (prop_domain id_ewdomainuser id_adomain)
    (prop_domain id_exdomaincredential id_adomain)
    (prop_domain id_fadomainuser id_adomain)
    (prop_domain id_fbdomaincredential id_adomain)
    (prop_domain id_fedomainuser id_adomain)
    (prop_domain id_ffdomaincredential id_adomain)
    (prop_domain id_fidomainuser id_adomain)
    (prop_domain id_fjdomaincredential id_adomain)
    (prop_domain id_fmdomainuser id_adomain)
    (prop_domain id_fndomaincredential id_adomain)
    (prop_domain id_fqdomainuser id_adomain)
    (prop_domain id_frdomaincredential id_adomain)
    (prop_domain id_fudomainuser id_adomain)
    (prop_domain id_fvdomaincredential id_adomain)
    (prop_domain id_fydomainuser id_adomain)
    (prop_domain id_fzdomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_gcdomainuser id_adomain)
    (prop_domain id_gddomaincredential id_adomain)
    (prop_domain id_ggdomainuser id_adomain)
    (prop_domain id_ghdomaincredential id_adomain)
    (prop_domain id_gkdomainuser id_adomain)
    (prop_domain id_gldomaincredential id_adomain)
    (prop_domain id_godomainuser id_adomain)
    (prop_domain id_gpdomaincredential id_adomain)
    (prop_domain id_gsdomainuser id_adomain)
    (prop_domain id_gtdomaincredential id_adomain)
    (prop_domain id_gwdomainuser id_adomain)
    (prop_domain id_gxdomaincredential id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_hadomainuser id_adomain)
    (prop_domain id_hbdomaincredential id_adomain)
    (prop_domain id_hedomainuser id_adomain)
    (prop_domain id_hfdomaincredential id_adomain)
    (prop_domain id_hidomainuser id_adomain)
    (prop_domain id_hjdomaincredential id_adomain)
    (prop_domain id_hmhost id_adomain)
    (prop_domain id_hthost id_adomain)
    (prop_domain id_iahost id_adomain)
    (prop_domain id_ihhost id_adomain)
    (prop_domain id_iohost id_adomain)
    (prop_domain id_ivhost id_adomain)
    (prop_domain id_jchost id_adomain)
    (prop_domain id_jjhost id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_jqrat yes)
    (prop_executable id_jqrat str__jr)
    (prop_fqdn id_hmhost str__hs)
    (prop_fqdn id_hthost str__hz)
    (prop_fqdn id_iahost str__ig)
    (prop_fqdn id_ihhost str__in)
    (prop_fqdn id_iohost str__iu)
    (prop_fqdn id_ivhost str__jb)
    (prop_fqdn id_jchost str__ji)
    (prop_fqdn id_jjhost str__jp)
    (prop_host id_hntimedelta id_hmhost)
    (prop_host id_hutimedelta id_hthost)
    (prop_host id_ibtimedelta id_iahost)
    (prop_host id_iitimedelta id_ihhost)
    (prop_host id_iptimedelta id_iohost)
    (prop_host id_iwtimedelta id_ivhost)
    (prop_host id_jdtimedelta id_jchost)
    (prop_host id_jktimedelta id_jjhost)
    (prop_host id_jqrat id_hthost)
    (prop_hostname id_hmhost str__hq)
    (prop_hostname id_hthost str__hx)
    (prop_hostname id_iahost str__ie)
    (prop_hostname id_ihhost str__il)
    (prop_hostname id_iohost str__is)
    (prop_hostname id_ivhost str__iz)
    (prop_hostname id_jchost str__jg)
    (prop_hostname id_jjhost str__jn)
    (prop_is_group id_badomainuser no)
    (prop_is_group id_bedomainuser no)
    (prop_is_group id_bidomainuser no)
    (prop_is_group id_bmdomainuser no)
    (prop_is_group id_bqdomainuser no)
    (prop_is_group id_budomainuser no)
    (prop_is_group id_bydomainuser no)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_ccdomainuser no)
    (prop_is_group id_cgdomainuser no)
    (prop_is_group id_ckdomainuser no)
    (prop_is_group id_codomainuser no)
    (prop_is_group id_csdomainuser no)
    (prop_is_group id_cwdomainuser no)
    (prop_is_group id_dadomainuser no)
    (prop_is_group id_dedomainuser no)
    (prop_is_group id_didomainuser no)
    (prop_is_group id_dmdomainuser no)
    (prop_is_group id_dqdomainuser no)
    (prop_is_group id_dudomainuser no)
    (prop_is_group id_dydomainuser no)
    (prop_is_group id_ecdomainuser no)
    (prop_is_group id_egdomainuser no)
    (prop_is_group id_ekdomainuser no)
    (prop_is_group id_eodomainuser no)
    (prop_is_group id_esdomainuser no)
    (prop_is_group id_ewdomainuser no)
    (prop_is_group id_fadomainuser no)
    (prop_is_group id_fedomainuser no)
    (prop_is_group id_fidomainuser no)
    (prop_is_group id_fmdomainuser no)
    (prop_is_group id_fqdomainuser no)
    (prop_is_group id_fudomainuser no)
    (prop_is_group id_fydomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_gcdomainuser no)
    (prop_is_group id_ggdomainuser no)
    (prop_is_group id_gkdomainuser no)
    (prop_is_group id_godomainuser no)
    (prop_is_group id_gsdomainuser no)
    (prop_is_group id_gwdomainuser no)
    (prop_is_group id_hadomainuser no)
    (prop_is_group id_hedomainuser no)
    (prop_is_group id_hidomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_hntimedelta num__196)
    (prop_microseconds id_hutimedelta num__203)
    (prop_microseconds id_ibtimedelta num__210)
    (prop_microseconds id_iitimedelta num__217)
    (prop_microseconds id_iptimedelta num__224)
    (prop_microseconds id_iwtimedelta num__231)
    (prop_microseconds id_jdtimedelta num__238)
    (prop_microseconds id_jktimedelta num__245)
    (prop_password id_bbdomaincredential str__bc)
    (prop_password id_bfdomaincredential str__bg)
    (prop_password id_bjdomaincredential str__bk)
    (prop_password id_bndomaincredential str__bo)
    (prop_password id_brdomaincredential str__bs)
    (prop_password id_bvdomaincredential str__bw)
    (prop_password id_bzdomaincredential str__ca)
    (prop_password id_cddomaincredential str__ce)
    (prop_password id_chdomaincredential str__ci)
    (prop_password id_cldomaincredential str__cm)
    (prop_password id_cpdomaincredential str__cq)
    (prop_password id_ctdomaincredential str__cu)
    (prop_password id_cxdomaincredential str__cy)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_dbdomaincredential str__dc)
    (prop_password id_dfdomaincredential str__dg)
    (prop_password id_djdomaincredential str__dk)
    (prop_password id_dndomaincredential str__do)
    (prop_password id_drdomaincredential str__ds)
    (prop_password id_dvdomaincredential str__dw)
    (prop_password id_dzdomaincredential str__ea)
    (prop_password id_eddomaincredential str__ee)
    (prop_password id_ehdomaincredential str__ei)
    (prop_password id_eldomaincredential str__em)
    (prop_password id_epdomaincredential str__eq)
    (prop_password id_etdomaincredential str__eu)
    (prop_password id_exdomaincredential str__ey)
    (prop_password id_fbdomaincredential str__fc)
    (prop_password id_ffdomaincredential str__fg)
    (prop_password id_fjdomaincredential str__fk)
    (prop_password id_fndomaincredential str__fo)
    (prop_password id_frdomaincredential str__fs)
    (prop_password id_fvdomaincredential str__fw)
    (prop_password id_fzdomaincredential str__ga)
    (prop_password id_gddomaincredential str__ge)
    (prop_password id_ghdomaincredential str__gi)
    (prop_password id_gldomaincredential str__gm)
    (prop_password id_gpdomaincredential str__gq)
    (prop_password id_gtdomaincredential str__gu)
    (prop_password id_gxdomaincredential str__gy)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_hbdomaincredential str__hc)
    (prop_password id_hfdomaincredential str__hg)
    (prop_password id_hjdomaincredential str__hk)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_hntimedelta num__197)
    (prop_seconds id_hutimedelta num__204)
    (prop_seconds id_ibtimedelta num__211)
    (prop_seconds id_iitimedelta num__218)
    (prop_seconds id_iptimedelta num__225)
    (prop_seconds id_iwtimedelta num__232)
    (prop_seconds id_jdtimedelta num__239)
    (prop_seconds id_jktimedelta num__246)
    (prop_sid id_badomainuser str__bd)
    (prop_sid id_bedomainuser str__bh)
    (prop_sid id_bidomainuser str__bl)
    (prop_sid id_bmdomainuser str__bp)
    (prop_sid id_bqdomainuser str__bt)
    (prop_sid id_budomainuser str__bx)
    (prop_sid id_bydomainuser str__cb)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_ccdomainuser str__cf)
    (prop_sid id_cgdomainuser str__cj)
    (prop_sid id_ckdomainuser str__cn)
    (prop_sid id_codomainuser str__cr)
    (prop_sid id_csdomainuser str__cv)
    (prop_sid id_cwdomainuser str__cz)
    (prop_sid id_dadomainuser str__dd)
    (prop_sid id_dedomainuser str__dh)
    (prop_sid id_didomainuser str__dl)
    (prop_sid id_dmdomainuser str__dp)
    (prop_sid id_dqdomainuser str__dt)
    (prop_sid id_dudomainuser str__dx)
    (prop_sid id_dydomainuser str__eb)
    (prop_sid id_ecdomainuser str__ef)
    (prop_sid id_egdomainuser str__ej)
    (prop_sid id_ekdomainuser str__en)
    (prop_sid id_eodomainuser str__er)
    (prop_sid id_esdomainuser str__ev)
    (prop_sid id_ewdomainuser str__ez)
    (prop_sid id_fadomainuser str__fd)
    (prop_sid id_fedomainuser str__fh)
    (prop_sid id_fidomainuser str__fl)
    (prop_sid id_fmdomainuser str__fp)
    (prop_sid id_fqdomainuser str__ft)
    (prop_sid id_fudomainuser str__fx)
    (prop_sid id_fydomainuser str__gb)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_gcdomainuser str__gf)
    (prop_sid id_ggdomainuser str__gj)
    (prop_sid id_gkdomainuser str__gn)
    (prop_sid id_godomainuser str__gr)
    (prop_sid id_gsdomainuser str__gv)
    (prop_sid id_gwdomainuser str__gz)
    (prop_sid id_hadomainuser str__hd)
    (prop_sid id_hedomainuser str__hh)
    (prop_sid id_hidomainuser str__hl)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_hmhost id_hntimedelta)
    (prop_timedelta id_hthost id_hutimedelta)
    (prop_timedelta id_iahost id_ibtimedelta)
    (prop_timedelta id_ihhost id_iitimedelta)
    (prop_timedelta id_iohost id_iptimedelta)
    (prop_timedelta id_ivhost id_iwtimedelta)
    (prop_timedelta id_jchost id_jdtimedelta)
    (prop_timedelta id_jjhost id_jktimedelta)
    (prop_user id_bbdomaincredential id_badomainuser)
    (prop_user id_bfdomaincredential id_bedomainuser)
    (prop_user id_bjdomaincredential id_bidomainuser)
    (prop_user id_bndomaincredential id_bmdomainuser)
    (prop_user id_brdomaincredential id_bqdomainuser)
    (prop_user id_bvdomaincredential id_budomainuser)
    (prop_user id_bzdomaincredential id_bydomainuser)
    (prop_user id_cddomaincredential id_ccdomainuser)
    (prop_user id_chdomaincredential id_cgdomainuser)
    (prop_user id_cldomaincredential id_ckdomainuser)
    (prop_user id_cpdomaincredential id_codomainuser)
    (prop_user id_ctdomaincredential id_csdomainuser)
    (prop_user id_cxdomaincredential id_cwdomainuser)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_dbdomaincredential id_dadomainuser)
    (prop_user id_dfdomaincredential id_dedomainuser)
    (prop_user id_djdomaincredential id_didomainuser)
    (prop_user id_dndomaincredential id_dmdomainuser)
    (prop_user id_drdomaincredential id_dqdomainuser)
    (prop_user id_dvdomaincredential id_dudomainuser)
    (prop_user id_dzdomaincredential id_dydomainuser)
    (prop_user id_eddomaincredential id_ecdomainuser)
    (prop_user id_ehdomaincredential id_egdomainuser)
    (prop_user id_eldomaincredential id_ekdomainuser)
    (prop_user id_epdomaincredential id_eodomainuser)
    (prop_user id_etdomaincredential id_esdomainuser)
    (prop_user id_exdomaincredential id_ewdomainuser)
    (prop_user id_fbdomaincredential id_fadomainuser)
    (prop_user id_ffdomaincredential id_fedomainuser)
    (prop_user id_fjdomaincredential id_fidomainuser)
    (prop_user id_fndomaincredential id_fmdomainuser)
    (prop_user id_frdomaincredential id_fqdomainuser)
    (prop_user id_fvdomaincredential id_fudomainuser)
    (prop_user id_fzdomaincredential id_fydomainuser)
    (prop_user id_gddomaincredential id_gcdomainuser)
    (prop_user id_ghdomaincredential id_ggdomainuser)
    (prop_user id_gldomaincredential id_gkdomainuser)
    (prop_user id_gpdomaincredential id_godomainuser)
    (prop_user id_gtdomaincredential id_gsdomainuser)
    (prop_user id_gxdomaincredential id_gwdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_hbdomaincredential id_hadomainuser)
    (prop_user id_hfdomaincredential id_hedomainuser)
    (prop_user id_hjdomaincredential id_hidomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_badomainuser str__michael)
    (prop_username id_bedomainuser str__barbara)
    (prop_username id_bidomainuser str__william)
    (prop_username id_bmdomainuser str__elizabeth)
    (prop_username id_bqdomainuser str__david)
    (prop_username id_budomainuser str__jennifer)
    (prop_username id_bydomainuser str__richard)
    (prop_username id_cdomainuser str__james)
    (prop_username id_ccdomainuser str__maria)
    (prop_username id_cgdomainuser str__charles)
    (prop_username id_ckdomainuser str__susan)
    (prop_username id_codomainuser str__joseph)
    (prop_username id_csdomainuser str__margaret)
    (prop_username id_cwdomainuser str__thomas)
    (prop_username id_dadomainuser str__dorothy)
    (prop_username id_dedomainuser str__christopher)
    (prop_username id_didomainuser str__lisa)
    (prop_username id_dmdomainuser str__daniel)
    (prop_username id_dqdomainuser str__nancy)
    (prop_username id_dudomainuser str__paul)
    (prop_username id_dydomainuser str__karen)
    (prop_username id_ecdomainuser str__mark)
    (prop_username id_egdomainuser str__betty)
    (prop_username id_ekdomainuser str__donald)
    (prop_username id_eodomainuser str__helen)
    (prop_username id_esdomainuser str__george)
    (prop_username id_ewdomainuser str__sandra)
    (prop_username id_fadomainuser str__kenneth)
    (prop_username id_fedomainuser str__donna)
    (prop_username id_fidomainuser str__steven)
    (prop_username id_fmdomainuser str__carol)
    (prop_username id_fqdomainuser str__edward)
    (prop_username id_fudomainuser str__ruth)
    (prop_username id_fydomainuser str__brian)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_gcdomainuser str__sharon)
    (prop_username id_ggdomainuser str__ronald)
    (prop_username id_gkdomainuser str__michelle)
    (prop_username id_godomainuser str__anthony)
    (prop_username id_gsdomainuser str__laura)
    (prop_username id_gwdomainuser str__kevin)
    (prop_username id_hadomainuser str__sarah)
    (prop_username id_hedomainuser str__jason)
    (prop_username id_hidomainuser str__kimberly)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_jtrat id_iohost)
    (prop_host id_jwrat id_ihhost)
    (prop_host id_jurat id_ivhost)
    (prop_host id_jsrat id_jchost)
    (prop_host id_jvrat id_jjhost)
    (prop_host id_jxrat id_iahost)
    (prop_host id_jzrat id_hmhost)
)
)
(:metric minimize (total-cost))
)