(define (problem p9_hosts_trial_3)
(:domain caldera-split)
(:objects
    id_dzrat - observedrat
    id_earat - observedrat
    id_ebrat - observedrat
    id_dxrat - observedrat
    id_ddrat - observedrat
    id_eerat - observedrat
    id_efrat - observedrat
    id_ecrat - observedrat
    id_edrat - observedrat
    id_dyrat - observedrat
    id_dkschtask - observedschtask
    id_dischtask - observedschtask
    id_dmschtask - observedschtask
    id_dnschtask - observedschtask
    id_dhschtask - observedschtask
    id_dgschtask - observedschtask
    id_djschtask - observedschtask
    id_dlschtask - observedschtask
    id_dfschtask - observedschtask
    num__76 - num
    num__34 - num
    num__55 - num
    num__69 - num
    num__42 - num
    num__27 - num
    num__70 - num
    num__77 - num
    num__62 - num
    num__56 - num
    num__21 - num
    num__41 - num
    num__63 - num
    num__48 - num
    num__28 - num
    num__20 - num
    num__35 - num
    num__49 - num
    id_adomain - observeddomain
    str__db - string
    str__j - string
    str__n - string
    str__bs - string
    str__x - string
    str__e - string
    str__co - string
    str__by - string
    str__bz - string
    str__john - string
    str__bt - string
    str__dc - string
    str__be - string
    str__bd - string
    str__q - string
    str__mary - string
    str__ca - string
    str__da - string
    str__bm - string
    str__cm - string
    str__bf - string
    str__b - string
    str__alpha - string
    str__cn - string
    str__cu - string
    str__patricia - string
    str__cg - string
    str__r - string
    str__ch - string
    str__ct - string
    str__w - string
    str__bl - string
    str__bk - string
    str__f - string
    str__cf - string
    str__cv - string
    str__james - string
    str__i - string
    str__m - string
    str__y - string
    str__de - string
    str__br - string
    id_pdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_drfile - observedfile
    id_dpfile - observedfile
    id_dvfile - observedfile
    id_dqfile - observedfile
    id_dtfile - observedfile
    id_dofile - observedfile
    id_dufile - observedfile
    id_dsfile - observedfile
    id_dwfile - observedfile
    id_shost - observedhost
    id_cbhost - observedhost
    id_cihost - observedhost
    id_bnhost - observedhost
    id_bghost - observedhost
    id_cphost - observedhost
    id_buhost - observedhost
    id_cwhost - observedhost
    id_zhost - observedhost
    id_emshare - observedshare
    id_ejshare - observedshare
    id_elshare - observedshare
    id_eishare - observedshare
    id_egshare - observedshare
    id_ehshare - observedshare
    id_eoshare - observedshare
    id_ekshare - observedshare
    id_enshare - observedshare
    id_gdomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_cqtimedelta - observedtimedelta
    id_cxtimedelta - observedtimedelta
    id_cctimedelta - observedtimedelta
    id_bhtimedelta - observedtimedelta
    id_bvtimedelta - observedtimedelta
    id_ttimedelta - observedtimedelta
    id_cjtimedelta - observedtimedelta
    id_botimedelta - observedtimedelta
    id_batimedelta - observedtimedelta
)
(:init
    (knows id_ddrat)
    (knows id_zhost)
    (knows_property id_ddrat pexecutable)
    (knows_property id_ddrat phost)
    (knows_property id_zhost pfqdn)
    (mem_cached_domain_creds id_bghost id_ddomaincredential)
    (mem_cached_domain_creds id_bghost id_hdomaincredential)
    (mem_cached_domain_creds id_bnhost id_hdomaincredential)
    (mem_cached_domain_creds id_bnhost id_pdomaincredential)
    (mem_cached_domain_creds id_buhost id_ddomaincredential)
    (mem_cached_domain_creds id_buhost id_ldomaincredential)
    (mem_cached_domain_creds id_cbhost id_ddomaincredential)
    (mem_cached_domain_creds id_cbhost id_hdomaincredential)
    (mem_cached_domain_creds id_cihost id_ddomaincredential)
    (mem_cached_domain_creds id_cihost id_ldomaincredential)
    (mem_cached_domain_creds id_cphost id_hdomaincredential)
    (mem_cached_domain_creds id_cphost id_pdomaincredential)
    (mem_cached_domain_creds id_cwhost id_ddomaincredential)
    (mem_cached_domain_creds id_cwhost id_pdomaincredential)
    (mem_cached_domain_creds id_shost id_ldomaincredential)
    (mem_cached_domain_creds id_shost id_pdomaincredential)
    (mem_cached_domain_creds id_zhost id_hdomaincredential)
    (mem_cached_domain_creds id_zhost id_ldomaincredential)
    (mem_domain_user_admins id_bghost id_gdomainuser)
    (mem_domain_user_admins id_bghost id_odomainuser)
    (mem_domain_user_admins id_bnhost id_gdomainuser)
    (mem_domain_user_admins id_bnhost id_kdomainuser)
    (mem_domain_user_admins id_buhost id_gdomainuser)
    (mem_domain_user_admins id_buhost id_odomainuser)
    (mem_domain_user_admins id_cbhost id_kdomainuser)
    (mem_domain_user_admins id_cbhost id_odomainuser)
    (mem_domain_user_admins id_cihost id_cdomainuser)
    (mem_domain_user_admins id_cihost id_odomainuser)
    (mem_domain_user_admins id_cphost id_cdomainuser)
    (mem_domain_user_admins id_cphost id_gdomainuser)
    (mem_domain_user_admins id_cwhost id_cdomainuser)
    (mem_domain_user_admins id_cwhost id_odomainuser)
    (mem_domain_user_admins id_shost id_cdomainuser)
    (mem_domain_user_admins id_shost id_gdomainuser)
    (mem_domain_user_admins id_zhost id_cdomainuser)
    (mem_domain_user_admins id_zhost id_kdomainuser)
    (mem_hosts id_adomain id_bghost)
    (mem_hosts id_adomain id_bnhost)
    (mem_hosts id_adomain id_buhost)
    (mem_hosts id_adomain id_cbhost)
    (mem_hosts id_adomain id_cihost)
    (mem_hosts id_adomain id_cphost)
    (mem_hosts id_adomain id_cwhost)
    (mem_hosts id_adomain id_shost)
    (mem_hosts id_adomain id_zhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_dc id_bghost yes)
    (prop_dc id_bnhost no)
    (prop_dc id_buhost no)
    (prop_dc id_cbhost no)
    (prop_dc id_cihost no)
    (prop_dc id_cphost yes)
    (prop_dc id_cwhost no)
    (prop_dc id_shost no)
    (prop_dc id_zhost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_bghost str__bk)
    (prop_dns_domain_name id_bnhost str__br)
    (prop_dns_domain_name id_buhost str__by)
    (prop_dns_domain_name id_cbhost str__cf)
    (prop_dns_domain_name id_cihost str__cm)
    (prop_dns_domain_name id_cphost str__ct)
    (prop_dns_domain_name id_cwhost str__da)
    (prop_dns_domain_name id_shost str__w)
    (prop_dns_domain_name id_zhost str__bd)
    (prop_domain id_bghost id_adomain)
    (prop_domain id_bnhost id_adomain)
    (prop_domain id_buhost id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_cbhost id_adomain)
    (prop_domain id_cihost id_adomain)
    (prop_domain id_cphost id_adomain)
    (prop_domain id_cwhost id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_shost id_adomain)
    (prop_domain id_zhost id_adomain)
    (prop_elevated id_ddrat yes)
    (prop_executable id_ddrat str__de)
    (prop_fqdn id_bghost str__bm)
    (prop_fqdn id_bnhost str__bt)
    (prop_fqdn id_buhost str__ca)
    (prop_fqdn id_cbhost str__ch)
    (prop_fqdn id_cihost str__co)
    (prop_fqdn id_cphost str__cv)
    (prop_fqdn id_cwhost str__dc)
    (prop_fqdn id_shost str__y)
    (prop_fqdn id_zhost str__bf)
    (prop_host id_batimedelta id_zhost)
    (prop_host id_bhtimedelta id_bghost)
    (prop_host id_botimedelta id_bnhost)
    (prop_host id_bvtimedelta id_buhost)
    (prop_host id_cctimedelta id_cbhost)
    (prop_host id_cjtimedelta id_cihost)
    (prop_host id_cqtimedelta id_cphost)
    (prop_host id_cxtimedelta id_cwhost)
    (prop_host id_ddrat id_zhost)
    (prop_host id_ttimedelta id_shost)
    (prop_hostname id_bghost str__bl)
    (prop_hostname id_bnhost str__bs)
    (prop_hostname id_buhost str__bz)
    (prop_hostname id_cbhost str__cg)
    (prop_hostname id_cihost str__cn)
    (prop_hostname id_cphost str__cu)
    (prop_hostname id_cwhost str__db)
    (prop_hostname id_shost str__x)
    (prop_hostname id_zhost str__be)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_microseconds id_batimedelta num__28)
    (prop_microseconds id_bhtimedelta num__35)
    (prop_microseconds id_botimedelta num__42)
    (prop_microseconds id_bvtimedelta num__49)
    (prop_microseconds id_cctimedelta num__56)
    (prop_microseconds id_cjtimedelta num__63)
    (prop_microseconds id_cqtimedelta num__70)
    (prop_microseconds id_cxtimedelta num__77)
    (prop_microseconds id_ttimedelta num__21)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_seconds id_batimedelta num__27)
    (prop_seconds id_bhtimedelta num__34)
    (prop_seconds id_botimedelta num__41)
    (prop_seconds id_bvtimedelta num__48)
    (prop_seconds id_cctimedelta num__55)
    (prop_seconds id_cjtimedelta num__62)
    (prop_seconds id_cqtimedelta num__69)
    (prop_seconds id_cxtimedelta num__76)
    (prop_seconds id_ttimedelta num__20)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_timedelta id_bghost id_bhtimedelta)
    (prop_timedelta id_bnhost id_botimedelta)
    (prop_timedelta id_buhost id_bvtimedelta)
    (prop_timedelta id_cbhost id_cctimedelta)
    (prop_timedelta id_cihost id_cjtimedelta)
    (prop_timedelta id_cphost id_cqtimedelta)
    (prop_timedelta id_cwhost id_cxtimedelta)
    (prop_timedelta id_shost id_ttimedelta)
    (prop_timedelta id_zhost id_batimedelta)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_username id_cdomainuser str__james)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_ecrat id_buhost)
    (prop_host id_efrat id_cphost)
    (prop_host id_eerat id_bghost)
    (prop_host id_dxrat id_bnhost)
    (prop_host id_ebrat id_cihost)
    (prop_host id_earat id_cbhost)
    (prop_host id_dzrat id_shost)
    (prop_host id_dyrat id_cwhost)
)
)
(:metric minimize (total-cost))
)