(define (problem p10_hosts_trial_9)
(:domain caldera-split)
(:objects
    id_fmrat - observedrat
    id_fnrat - observedrat
    id_fjrat - observedrat
    id_firat - observedrat
    id_fqrat - observedrat
    id_frrat - observedrat
    id_forat - observedrat
    id_fgrat - observedrat
    id_fkrat - observedrat
    id_flrat - observedrat
    id_fprat - observedrat
    str__r - string
    str__dw - string
    str__dv - string
    str__du - string
    str__q - string
    str__db - string
    str__da - string
    str__ey - string
    str__james - string
    str__robert - string
    str__michael - string
    str__bp - string
    str__ec - string
    str__cs - string
    str__cn - string
    str__ex - string
    str__dn - string
    str__bd - string
    str__susan - string
    str__bw - string
    str__ej - string
    str__fe - string
    str__m - string
    str__e - string
    str__i - string
    str__dp - string
    str__ff - string
    str__cm - string
    str__ew - string
    str__ca - string
    str__eq - string
    str__ce - string
    str__john - string
    str__cf - string
    str__y - string
    str__maria - string
    str__cz - string
    str__dg - string
    str__elizabeth - string
    str__ed - string
    str__cb - string
    str__barbara - string
    str__alpha - string
    str__do - string
    str__b - string
    str__bt - string
    str__jennifer - string
    str__bh - string
    str__cu - string
    str__bs - string
    str__charles - string
    str__u - string
    str__di - string
    str__william - string
    str__ct - string
    str__n - string
    str__linda - string
    str__ek - string
    str__fh - string
    str__ep - string
    str__f - string
    str__z - string
    str__richard - string
    str__dh - string
    str__bx - string
    str__bc - string
    str__cj - string
    str__bg - string
    str__david - string
    str__ei - string
    str__j - string
    str__bl - string
    str__patricia - string
    str__er - string
    str__eb - string
    str__v - string
    str__bo - string
    str__ci - string
    str__fd - string
    str__bk - string
    str__mary - string
    num__69 - num
    num__76 - num
    num__125 - num
    num__104 - num
    num__83 - num
    num__132 - num
    num__97 - num
    num__117 - num
    num__75 - num
    num__82 - num
    num__68 - num
    num__89 - num
    num__131 - num
    num__103 - num
    num__96 - num
    num__111 - num
    num__118 - num
    num__110 - num
    num__90 - num
    num__124 - num
    id_gifile - observedfile
    id_ghfile - observedfile
    id_gjfile - observedfile
    id_gkfile - observedfile
    id_gcfile - observedfile
    id_gdfile - observedfile
    id_ggfile - observedfile
    id_glfile - observedfile
    id_gefile - observedfile
    id_gffile - observedfile
    id_cptimedelta - observedtimedelta
    id_eftimedelta - observedtimedelta
    id_dytimedelta - observedtimedelta
    id_ddtimedelta - observedtimedelta
    id_ettimedelta - observedtimedelta
    id_dktimedelta - observedtimedelta
    id_drtimedelta - observedtimedelta
    id_fatimedelta - observedtimedelta
    id_emtimedelta - observedtimedelta
    id_cwtimedelta - observedtimedelta
    id_ddomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_cddomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_cldomaincredential - observeddomaincredential
    id_brdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_bvdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_chdomaincredential - observeddomaincredential
    id_dxhost - observedhost
    id_eshost - observedhost
    id_ezhost - observedhost
    id_cvhost - observedhost
    id_dqhost - observedhost
    id_dchost - observedhost
    id_elhost - observedhost
    id_cohost - observedhost
    id_eehost - observedhost
    id_djhost - observedhost
    id_gdomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_cgdomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_ckdomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_fwshare - observedshare
    id_fxshare - observedshare
    id_ftshare - observedshare
    id_gbshare - observedshare
    id_fvshare - observedshare
    id_fzshare - observedshare
    id_gashare - observedshare
    id_fsshare - observedshare
    id_fushare - observedshare
    id_fyshare - observedshare
    id_adomain - observeddomain
    id_gtschtask - observedschtask
    id_gmschtask - observedschtask
    id_gqschtask - observedschtask
    id_guschtask - observedschtask
    id_gvschtask - observedschtask
    id_grschtask - observedschtask
    id_goschtask - observedschtask
    id_gsschtask - observedschtask
    id_gpschtask - observedschtask
    id_gnschtask - observedschtask
)
(:init
    (knows id_eehost)
    (knows id_fgrat)
    (knows_property id_eehost pfqdn)
    (knows_property id_fgrat pexecutable)
    (knows_property id_fgrat phost)
    (mem_cached_domain_creds id_cohost id_cddomaincredential)
    (mem_cached_domain_creds id_cohost id_ddomaincredential)
    (mem_cached_domain_creds id_cohost id_pdomaincredential)
    (mem_cached_domain_creds id_cvhost id_bjdomaincredential)
    (mem_cached_domain_creds id_cvhost id_brdomaincredential)
    (mem_cached_domain_creds id_cvhost id_chdomaincredential)
    (mem_cached_domain_creds id_dchost id_brdomaincredential)
    (mem_cached_domain_creds id_dchost id_cddomaincredential)
    (mem_cached_domain_creds id_dchost id_ldomaincredential)
    (mem_cached_domain_creds id_djhost id_brdomaincredential)
    (mem_cached_domain_creds id_djhost id_cddomaincredential)
    (mem_cached_domain_creds id_djhost id_pdomaincredential)
    (mem_cached_domain_creds id_dqhost id_bvdomaincredential)
    (mem_cached_domain_creds id_dqhost id_cldomaincredential)
    (mem_cached_domain_creds id_dqhost id_hdomaincredential)
    (mem_cached_domain_creds id_dxhost id_bzdomaincredential)
    (mem_cached_domain_creds id_dxhost id_cldomaincredential)
    (mem_cached_domain_creds id_dxhost id_tdomaincredential)
    (mem_cached_domain_creds id_eehost id_cddomaincredential)
    (mem_cached_domain_creds id_eehost id_chdomaincredential)
    (mem_cached_domain_creds id_eehost id_hdomaincredential)
    (mem_cached_domain_creds id_elhost id_bfdomaincredential)
    (mem_cached_domain_creds id_elhost id_brdomaincredential)
    (mem_cached_domain_creds id_elhost id_bzdomaincredential)
    (mem_cached_domain_creds id_eshost id_hdomaincredential)
    (mem_cached_domain_creds id_eshost id_ldomaincredential)
    (mem_cached_domain_creds id_eshost id_xdomaincredential)
    (mem_cached_domain_creds id_ezhost id_bbdomaincredential)
    (mem_cached_domain_creds id_ezhost id_bzdomaincredential)
    (mem_cached_domain_creds id_ezhost id_tdomaincredential)
    (mem_domain_user_admins id_cohost id_badomainuser)
    (mem_domain_user_admins id_cvhost id_bydomainuser)
    (mem_domain_user_admins id_dchost id_ccdomainuser)
    (mem_domain_user_admins id_djhost id_odomainuser)
    (mem_domain_user_admins id_dqhost id_cdomainuser)
    (mem_domain_user_admins id_dxhost id_bqdomainuser)
    (mem_domain_user_admins id_eehost id_bidomainuser)
    (mem_domain_user_admins id_elhost id_sdomainuser)
    (mem_domain_user_admins id_eshost id_bidomainuser)
    (mem_domain_user_admins id_ezhost id_bqdomainuser)
    (mem_hosts id_adomain id_cohost)
    (mem_hosts id_adomain id_cvhost)
    (mem_hosts id_adomain id_dchost)
    (mem_hosts id_adomain id_djhost)
    (mem_hosts id_adomain id_dqhost)
    (mem_hosts id_adomain id_dxhost)
    (mem_hosts id_adomain id_eehost)
    (mem_hosts id_adomain id_elhost)
    (mem_hosts id_adomain id_eshost)
    (mem_hosts id_adomain id_ezhost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_cgdomainuser id_chdomaincredential)
    (prop_cred id_ckdomainuser id_cldomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_cohost no)
    (prop_dc id_cvhost no)
    (prop_dc id_dchost no)
    (prop_dc id_djhost yes)
    (prop_dc id_dqhost no)
    (prop_dc id_dxhost no)
    (prop_dc id_eehost no)
    (prop_dc id_elhost no)
    (prop_dc id_eshost no)
    (prop_dc id_ezhost yes)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_cohost str__cs)
    (prop_dns_domain_name id_cvhost str__cz)
    (prop_dns_domain_name id_dchost str__dg)
    (prop_dns_domain_name id_djhost str__dn)
    (prop_dns_domain_name id_dqhost str__du)
    (prop_dns_domain_name id_dxhost str__eb)
    (prop_dns_domain_name id_eehost str__ei)
    (prop_dns_domain_name id_elhost str__ep)
    (prop_dns_domain_name id_eshost str__ew)
    (prop_dns_domain_name id_ezhost str__fd)
    (prop_domain id_badomainuser id_adomain)
    (prop_domain id_bbdomaincredential id_adomain)
    (prop_domain id_bedomainuser id_adomain)
    (prop_domain id_bfdomaincredential id_adomain)
    (prop_domain id_bidomainuser id_adomain)
    (prop_domain id_bjdomaincredential id_adomain)
    (prop_domain id_bmdomainuser id_adomain)
    (prop_domain id_bndomaincredential id_adomain)
    (prop_domain id_bqdomainuser id_adomain)
    (prop_domain id_brdomaincredential id_adomain)
    (prop_domain id_budomainuser id_adomain)
    (prop_domain id_bvdomaincredential id_adomain)
    (prop_domain id_bydomainuser id_adomain)
    (prop_domain id_bzdomaincredential id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ccdomainuser id_adomain)
    (prop_domain id_cddomaincredential id_adomain)
    (prop_domain id_cgdomainuser id_adomain)
    (prop_domain id_chdomaincredential id_adomain)
    (prop_domain id_ckdomainuser id_adomain)
    (prop_domain id_cldomaincredential id_adomain)
    (prop_domain id_cohost id_adomain)
    (prop_domain id_cvhost id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_dchost id_adomain)
    (prop_domain id_djhost id_adomain)
    (prop_domain id_dqhost id_adomain)
    (prop_domain id_dxhost id_adomain)
    (prop_domain id_eehost id_adomain)
    (prop_domain id_elhost id_adomain)
    (prop_domain id_eshost id_adomain)
    (prop_domain id_ezhost id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_fgrat yes)
    (prop_executable id_fgrat str__fh)
    (prop_fqdn id_cohost str__cu)
    (prop_fqdn id_cvhost str__db)
    (prop_fqdn id_dchost str__di)
    (prop_fqdn id_djhost str__dp)
    (prop_fqdn id_dqhost str__dw)
    (prop_fqdn id_dxhost str__ed)
    (prop_fqdn id_eehost str__ek)
    (prop_fqdn id_elhost str__er)
    (prop_fqdn id_eshost str__ey)
    (prop_fqdn id_ezhost str__ff)
    (prop_host id_cptimedelta id_cohost)
    (prop_host id_cwtimedelta id_cvhost)
    (prop_host id_ddtimedelta id_dchost)
    (prop_host id_dktimedelta id_djhost)
    (prop_host id_drtimedelta id_dqhost)
    (prop_host id_dytimedelta id_dxhost)
    (prop_host id_eftimedelta id_eehost)
    (prop_host id_emtimedelta id_elhost)
    (prop_host id_ettimedelta id_eshost)
    (prop_host id_fatimedelta id_ezhost)
    (prop_host id_fgrat id_eehost)
    (prop_hostname id_cohost str__ct)
    (prop_hostname id_cvhost str__da)
    (prop_hostname id_dchost str__dh)
    (prop_hostname id_djhost str__do)
    (prop_hostname id_dqhost str__dv)
    (prop_hostname id_dxhost str__ec)
    (prop_hostname id_eehost str__ej)
    (prop_hostname id_elhost str__eq)
    (prop_hostname id_eshost str__ex)
    (prop_hostname id_ezhost str__fe)
    (prop_is_group id_badomainuser no)
    (prop_is_group id_bedomainuser no)
    (prop_is_group id_bidomainuser no)
    (prop_is_group id_bmdomainuser no)
    (prop_is_group id_bqdomainuser no)
    (prop_is_group id_budomainuser no)
    (prop_is_group id_bydomainuser no)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_ccdomainuser no)
    (prop_is_group id_cgdomainuser no)
    (prop_is_group id_ckdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_cptimedelta num__68)
    (prop_microseconds id_cwtimedelta num__75)
    (prop_microseconds id_ddtimedelta num__82)
    (prop_microseconds id_dktimedelta num__89)
    (prop_microseconds id_drtimedelta num__96)
    (prop_microseconds id_dytimedelta num__103)
    (prop_microseconds id_eftimedelta num__110)
    (prop_microseconds id_emtimedelta num__117)
    (prop_microseconds id_ettimedelta num__124)
    (prop_microseconds id_fatimedelta num__131)
    (prop_password id_bbdomaincredential str__bc)
    (prop_password id_bfdomaincredential str__bg)
    (prop_password id_bjdomaincredential str__bk)
    (prop_password id_bndomaincredential str__bo)
    (prop_password id_brdomaincredential str__bs)
    (prop_password id_bvdomaincredential str__bw)
    (prop_password id_bzdomaincredential str__ca)
    (prop_password id_cddomaincredential str__ce)
    (prop_password id_chdomaincredential str__ci)
    (prop_password id_cldomaincredential str__cm)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_cptimedelta num__69)
    (prop_seconds id_cwtimedelta num__76)
    (prop_seconds id_ddtimedelta num__83)
    (prop_seconds id_dktimedelta num__90)
    (prop_seconds id_drtimedelta num__97)
    (prop_seconds id_dytimedelta num__104)
    (prop_seconds id_eftimedelta num__111)
    (prop_seconds id_emtimedelta num__118)
    (prop_seconds id_ettimedelta num__125)
    (prop_seconds id_fatimedelta num__132)
    (prop_sid id_badomainuser str__bd)
    (prop_sid id_bedomainuser str__bh)
    (prop_sid id_bidomainuser str__bl)
    (prop_sid id_bmdomainuser str__bp)
    (prop_sid id_bqdomainuser str__bt)
    (prop_sid id_budomainuser str__bx)
    (prop_sid id_bydomainuser str__cb)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_ccdomainuser str__cf)
    (prop_sid id_cgdomainuser str__cj)
    (prop_sid id_ckdomainuser str__cn)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_cohost id_cptimedelta)
    (prop_timedelta id_cvhost id_cwtimedelta)
    (prop_timedelta id_dchost id_ddtimedelta)
    (prop_timedelta id_djhost id_dktimedelta)
    (prop_timedelta id_dqhost id_drtimedelta)
    (prop_timedelta id_dxhost id_dytimedelta)
    (prop_timedelta id_eehost id_eftimedelta)
    (prop_timedelta id_elhost id_emtimedelta)
    (prop_timedelta id_eshost id_ettimedelta)
    (prop_timedelta id_ezhost id_fatimedelta)
    (prop_user id_bbdomaincredential id_badomainuser)
    (prop_user id_bfdomaincredential id_bedomainuser)
    (prop_user id_bjdomaincredential id_bidomainuser)
    (prop_user id_bndomaincredential id_bmdomainuser)
    (prop_user id_brdomaincredential id_bqdomainuser)
    (prop_user id_bvdomaincredential id_budomainuser)
    (prop_user id_bzdomaincredential id_bydomainuser)
    (prop_user id_cddomaincredential id_ccdomainuser)
    (prop_user id_chdomaincredential id_cgdomainuser)
    (prop_user id_cldomaincredential id_ckdomainuser)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_badomainuser str__michael)
    (prop_username id_bedomainuser str__barbara)
    (prop_username id_bidomainuser str__william)
    (prop_username id_bmdomainuser str__elizabeth)
    (prop_username id_bqdomainuser str__david)
    (prop_username id_budomainuser str__jennifer)
    (prop_username id_bydomainuser str__richard)
    (prop_username id_cdomainuser str__james)
    (prop_username id_ccdomainuser str__maria)
    (prop_username id_cgdomainuser str__charles)
    (prop_username id_ckdomainuser str__susan)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_fkrat id_cohost)
    (prop_host id_forat id_elhost)
    (prop_host id_frrat id_dchost)
    (prop_host id_fqrat id_dqhost)
    (prop_host id_firat id_cvhost)
    (prop_host id_fjrat id_ezhost)
    (prop_host id_fnrat id_eshost)
    (prop_host id_fmrat id_dxhost)
    (prop_host id_fprat id_djhost)
)
)
(:metric minimize (total-cost))
)