(define (problem p12_hosts_trial_14)
(:domain caldera-split)
(:objects
    id_cwdomainuser - observeddomainuser
    id_dmdomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_ckdomainuser - observeddomainuser
    id_codomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_dqdomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_dadomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_csdomainuser - observeddomainuser
    id_cgdomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_dedomainuser - observeddomainuser
    id_didomainuser - observeddomainuser
    num__115 - num
    num__101 - num
    num__114 - num
    num__121 - num
    num__136 - num
    num__128 - num
    num__129 - num
    num__156 - num
    num__107 - num
    num__163 - num
    num__108 - num
    num__157 - num
    num__122 - num
    num__150 - num
    num__164 - num
    num__135 - num
    num__171 - num
    num__142 - num
    num__143 - num
    num__170 - num
    num__100 - num
    num__178 - num
    num__149 - num
    num__177 - num
    id_frhost - observedhost
    id_fyhost - observedhost
    id_gfhost - observedhost
    id_ephost - observedhost
    id_fdhost - observedhost
    id_gmhost - observedhost
    id_duhost - observedhost
    id_ebhost - observedhost
    id_gthost - observedhost
    id_eihost - observedhost
    id_ewhost - observedhost
    id_fkhost - observedhost
    id_gntimedelta - observedtimedelta
    id_eqtimedelta - observedtimedelta
    id_ggtimedelta - observedtimedelta
    id_ectimedelta - observedtimedelta
    id_ejtimedelta - observedtimedelta
    id_fstimedelta - observedtimedelta
    id_gutimedelta - observedtimedelta
    id_dvtimedelta - observedtimedelta
    id_fztimedelta - observedtimedelta
    id_fltimedelta - observedtimedelta
    id_extimedelta - observedtimedelta
    id_fetimedelta - observedtimedelta
    id_ihshare - observedshare
    id_idshare - observedshare
    id_iishare - observedshare
    id_ieshare - observedshare
    id_ilshare - observedshare
    id_iashare - observedshare
    id_igshare - observedshare
    id_ijshare - observedshare
    id_ifshare - observedshare
    id_ikshare - observedshare
    id_ibshare - observedshare
    id_icshare - observedshare
    id_hhfile - observedfile
    id_hmfile - observedfile
    id_hkfile - observedfile
    id_hlfile - observedfile
    id_hefile - observedfile
    id_hnfile - observedfile
    id_hcfile - observedfile
    id_hdfile - observedfile
    id_hifile - observedfile
    id_hgfile - observedfile
    id_hffile - observedfile
    id_hjfile - observedfile
    str__james - string
    str__robert - string
    str__gd - string
    str__n - string
    str__lisa - string
    str__v - string
    str__cq - string
    str__em - string
    str__ea - string
    str__john - string
    str__gy - string
    str__charles - string
    str__bc - string
    str__r - string
    str__eu - string
    str__gc - string
    str__bo - string
    str__michael - string
    str__cu - string
    str__eo - string
    str__bt - string
    str__linda - string
    str__ev - string
    str__dh - string
    str__fj - string
    str__bk - string
    str__ds - string
    str__dp - string
    str__cz - string
    str__fb - string
    str__bl - string
    str__u - string
    str__gz - string
    str__cj - string
    str__cn - string
    str__david - string
    str__gs - string
    str__j - string
    str__bp - string
    str__dy - string
    str__fx - string
    str__barbara - string
    str__maria - string
    str__dorothy - string
    str__ca - string
    str__richard - string
    str__bh - string
    str__gl - string
    str__dz - string
    str__hb - string
    str__cr - string
    str__cy - string
    str__gk - string
    str__daniel - string
    str__margaret - string
    str__z - string
    str__ef - string
    str__gx - string
    str__e - string
    str__patricia - string
    str__gr - string
    str__dl - string
    str__fq - string
    str__bx - string
    str__thomas - string
    str__ci - string
    str__elizabeth - string
    str__mary - string
    str__fp - string
    str__joseph - string
    str__fo - string
    str__cm - string
    str__eg - string
    str__alpha - string
    str__fa - string
    str__b - string
    str__q - string
    str__nancy - string
    str__eh - string
    str__et - string
    str__fh - string
    str__y - string
    str__dt - string
    str__susan - string
    str__do - string
    str__fw - string
    str__f - string
    str__gj - string
    str__m - string
    str__gq - string
    str__fc - string
    str__en - string
    str__bd - string
    str__cf - string
    str__fv - string
    str__dc - string
    str__ce - string
    str__cv - string
    str__bs - string
    str__william - string
    str__jennifer - string
    str__bw - string
    str__bg - string
    str__fi - string
    str__ge - string
    str__cb - string
    str__dd - string
    str__dg - string
    str__christopher - string
    str__dk - string
    str__i - string
    id_adomain - observeddomain
    id_hsschtask - observedschtask
    id_hwschtask - observedschtask
    id_htschtask - observedschtask
    id_hqschtask - observedschtask
    id_hvschtask - observedschtask
    id_huschtask - observedschtask
    id_hrschtask - observedschtask
    id_hzschtask - observedschtask
    id_hoschtask - observedschtask
    id_hxschtask - observedschtask
    id_hpschtask - observedschtask
    id_hyschtask - observedschtask
    id_brdomaincredential - observeddomaincredential
    id_drdomaincredential - observeddomaincredential
    id_ctdomaincredential - observeddomaincredential
    id_djdomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_cxdomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_cddomaincredential - observeddomaincredential
    id_dndomaincredential - observeddomaincredential
    id_dfdomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_dbdomaincredential - observeddomaincredential
    id_chdomaincredential - observeddomaincredential
    id_cldomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_cpdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_bvdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_imrat - observedrat
    id_irrat - observedrat
    id_ivrat - observedrat
    id_itrat - observedrat
    id_iurat - observedrat
    id_iprat - observedrat
    id_ixrat - observedrat
    id_inrat - observedrat
    id_iorat - observedrat
    id_israt - observedrat
    id_iwrat - observedrat
    id_harat - observedrat
    id_iqrat - observedrat
)
(:init
    (knows id_fkhost)
    (knows id_harat)
    (knows_property id_fkhost pfqdn)
    (knows_property id_harat pexecutable)
    (knows_property id_harat phost)
    (mem_cached_domain_creds id_duhost id_brdomaincredential)
    (mem_cached_domain_creds id_duhost id_tdomaincredential)
    (mem_cached_domain_creds id_ebhost id_bbdomaincredential)
    (mem_cached_domain_creds id_ebhost id_bndomaincredential)
    (mem_cached_domain_creds id_eihost id_cxdomaincredential)
    (mem_cached_domain_creds id_eihost id_hdomaincredential)
    (mem_cached_domain_creds id_ephost id_cpdomaincredential)
    (mem_cached_domain_creds id_ephost id_ldomaincredential)
    (mem_cached_domain_creds id_ewhost id_bjdomaincredential)
    (mem_cached_domain_creds id_ewhost id_tdomaincredential)
    (mem_cached_domain_creds id_fdhost id_ctdomaincredential)
    (mem_cached_domain_creds id_fdhost id_ddomaincredential)
    (mem_cached_domain_creds id_fkhost id_bvdomaincredential)
    (mem_cached_domain_creds id_fkhost id_bzdomaincredential)
    (mem_cached_domain_creds id_frhost id_bvdomaincredential)
    (mem_cached_domain_creds id_frhost id_cddomaincredential)
    (mem_cached_domain_creds id_fyhost id_ctdomaincredential)
    (mem_cached_domain_creds id_fyhost id_ldomaincredential)
    (mem_cached_domain_creds id_gfhost id_cpdomaincredential)
    (mem_cached_domain_creds id_gfhost id_dbdomaincredential)
    (mem_cached_domain_creds id_gmhost id_dbdomaincredential)
    (mem_cached_domain_creds id_gmhost id_xdomaincredential)
    (mem_cached_domain_creds id_gthost id_dbdomaincredential)
    (mem_cached_domain_creds id_gthost id_djdomaincredential)
    (mem_domain_user_admins id_duhost id_cwdomainuser)
    (mem_domain_user_admins id_duhost id_didomainuser)
    (mem_domain_user_admins id_ebhost id_bedomainuser)
    (mem_domain_user_admins id_ebhost id_budomainuser)
    (mem_domain_user_admins id_eihost id_dadomainuser)
    (mem_domain_user_admins id_eihost id_didomainuser)
    (mem_domain_user_admins id_ephost id_csdomainuser)
    (mem_domain_user_admins id_ephost id_odomainuser)
    (mem_domain_user_admins id_ewhost id_bqdomainuser)
    (mem_domain_user_admins id_ewhost id_csdomainuser)
    (mem_domain_user_admins id_fdhost id_ckdomainuser)
    (mem_domain_user_admins id_fdhost id_gdomainuser)
    (mem_domain_user_admins id_fkhost id_bmdomainuser)
    (mem_domain_user_admins id_fkhost id_sdomainuser)
    (mem_domain_user_admins id_frhost id_bedomainuser)
    (mem_domain_user_admins id_frhost id_dadomainuser)
    (mem_domain_user_admins id_fyhost id_bidomainuser)
    (mem_domain_user_admins id_fyhost id_cwdomainuser)
    (mem_domain_user_admins id_gfhost id_codomainuser)
    (mem_domain_user_admins id_gfhost id_csdomainuser)
    (mem_domain_user_admins id_gmhost id_badomainuser)
    (mem_domain_user_admins id_gmhost id_sdomainuser)
    (mem_domain_user_admins id_gthost id_csdomainuser)
    (mem_domain_user_admins id_gthost id_kdomainuser)
    (mem_hosts id_adomain id_duhost)
    (mem_hosts id_adomain id_ebhost)
    (mem_hosts id_adomain id_eihost)
    (mem_hosts id_adomain id_ephost)
    (mem_hosts id_adomain id_ewhost)
    (mem_hosts id_adomain id_fdhost)
    (mem_hosts id_adomain id_fkhost)
    (mem_hosts id_adomain id_frhost)
    (mem_hosts id_adomain id_fyhost)
    (mem_hosts id_adomain id_gfhost)
    (mem_hosts id_adomain id_gmhost)
    (mem_hosts id_adomain id_gthost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_cgdomainuser id_chdomaincredential)
    (prop_cred id_ckdomainuser id_cldomaincredential)
    (prop_cred id_codomainuser id_cpdomaincredential)
    (prop_cred id_csdomainuser id_ctdomaincredential)
    (prop_cred id_cwdomainuser id_cxdomaincredential)
    (prop_cred id_dadomainuser id_dbdomaincredential)
    (prop_cred id_dedomainuser id_dfdomaincredential)
    (prop_cred id_didomainuser id_djdomaincredential)
    (prop_cred id_dmdomainuser id_dndomaincredential)
    (prop_cred id_dqdomainuser id_drdomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (prop_dc id_duhost no)
    (prop_dc id_ebhost no)
    (prop_dc id_eihost no)
    (prop_dc id_ephost no)
    (prop_dc id_ewhost no)
    (prop_dc id_fdhost no)
    (prop_dc id_fkhost no)
    (prop_dc id_frhost no)
    (prop_dc id_fyhost no)
    (prop_dc id_gfhost no)
    (prop_dc id_gmhost no)
    (prop_dc id_gthost no)
    (prop_dns_domain id_adomain str__b)
    (prop_dns_domain_name id_duhost str__dz)
    (prop_dns_domain_name id_ebhost str__eg)
    (prop_dns_domain_name id_eihost str__en)
    (prop_dns_domain_name id_ephost str__eu)
    (prop_dns_domain_name id_ewhost str__fb)
    (prop_dns_domain_name id_fdhost str__fi)
    (prop_dns_domain_name id_fkhost str__fp)
    (prop_dns_domain_name id_frhost str__fw)
    (prop_dns_domain_name id_fyhost str__gd)
    (prop_dns_domain_name id_gfhost str__gk)
    (prop_dns_domain_name id_gmhost str__gr)
    (prop_dns_domain_name id_gthost str__gy)
    (prop_domain id_badomainuser id_adomain)
    (prop_domain id_bbdomaincredential id_adomain)
    (prop_domain id_bedomainuser id_adomain)
    (prop_domain id_bfdomaincredential id_adomain)
    (prop_domain id_bidomainuser id_adomain)
    (prop_domain id_bjdomaincredential id_adomain)
    (prop_domain id_bmdomainuser id_adomain)
    (prop_domain id_bndomaincredential id_adomain)
    (prop_domain id_bqdomainuser id_adomain)
    (prop_domain id_brdomaincredential id_adomain)
    (prop_domain id_budomainuser id_adomain)
    (prop_domain id_bvdomaincredential id_adomain)
    (prop_domain id_bydomainuser id_adomain)
    (prop_domain id_bzdomaincredential id_adomain)
    (prop_domain id_cdomainuser id_adomain)
    (prop_domain id_ccdomainuser id_adomain)
    (prop_domain id_cddomaincredential id_adomain)
    (prop_domain id_cgdomainuser id_adomain)
    (prop_domain id_chdomaincredential id_adomain)
    (prop_domain id_ckdomainuser id_adomain)
    (prop_domain id_cldomaincredential id_adomain)
    (prop_domain id_codomainuser id_adomain)
    (prop_domain id_cpdomaincredential id_adomain)
    (prop_domain id_csdomainuser id_adomain)
    (prop_domain id_ctdomaincredential id_adomain)
    (prop_domain id_cwdomainuser id_adomain)
    (prop_domain id_cxdomaincredential id_adomain)
    (prop_domain id_ddomaincredential id_adomain)
    (prop_domain id_dadomainuser id_adomain)
    (prop_domain id_dbdomaincredential id_adomain)
    (prop_domain id_dedomainuser id_adomain)
    (prop_domain id_dfdomaincredential id_adomain)
    (prop_domain id_didomainuser id_adomain)
    (prop_domain id_djdomaincredential id_adomain)
    (prop_domain id_dmdomainuser id_adomain)
    (prop_domain id_dndomaincredential id_adomain)
    (prop_domain id_dqdomainuser id_adomain)
    (prop_domain id_drdomaincredential id_adomain)
    (prop_domain id_duhost id_adomain)
    (prop_domain id_ebhost id_adomain)
    (prop_domain id_eihost id_adomain)
    (prop_domain id_ephost id_adomain)
    (prop_domain id_ewhost id_adomain)
    (prop_domain id_fdhost id_adomain)
    (prop_domain id_fkhost id_adomain)
    (prop_domain id_frhost id_adomain)
    (prop_domain id_fyhost id_adomain)
    (prop_domain id_gdomainuser id_adomain)
    (prop_domain id_gfhost id_adomain)
    (prop_domain id_gmhost id_adomain)
    (prop_domain id_gthost id_adomain)
    (prop_domain id_hdomaincredential id_adomain)
    (prop_domain id_kdomainuser id_adomain)
    (prop_domain id_ldomaincredential id_adomain)
    (prop_domain id_odomainuser id_adomain)
    (prop_domain id_pdomaincredential id_adomain)
    (prop_domain id_sdomainuser id_adomain)
    (prop_domain id_tdomaincredential id_adomain)
    (prop_domain id_wdomainuser id_adomain)
    (prop_domain id_xdomaincredential id_adomain)
    (prop_elevated id_harat yes)
    (prop_executable id_harat str__hb)
    (prop_fqdn id_duhost str__ea)
    (prop_fqdn id_ebhost str__eh)
    (prop_fqdn id_eihost str__eo)
    (prop_fqdn id_ephost str__ev)
    (prop_fqdn id_ewhost str__fc)
    (prop_fqdn id_fdhost str__fj)
    (prop_fqdn id_fkhost str__fq)
    (prop_fqdn id_frhost str__fx)
    (prop_fqdn id_fyhost str__ge)
    (prop_fqdn id_gfhost str__gl)
    (prop_fqdn id_gmhost str__gs)
    (prop_fqdn id_gthost str__gz)
    (prop_host id_dvtimedelta id_duhost)
    (prop_host id_ectimedelta id_ebhost)
    (prop_host id_ejtimedelta id_eihost)
    (prop_host id_eqtimedelta id_ephost)
    (prop_host id_extimedelta id_ewhost)
    (prop_host id_fetimedelta id_fdhost)
    (prop_host id_fltimedelta id_fkhost)
    (prop_host id_fstimedelta id_frhost)
    (prop_host id_fztimedelta id_fyhost)
    (prop_host id_ggtimedelta id_gfhost)
    (prop_host id_gntimedelta id_gmhost)
    (prop_host id_gutimedelta id_gthost)
    (prop_host id_harat id_fkhost)
    (prop_hostname id_duhost str__dy)
    (prop_hostname id_ebhost str__ef)
    (prop_hostname id_eihost str__em)
    (prop_hostname id_ephost str__et)
    (prop_hostname id_ewhost str__fa)
    (prop_hostname id_fdhost str__fh)
    (prop_hostname id_fkhost str__fo)
    (prop_hostname id_frhost str__fv)
    (prop_hostname id_fyhost str__gc)
    (prop_hostname id_gfhost str__gj)
    (prop_hostname id_gmhost str__gq)
    (prop_hostname id_gthost str__gx)
    (prop_is_group id_badomainuser no)
    (prop_is_group id_bedomainuser no)
    (prop_is_group id_bidomainuser no)
    (prop_is_group id_bmdomainuser no)
    (prop_is_group id_bqdomainuser no)
    (prop_is_group id_budomainuser no)
    (prop_is_group id_bydomainuser no)
    (prop_is_group id_cdomainuser no)
    (prop_is_group id_ccdomainuser no)
    (prop_is_group id_cgdomainuser no)
    (prop_is_group id_ckdomainuser no)
    (prop_is_group id_codomainuser no)
    (prop_is_group id_csdomainuser no)
    (prop_is_group id_cwdomainuser no)
    (prop_is_group id_dadomainuser no)
    (prop_is_group id_dedomainuser no)
    (prop_is_group id_didomainuser no)
    (prop_is_group id_dmdomainuser no)
    (prop_is_group id_dqdomainuser no)
    (prop_is_group id_gdomainuser no)
    (prop_is_group id_kdomainuser no)
    (prop_is_group id_odomainuser no)
    (prop_is_group id_sdomainuser no)
    (prop_is_group id_wdomainuser no)
    (prop_microseconds id_dvtimedelta num__100)
    (prop_microseconds id_ectimedelta num__107)
    (prop_microseconds id_ejtimedelta num__114)
    (prop_microseconds id_eqtimedelta num__121)
    (prop_microseconds id_extimedelta num__128)
    (prop_microseconds id_fetimedelta num__135)
    (prop_microseconds id_fltimedelta num__142)
    (prop_microseconds id_fstimedelta num__149)
    (prop_microseconds id_fztimedelta num__156)
    (prop_microseconds id_ggtimedelta num__163)
    (prop_microseconds id_gntimedelta num__170)
    (prop_microseconds id_gutimedelta num__177)
    (prop_password id_bbdomaincredential str__bc)
    (prop_password id_bfdomaincredential str__bg)
    (prop_password id_bjdomaincredential str__bk)
    (prop_password id_bndomaincredential str__bo)
    (prop_password id_brdomaincredential str__bs)
    (prop_password id_bvdomaincredential str__bw)
    (prop_password id_bzdomaincredential str__ca)
    (prop_password id_cddomaincredential str__ce)
    (prop_password id_chdomaincredential str__ci)
    (prop_password id_cldomaincredential str__cm)
    (prop_password id_cpdomaincredential str__cq)
    (prop_password id_ctdomaincredential str__cu)
    (prop_password id_cxdomaincredential str__cy)
    (prop_password id_ddomaincredential str__e)
    (prop_password id_dbdomaincredential str__dc)
    (prop_password id_dfdomaincredential str__dg)
    (prop_password id_djdomaincredential str__dk)
    (prop_password id_dndomaincredential str__do)
    (prop_password id_drdomaincredential str__ds)
    (prop_password id_hdomaincredential str__i)
    (prop_password id_ldomaincredential str__m)
    (prop_password id_pdomaincredential str__q)
    (prop_password id_tdomaincredential str__u)
    (prop_password id_xdomaincredential str__y)
    (prop_seconds id_dvtimedelta num__101)
    (prop_seconds id_ectimedelta num__108)
    (prop_seconds id_ejtimedelta num__115)
    (prop_seconds id_eqtimedelta num__122)
    (prop_seconds id_extimedelta num__129)
    (prop_seconds id_fetimedelta num__136)
    (prop_seconds id_fltimedelta num__143)
    (prop_seconds id_fstimedelta num__150)
    (prop_seconds id_fztimedelta num__157)
    (prop_seconds id_ggtimedelta num__164)
    (prop_seconds id_gntimedelta num__171)
    (prop_seconds id_gutimedelta num__178)
    (prop_sid id_badomainuser str__bd)
    (prop_sid id_bedomainuser str__bh)
    (prop_sid id_bidomainuser str__bl)
    (prop_sid id_bmdomainuser str__bp)
    (prop_sid id_bqdomainuser str__bt)
    (prop_sid id_budomainuser str__bx)
    (prop_sid id_bydomainuser str__cb)
    (prop_sid id_cdomainuser str__f)
    (prop_sid id_ccdomainuser str__cf)
    (prop_sid id_cgdomainuser str__cj)
    (prop_sid id_ckdomainuser str__cn)
    (prop_sid id_codomainuser str__cr)
    (prop_sid id_csdomainuser str__cv)
    (prop_sid id_cwdomainuser str__cz)
    (prop_sid id_dadomainuser str__dd)
    (prop_sid id_dedomainuser str__dh)
    (prop_sid id_didomainuser str__dl)
    (prop_sid id_dmdomainuser str__dp)
    (prop_sid id_dqdomainuser str__dt)
    (prop_sid id_gdomainuser str__j)
    (prop_sid id_kdomainuser str__n)
    (prop_sid id_odomainuser str__r)
    (prop_sid id_sdomainuser str__v)
    (prop_sid id_wdomainuser str__z)
    (prop_timedelta id_duhost id_dvtimedelta)
    (prop_timedelta id_ebhost id_ectimedelta)
    (prop_timedelta id_eihost id_ejtimedelta)
    (prop_timedelta id_ephost id_eqtimedelta)
    (prop_timedelta id_ewhost id_extimedelta)
    (prop_timedelta id_fdhost id_fetimedelta)
    (prop_timedelta id_fkhost id_fltimedelta)
    (prop_timedelta id_frhost id_fstimedelta)
    (prop_timedelta id_fyhost id_fztimedelta)
    (prop_timedelta id_gfhost id_ggtimedelta)
    (prop_timedelta id_gmhost id_gntimedelta)
    (prop_timedelta id_gthost id_gutimedelta)
    (prop_user id_bbdomaincredential id_badomainuser)
    (prop_user id_bfdomaincredential id_bedomainuser)
    (prop_user id_bjdomaincredential id_bidomainuser)
    (prop_user id_bndomaincredential id_bmdomainuser)
    (prop_user id_brdomaincredential id_bqdomainuser)
    (prop_user id_bvdomaincredential id_budomainuser)
    (prop_user id_bzdomaincredential id_bydomainuser)
    (prop_user id_cddomaincredential id_ccdomainuser)
    (prop_user id_chdomaincredential id_cgdomainuser)
    (prop_user id_cldomaincredential id_ckdomainuser)
    (prop_user id_cpdomaincredential id_codomainuser)
    (prop_user id_ctdomaincredential id_csdomainuser)
    (prop_user id_cxdomaincredential id_cwdomainuser)
    (prop_user id_ddomaincredential id_cdomainuser)
    (prop_user id_dbdomaincredential id_dadomainuser)
    (prop_user id_dfdomaincredential id_dedomainuser)
    (prop_user id_djdomaincredential id_didomainuser)
    (prop_user id_dndomaincredential id_dmdomainuser)
    (prop_user id_drdomaincredential id_dqdomainuser)
    (prop_user id_hdomaincredential id_gdomainuser)
    (prop_user id_ldomaincredential id_kdomainuser)
    (prop_user id_pdomaincredential id_odomainuser)
    (prop_user id_tdomaincredential id_sdomainuser)
    (prop_user id_xdomaincredential id_wdomainuser)
    (prop_username id_badomainuser str__michael)
    (prop_username id_bedomainuser str__barbara)
    (prop_username id_bidomainuser str__william)
    (prop_username id_bmdomainuser str__elizabeth)
    (prop_username id_bqdomainuser str__david)
    (prop_username id_budomainuser str__jennifer)
    (prop_username id_bydomainuser str__richard)
    (prop_username id_cdomainuser str__james)
    (prop_username id_ccdomainuser str__maria)
    (prop_username id_cgdomainuser str__charles)
    (prop_username id_ckdomainuser str__susan)
    (prop_username id_codomainuser str__joseph)
    (prop_username id_csdomainuser str__margaret)
    (prop_username id_cwdomainuser str__thomas)
    (prop_username id_dadomainuser str__dorothy)
    (prop_username id_dedomainuser str__christopher)
    (prop_username id_didomainuser str__lisa)
    (prop_username id_dmdomainuser str__daniel)
    (prop_username id_dqdomainuser str__nancy)
    (prop_username id_gdomainuser str__mary)
    (prop_username id_kdomainuser str__john)
    (prop_username id_odomainuser str__patricia)
    (prop_username id_sdomainuser str__robert)
    (prop_username id_wdomainuser str__linda)
    (prop_windows_domain id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_israt id_eihost)
    (prop_host id_iorat id_gthost)
    (prop_host id_inrat id_ebhost)
    (prop_host id_ixrat id_duhost)
    (prop_host id_iprat id_gmhost)
    (prop_host id_iurat id_fdhost)
    (prop_host id_itrat id_ephost)
    (prop_host id_ivrat id_gfhost)
    (prop_host id_irrat id_fyhost)
    (prop_host id_imrat id_frhost)
    (prop_host id_iqrat id_ewhost)
)
)
(:metric minimize (total-cost))
)