(define (problem blocks-60-0)
(:domain blocks)
(:objects a2 t c2 h2 g1 v b1 y c i c1 b g2 n1 e1 j z 
          j1 n l1 m r a e2 w1 o g r1 d2 d1 a1 s1 b2 
          h1 v1 w u k1 x z1 q1 d p q y1 m1 s h p1 t1 f u1 k i1 o1 f2 e f1 l x1)
(:init (clear a2) (clear t) (clear c2) (clear h2) (clear g1)
                    (clear v) (ontable b1) (ontable y) (ontable c) (ontable i)
                    (ontable c1) (ontable v) (on a2 b) (on b g2) (on g2 n1)
                    (on n1 e1) (on e1 j) (on j z) (on z j1) (on j1 n)
                    (on n l1) (on l1 m) (on m r) (on r a) (on a e2) (on e2 w1)
                    (on w1 o) (on o g) (on g r1) (on r1 d2) (on d2 d1)
                    (on d1 a1) (on a1 s1) (on s1 b2) (on b2 h1) (on h1 v1)
                    (on v1 w) (on w u) (on u k1) (on k1 b1) (on t x) (on x z1)
                    (on z1 q1) (on q1 d) (on d p) (on p q) (on q y1)
                    (on y1 m1) (on m1 s) (on s h) (on h p1) (on p1 t1)
                    (on t1 f) (on f u1) (on u1 k) (on k i1) (on i1 o1)
                    (on o1 y) (on c2 c) (on h2 f2) (on f2 e) (on e f1)
                    (on f1 l) (on l x1) (on x1 i) (on g1 c1) (handempty))
(:goal (and (on s l1) (on l1 i) (on i i1) (on i1 h2) (on h2 j) (on j g1)
           (on g1 w1) (on w1 r) (on r b) (on b q) (on q v) (on v u1) (on u1 g)
           (on g n1) (on n1 e2) (on e2 d1) (on d1 z1) (on z1 a) (on a n)
           (on n h1) (on h1 e1) (on e1 r1) (on r1 a1) (on a1 a2) (on a2 k)
           (on k o1) (on o1 c) (on c b2) (on b2 s1) (on s1 o) (on o c1)
           (on c1 e) (on e t) (on t y) (on y p1) (on p1 x1) (on x1 f)
           (on f f2) (on f2 m1) (on m1 b1) (on b1 m) (on m f1) (on f1 w)
           (on w u) (on u z) (on z t1) (on t1 l) (on l j1) (on j1 x) (on x y1)
           (on y1 d2) (on d2 c2) (on c2 d) (on d v1) (on v1 q1) (on q1 k1)
           (on k1 h) (on h g2) (on g2 p)))
)