(define (problem blocks-35-1)
(:domain blocks)
(:objects c m g1 l t d1 q g b1 w x u y r d h1 b a n j e v 
          h p f c1 s k o z f1 a1 i i1 e1) 
(:init (clear c) (clear m) (clear g1) (ontable l) (ontable t)
                    (ontable d1) (on c q) (on q g) (on g b1) (on b1 w)
                    (on w x) (on x u) (on u y) (on y r) (on r d) (on d h1)
                    (on h1 b) (on b a) (on a n) (on n j) (on j e) (on e v)
                    (on v h) (on h p) (on p f) (on f c1) (on c1 s) (on s k)
                    (on k o) (on o z) (on z f1) (on f1 a1) (on a1 i) (on i i1)
                    (on i1 l) (on m e1) (on e1 t) (on g1 d1) (handempty))
(:goal (and (on i f1) (on f1 c) (on c r) (on r j) (on j f) (on f s) (on s z)
           (on z g1) (on g1 d) (on d v) (on v c1) (on c1 h1) (on h1 h)
           (on h m) (on m b1) (on b1 i1) (on i1 l) (on l a) (on a a1)
           (on a1 b) (on b y) (on y k) (on k e) (on e p) (on p d1) (on d1 u)
           (on u q) (on q x) (on x g) (on g e1) (on e1 n) (on n t) (on t w)
           (on w o)))
)