(define (problem blocks-28-0)
(:domain blocks)
(:objects m e s z w h d p i q o r c b a1 n a v j g b1 u y l f t k x )
(:init (clear x) (clear k) (clear t) (clear f) (ontable l) (ontable y)
 (ontable u) (ontable b1) (on x g) (on g j) (on j v) (on v a) (on a n)
 (on n a1) (on a1 b) (on b c) (on c r) (on r l) (on k y) (on t o) (on o u)
 (on f q) (on q i) (on i p) (on p d) (on d h) (on h w) (on w z) (on z s)
 (on s e) (on e m) (on m b1) (handempty))
(:goal (and (on b1 n) (on n a) (on a y) (on y d) (on d a1) (on a1 t) (on t r)
            (on r x) (on x g) (on g b) (on b f) (on f c) (on c u) (on u k)
            (on k m) (on m w) (on w z) (on z j) (on j p) (on p o) (on o l)
            (on l s) (on s e) (on e i) (on i v) (on v q) (on q h)))
)