(define (problem blocks-55-0)
(:domain blocks)
(:objects a1 v r1 l t1 i i1 x c1 q1 h m f1 y b d e h1 s1 j m1 w
          a2 c e1 n1 s v1 p1 r o g1 z1 w1 p g k k1 b2 a t n o1 u1 
          j1 l1 x1 z y1 f b1 c2 u d1 q)

(:init (clear a1) (clear v) (clear r1) (clear l) (clear t1)
                    (ontable i) (ontable i1) (ontable r1) (ontable x)
                    (ontable c1) (on a1 q1) (on q1 h) (on h m) (on m f1)
                    (on f1 y) (on y b) (on b d) (on d e) (on e h1) (on h1 s1)
                    (on s1 j) (on j m1) (on m1 w) (on w a2) (on a2 c)
                    (on c e1) (on e1 n1) (on n1 s) (on s v1) (on v1 p1)
                    (on p1 r) (on r o) (on o g1) (on g1 i) (on v z1)
                    (on z1 w1) (on w1 p) (on p g) (on g k) (on k k1)
                    (on k1 i1) (on l b2) (on b2 a) (on a t) (on t n) (on n o1)
                    (on o1 u1) (on u1 j1) (on j1 l1) (on l1 x1) (on x1 z)
                    (on z y1) (on y1 f) (on f b1) (on b1 c2) (on c2 x)
                    (on t1 u) (on u d1) (on d1 q) (on q c1) (handempty))
(:goal (and (on e r) (on r h1) (on h1 x1) (on x1 v1) (on v1 b2) (on b2 q)
           (on q a) (on a h) (on h y1) (on y1 i1) (on i1 p) (on p c) (on c f)
           (on f s) (on s w1) (on w1 a1) (on a1 k1) (on k1 s1) (on s1 o1)
           (on o1 d) (on d g) (on g e1) (on e1 t1) (on t1 y) (on y b1)
           (on b1 v) (on v q1) (on q1 c2) (on c2 z1) (on z1 f1) (on f1 d1)
           (on d1 l1) (on l1 t) (on t c1) (on c1 n) (on n k) (on k r1)
           (on r1 a2) (on a2 n1) (on n1 b) (on b z) (on z g1) (on g1 x)
           (on x o) (on o j1) (on j1 p1) (on p1 m1) (on m1 l) (on l w)
           (on w j) (on j m) (on m u) (on u i) (on i u1)))
)