(define (problem blocks-60-1)
(:domain blocks)
(:objects m1 b1 e d1 h1 q i e1 n1 f2 m y1 j o1 k1 c2
          l t1 n t f1 r d2 r1 h2 v1 e2 c w1 a v z1 u1 
          a2 q1 d a1 g j1 k i1 z b2 x1 l1 y o f p1 g2 u w c1 s1 g1 h b s p x)

(:init (clear m1) (clear b1) (clear e) (clear d1) (clear h1)
                    (clear q) (ontable i) (ontable e1) (ontable n1)
                    (ontable f2) (ontable h1) (ontable q) (on m1 m) (on m y1)
                    (on y1 j) (on j o1) (on o1 k1) (on k1 c2) (on c2 l)
                    (on l t1) (on t1 i) (on b1 n) (on n t) (on t f1) (on f1 r)
                    (on r d2) (on d2 r1) (on r1 h2) (on h2 v1) (on v1 e2)
                    (on e2 c) (on c w1) (on w1 a) (on a v) (on v z1)
                    (on z1 e1) (on e u1) (on u1 a2) (on a2 q1) (on q1 d)
                    (on d a1) (on a1 g) (on g j1) (on j1 k) (on k i1)
                    (on i1 z) (on z b2) (on b2 x1) (on x1 l1) (on l1 y)
                    (on y o) (on o f) (on f p1) (on p1 g2) (on g2 u) (on u w)
                    (on w c1) (on c1 s1) (on s1 g1) (on g1 h) (on h b)
                    (on b s) (on s p) (on p x) (on x n1) (on d1 f2)
                    (handempty))
(:goal (and (on g b2) (on b2 x) (on x r1) (on r1 d2) (on d2 z) (on z n)
           (on n i) (on i w) (on w f2) (on f2 b) (on b m1) (on m1 o1)
           (on o1 t1) (on t1 p1) (on p1 n1) (on n1 f1) (on f1 c) (on c c1)
           (on c1 k1) (on k1 a2) (on a2 j) (on j j1) (on j1 p) (on p g1)
           (on g1 s) (on s a) (on a e1) (on e1 h) (on h h1) (on h1 v) (on v f)
           (on f g2) (on g2 l1) (on l1 y1) (on y1 x1) (on x1 i1) (on i1 t)
           (on t l) (on l e) (on e w1) (on w1 b1) (on b1 r) (on r u1)
           (on u1 u) (on u q) (on q m) (on m c2) (on c2 h2) (on h2 q1)
           (on q1 a1) (on a1 s1) (on s1 z1) (on z1 d1) (on d1 k) (on k y)
           (on y v1) (on v1 d) (on d o) (on o e2)))
)