(define (problem blocks-55-1)
(:domain blocks)
(:objects v1 p u a1 x1 x a2 o1 s b2 a t k1 g1 g y d1 m1 k y1 q1 
          o f1 u1 i1 d z1 c2 w p1 n z e b1 r1 n1 t1 i s1 f l1 m b 
          h1 j j1 v h l c c1 e1 q w1 r)
(:init (clear v1) (clear p) (clear u) (clear a1) (clear x1)
                    (ontable x) (ontable a2) (ontable o1) (ontable s)
                    (ontable x1) (on v1 b2) (on b2 a) (on a t) (on t k1)
                    (on k1 g1) (on g1 g) (on g y) (on y d1) (on d1 m1)
                    (on m1 k) (on k y1) (on y1 q1) (on q1 o) (on o f1)
                    (on f1 u1) (on u1 i1) (on i1 d) (on d z1) (on z1 c2)
                    (on c2 w) (on w p1) (on p1 n) (on n z) (on z e) (on e b1)
                    (on b1 r1) (on r1 n1) (on n1 t1) (on t1 i) (on i s1)
                    (on s1 f) (on f l1) (on l1 m) (on m b) (on b h1) (on h1 x)
                    (on p j) (on j j1) (on j1 v) (on v h) (on h l) (on l c)
                    (on c a2) (on u c1) (on c1 e1) (on e1 q) (on q w1)
                    (on w1 r) (on r o1) (on a1 s) (handempty))
(:goal (and (on b c2) (on c2 h) (on h p) (on p c1) (on c1 s) (on s o) (on o o1)
           (on o1 m) (on m l) (on l y) (on y j1) (on j1 q) (on q m1)
           (on m1 i1) (on i1 a) (on a i) (on i t1) (on t1 r) (on r z)
           (on z q1) (on q1 e1) (on e1 b2) (on b2 g1) (on g1 l1) (on l1 a2)
           (on a2 e) (on e x) (on x w1) (on w1 u) (on u a1) (on a1 s1)
           (on s1 p1) (on p1 x1) (on x1 r1) (on r1 c) (on c y1) (on y1 d)
           (on d h1) (on h1 n1) (on n1 z1) (on z1 k1) (on k1 f1) (on f1 g)
           (on g w) (on w n) (on n f) (on f j) (on j d1) (on d1 k) (on k u1)
           (on u1 b1) (on b1 v1) (on v1 t) (on t v)))
)