(define (problem blocks-50-1)
(:domain blocks)
(:objects j d1 y u q l f1 d e1 m v f r a1 m1 z x h1 
          k e n o s b1 r1 q1 h o1 t1 g j1 p k1 u1 b s1 c1 x1
          a w w1 i1 n1 v1 t l1 p1 g1 c i)
(:init (clear j) (clear d1) (clear y) (clear u) (clear q)
                    (ontable l) (ontable f1) (ontable d) (ontable u)
                    (ontable q) (on j e1) (on e1 m) (on m v) (on v f) (on f r)
                    (on r a1) (on a1 m1) (on m1 z) (on z x) (on x h1)
                    (on h1 k) (on k e) (on e n) (on n o) (on o s) (on s b1)
                    (on b1 r1) (on r1 q1) (on q1 h) (on h o1) (on o1 t1)
                    (on t1 g) (on g j1) (on j1 p) (on p k1) (on k1 l)
                    (on d1 u1) (on u1 b) (on b s1) (on s1 c1) (on c1 x1)
                    (on x1 a) (on a w) (on w w1) (on w1 i1) (on i1 n1)
                    (on n1 v1) (on v1 t) (on t l1) (on l1 f1) (on y p1)
                    (on p1 g1) (on g1 c) (on c i) (on i d) (handempty))
(:goal (and (on c a) (on a u1) (on u1 n) (on n m1) (on m1 x1) (on x1 k)
           (on k h1) (on h1 t1) (on t1 v) (on v e) (on e q) (on q r1)
           (on r1 s) (on s l1) (on l1 i1) (on i1 d1) (on d1 w) (on w m)
           (on m r) (on r g) (on g s1) (on s1 y) (on y n1) (on n1 b) (on b h)
           (on h e1) (on e1 f1) (on f1 p) (on p f) (on f d) (on d c1)
           (on c1 a1) (on a1 o) (on o u) (on u l) (on l b1) (on b1 v1)
           (on v1 w1) (on w1 k1) (on k1 i) (on i o1) (on o1 x) (on x j)
           (on j j1) (on j1 t) (on t g1) (on g1 z) (on z p1) (on p1 q1)))
)