(define (problem freecell5-4)
(:domain freecell)
(:objects
	diamond club heart spade 
	n0 n1 n2 n3 n4 n5 club5
	club2
	heart4
	club3
	spade4
	heart3
	diamond3
	spade5
	club4
	diamond2
	diamond4
	hearta
	diamonda
	heart2
	diamond5
	heart5
	spadea
	spade2
	cluba
	spade3
	diamond0
	club0
	heart0
	spade0
	
)
(:init
	(successor n1 n0)
	(successor n2 n1)
	(successor n3 n2)
	(successor n4 n3)
	(successor n5 n4)
	(cellspace n2)
	(clear club5)
	(on club5 heart3)
	(on heart3 diamond4)
	(on diamond4 heart5)
	(bottomcol heart5)
	(clear club2)
	(on club2 diamond3)
	(on diamond3 hearta)
	(on hearta spadea)
	(bottomcol spadea)
	(clear heart4)
	(on heart4 spade5)
	(on spade5 diamonda)
	(on diamonda spade2)
	(bottomcol spade2)
	(clear club3)
	(on club3 club4)
	(on club4 heart2)
	(on heart2 cluba)
	(bottomcol cluba)
	(clear spade4)
	(on spade4 diamond2)
	(on diamond2 diamond5)
	(on diamond5 spade3)
	(bottomcol spade3)
	(colspace n0)
	(value club5 n5)
	(suit club5 club)
	(value club2 n2)
	(suit club2 club)
	(canstack club2 diamond3)
	(canstack club2 heart3)
	(value heart4 n4)
	(suit heart4 heart)
	(canstack heart4 club5)
	(canstack heart4 spade5)
	(value club3 n3)
	(suit club3 club)
	(canstack club3 diamond4)
	(canstack club3 heart4)
	(value spade4 n4)
	(suit spade4 spade)
	(canstack spade4 diamond5)
	(canstack spade4 heart5)
	(value heart3 n3)
	(suit heart3 heart)
	(canstack heart3 club4)
	(canstack heart3 spade4)
	(value diamond3 n3)
	(suit diamond3 diamond)
	(canstack diamond3 club4)
	(canstack diamond3 spade4)
	(value spade5 n5)
	(suit spade5 spade)
	(value club4 n4)
	(suit club4 club)
	(canstack club4 diamond5)
	(canstack club4 heart5)
	(value diamond2 n2)
	(suit diamond2 diamond)
	(canstack diamond2 club3)
	(canstack diamond2 spade3)
	(value diamond4 n4)
	(suit diamond4 diamond)
	(canstack diamond4 club5)
	(canstack diamond4 spade5)
	(value hearta n1)
	(suit hearta heart)
	(canstack hearta club2)
	(canstack hearta spade2)
	(value diamonda n1)
	(suit diamonda diamond)
	(canstack diamonda club2)
	(canstack diamonda spade2)
	(value heart2 n2)
	(suit heart2 heart)
	(canstack heart2 club3)
	(canstack heart2 spade3)
	(value diamond5 n5)
	(suit diamond5 diamond)
	(value heart5 n5)
	(suit heart5 heart)
	(value spadea n1)
	(suit spadea spade)
	(canstack spadea diamond2)
	(canstack spadea heart2)
	(value spade2 n2)
	(suit spade2 spade)
	(canstack spade2 diamond3)
	(canstack spade2 heart3)
	(value cluba n1)
	(suit cluba club)
	(canstack cluba diamond2)
	(canstack cluba heart2)
	(value spade3 n3)
	(suit spade3 spade)
	(canstack spade3 diamond4)
	(canstack spade3 heart4)
	(home diamond0)
	(value diamond0 n0)
	(suit diamond0 diamond)
	(home club0)
	(value club0 n0)
	(suit club0 club)
	(home heart0)
	(value heart0 n0)
	(suit heart0 heart)
	(home spade0)
	(value spade0 n0)
	(suit spade0 spade)
)
(:goal (and
	(home diamond5)
	(home club5)
	(home heart5)
	(home spade5)
)))
