(define (problem freecell13-4)
(:domain freecell)
(:objects
	diamond club heart spade 
	n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 clubk
	spade7
	diamond9
	diamond2
	spade6
	diamond5
	spade2
	spadej
	club7
	hearta
	heart8
	spade4
	heart9
	spadeq
	club4
	spade8
	spade5
	heart6
	club8
	club3
	club9
	diamondq
	diamondj
	heartq
	heart2
	diamond7
	heart7
	spade10
	heart4
	club6
	heartj
	diamond10
	club5
	spade9
	heart10
	diamond6
	spade3
	spadek
	diamond4
	heartk
	heart3
	club10
	diamond3
	spadea
	club2
	diamonda
	clubj
	diamond8
	heart5
	cluba
	diamondk
	clubq
	diamond0
	club0
	heart0
	spade0
	
)
(:init
	(successor n1 n0)
	(successor n2 n1)
	(successor n3 n2)
	(successor n4 n3)
	(successor n5 n4)
	(successor n6 n5)
	(successor n7 n6)
	(successor n8 n7)
	(successor n9 n8)
	(successor n10 n9)
	(successor n11 n10)
	(successor n12 n11)
	(successor n13 n12)
	(cellspace n4)
	(clear clubk)
	(on clubk club7)
	(on club7 spade5)
	(on spade5 heart2)
	(on heart2 club5)
	(on club5 heart3)
	(on heart3 heart5)
	(bottomcol heart5)
	(clear spade7)
	(on spade7 hearta)
	(on hearta heart6)
	(on heart6 diamond7)
	(on diamond7 spade9)
	(on spade9 club10)
	(on club10 cluba)
	(bottomcol cluba)
	(clear diamond9)
	(on diamond9 heart8)
	(on heart8 club8)
	(on club8 heart7)
	(on heart7 heart10)
	(on heart10 diamond3)
	(on diamond3 diamondk)
	(bottomcol diamondk)
	(clear diamond2)
	(on diamond2 spade4)
	(on spade4 club3)
	(on club3 spade10)
	(on spade10 diamond6)
	(on diamond6 spadea)
	(on spadea clubq)
	(bottomcol clubq)
	(clear spade6)
	(on spade6 heart9)
	(on heart9 club9)
	(on club9 heart4)
	(on heart4 spade3)
	(on spade3 club2)
	(bottomcol club2)
	(clear diamond5)
	(on diamond5 spadeq)
	(on spadeq diamondq)
	(on diamondq club6)
	(on club6 spadek)
	(on spadek diamonda)
	(bottomcol diamonda)
	(clear spade2)
	(on spade2 club4)
	(on club4 diamondj)
	(on diamondj heartj)
	(on heartj diamond4)
	(on diamond4 clubj)
	(bottomcol clubj)
	(clear spadej)
	(on spadej spade8)
	(on spade8 heartq)
	(on heartq diamond10)
	(on diamond10 heartk)
	(on heartk diamond8)
	(bottomcol diamond8)
	(colspace n0)
	(value clubk n13)
	(suit clubk club)
	(value spade7 n7)
	(suit spade7 spade)
	(canstack spade7 diamond8)
	(canstack spade7 heart8)
	(value diamond9 n9)
	(suit diamond9 diamond)
	(canstack diamond9 club10)
	(canstack diamond9 spade10)
	(value diamond2 n2)
	(suit diamond2 diamond)
	(canstack diamond2 club3)
	(canstack diamond2 spade3)
	(value spade6 n6)
	(suit spade6 spade)
	(canstack spade6 diamond7)
	(canstack spade6 heart7)
	(value diamond5 n5)
	(suit diamond5 diamond)
	(canstack diamond5 club6)
	(canstack diamond5 spade6)
	(value spade2 n2)
	(suit spade2 spade)
	(canstack spade2 diamond3)
	(canstack spade2 heart3)
	(value spadej n11)
	(suit spadej spade)
	(canstack spadej diamondq)
	(canstack spadej heartq)
	(value club7 n7)
	(suit club7 club)
	(canstack club7 diamond8)
	(canstack club7 heart8)
	(value hearta n1)
	(suit hearta heart)
	(canstack hearta club2)
	(canstack hearta spade2)
	(value heart8 n8)
	(suit heart8 heart)
	(canstack heart8 club9)
	(canstack heart8 spade9)
	(value spade4 n4)
	(suit spade4 spade)
	(canstack spade4 diamond5)
	(canstack spade4 heart5)
	(value heart9 n9)
	(suit heart9 heart)
	(canstack heart9 club10)
	(canstack heart9 spade10)
	(value spadeq n12)
	(suit spadeq spade)
	(canstack spadeq diamondk)
	(canstack spadeq heartk)
	(value club4 n4)
	(suit club4 club)
	(canstack club4 diamond5)
	(canstack club4 heart5)
	(value spade8 n8)
	(suit spade8 spade)
	(canstack spade8 diamond9)
	(canstack spade8 heart9)
	(value spade5 n5)
	(suit spade5 spade)
	(canstack spade5 diamond6)
	(canstack spade5 heart6)
	(value heart6 n6)
	(suit heart6 heart)
	(canstack heart6 club7)
	(canstack heart6 spade7)
	(value club8 n8)
	(suit club8 club)
	(canstack club8 diamond9)
	(canstack club8 heart9)
	(value club3 n3)
	(suit club3 club)
	(canstack club3 diamond4)
	(canstack club3 heart4)
	(value club9 n9)
	(suit club9 club)
	(canstack club9 diamond10)
	(canstack club9 heart10)
	(value diamondq n12)
	(suit diamondq diamond)
	(canstack diamondq clubk)
	(canstack diamondq spadek)
	(value diamondj n11)
	(suit diamondj diamond)
	(canstack diamondj clubq)
	(canstack diamondj spadeq)
	(value heartq n12)
	(suit heartq heart)
	(canstack heartq clubk)
	(canstack heartq spadek)
	(value heart2 n2)
	(suit heart2 heart)
	(canstack heart2 club3)
	(canstack heart2 spade3)
	(value diamond7 n7)
	(suit diamond7 diamond)
	(canstack diamond7 club8)
	(canstack diamond7 spade8)
	(value heart7 n7)
	(suit heart7 heart)
	(canstack heart7 club8)
	(canstack heart7 spade8)
	(value spade10 n10)
	(suit spade10 spade)
	(canstack spade10 diamondj)
	(canstack spade10 heartj)
	(value heart4 n4)
	(suit heart4 heart)
	(canstack heart4 club5)
	(canstack heart4 spade5)
	(value club6 n6)
	(suit club6 club)
	(canstack club6 diamond7)
	(canstack club6 heart7)
	(value heartj n11)
	(suit heartj heart)
	(canstack heartj clubq)
	(canstack heartj spadeq)
	(value diamond10 n10)
	(suit diamond10 diamond)
	(canstack diamond10 clubj)
	(canstack diamond10 spadej)
	(value club5 n5)
	(suit club5 club)
	(canstack club5 diamond6)
	(canstack club5 heart6)
	(value spade9 n9)
	(suit spade9 spade)
	(canstack spade9 diamond10)
	(canstack spade9 heart10)
	(value heart10 n10)
	(suit heart10 heart)
	(canstack heart10 clubj)
	(canstack heart10 spadej)
	(value diamond6 n6)
	(suit diamond6 diamond)
	(canstack diamond6 club7)
	(canstack diamond6 spade7)
	(value spade3 n3)
	(suit spade3 spade)
	(canstack spade3 diamond4)
	(canstack spade3 heart4)
	(value spadek n13)
	(suit spadek spade)
	(value diamond4 n4)
	(suit diamond4 diamond)
	(canstack diamond4 club5)
	(canstack diamond4 spade5)
	(value heartk n13)
	(suit heartk heart)
	(value heart3 n3)
	(suit heart3 heart)
	(canstack heart3 club4)
	(canstack heart3 spade4)
	(value club10 n10)
	(suit club10 club)
	(canstack club10 diamondj)
	(canstack club10 heartj)
	(value diamond3 n3)
	(suit diamond3 diamond)
	(canstack diamond3 club4)
	(canstack diamond3 spade4)
	(value spadea n1)
	(suit spadea spade)
	(canstack spadea diamond2)
	(canstack spadea heart2)
	(value club2 n2)
	(suit club2 club)
	(canstack club2 diamond3)
	(canstack club2 heart3)
	(value diamonda n1)
	(suit diamonda diamond)
	(canstack diamonda club2)
	(canstack diamonda spade2)
	(value clubj n11)
	(suit clubj club)
	(canstack clubj diamondq)
	(canstack clubj heartq)
	(value diamond8 n8)
	(suit diamond8 diamond)
	(canstack diamond8 club9)
	(canstack diamond8 spade9)
	(value heart5 n5)
	(suit heart5 heart)
	(canstack heart5 club6)
	(canstack heart5 spade6)
	(value cluba n1)
	(suit cluba club)
	(canstack cluba diamond2)
	(canstack cluba heart2)
	(value diamondk n13)
	(suit diamondk diamond)
	(value clubq n12)
	(suit clubq club)
	(canstack clubq diamondk)
	(canstack clubq heartk)
	(home diamond0)
	(value diamond0 n0)
	(suit diamond0 diamond)
	(home club0)
	(value club0 n0)
	(suit club0 club)
	(home heart0)
	(value heart0 n0)
	(suit heart0 heart)
	(home spade0)
	(value spade0 n0)
	(suit spade0 spade)
)
(:goal (and
	(home diamondk)
	(home clubk)
	(home heartk)
	(home spadek)
)))
