(define (problem freecell4-4)
(:domain freecell)
(:objects
	diamond club heart spade 
	n0 n1 n2 n3 n4 n5 club3
	diamond2
	heart3
	diamond4
	diamonda
	spade3
	cluba
	spadea
	diamond3
	spade2
	heart2
	heart4
	hearta
	club2
	club4
	spade4
	diamond0
	club0
	heart0
	spade0
	
)
(:init
	(successor n1 n0)
	(successor n2 n1)
	(successor n3 n2)
	(successor n4 n3)
	(successor n5 n4)
	(cellspace n2)
	(clear club3)
	(on club3 spade3)
	(on spade3 heart2)
	(on heart2 spade4)
	(bottomcol spade4)
	(clear diamond2)
	(on diamond2 cluba)
	(on cluba heart4)
	(bottomcol heart4)
	(clear heart3)
	(on heart3 spadea)
	(on spadea hearta)
	(bottomcol hearta)
	(clear diamond4)
	(on diamond4 diamond3)
	(on diamond3 club2)
	(bottomcol club2)
	(clear diamonda)
	(on diamonda spade2)
	(on spade2 club4)
	(bottomcol club4)
	(colspace n0)
	(value club3 n3)
	(suit club3 club)
	(canstack club3 diamond4)
	(canstack club3 heart4)
	(value diamond2 n2)
	(suit diamond2 diamond)
	(canstack diamond2 club3)
	(canstack diamond2 spade3)
	(value heart3 n3)
	(suit heart3 heart)
	(canstack heart3 club4)
	(canstack heart3 spade4)
	(value diamond4 n4)
	(suit diamond4 diamond)
	(value diamonda n1)
	(suit diamonda diamond)
	(canstack diamonda club2)
	(canstack diamonda spade2)
	(value spade3 n3)
	(suit spade3 spade)
	(canstack spade3 diamond4)
	(canstack spade3 heart4)
	(value cluba n1)
	(suit cluba club)
	(canstack cluba diamond2)
	(canstack cluba heart2)
	(value spadea n1)
	(suit spadea spade)
	(canstack spadea diamond2)
	(canstack spadea heart2)
	(value diamond3 n3)
	(suit diamond3 diamond)
	(canstack diamond3 club4)
	(canstack diamond3 spade4)
	(value spade2 n2)
	(suit spade2 spade)
	(canstack spade2 diamond3)
	(canstack spade2 heart3)
	(value heart2 n2)
	(suit heart2 heart)
	(canstack heart2 club3)
	(canstack heart2 spade3)
	(value heart4 n4)
	(suit heart4 heart)
	(value hearta n1)
	(suit hearta heart)
	(canstack hearta club2)
	(canstack hearta spade2)
	(value club2 n2)
	(suit club2 club)
	(canstack club2 diamond3)
	(canstack club2 heart3)
	(value club4 n4)
	(suit club4 club)
	(value spade4 n4)
	(suit spade4 spade)
	(home diamond0)
	(value diamond0 n0)
	(suit diamond0 diamond)
	(home club0)
	(value club0 n0)
	(suit club0 club)
	(home heart0)
	(value heart0 n0)
	(suit heart0 heart)
	(home spade0)
	(value spade0 n0)
	(suit spade0 spade)
)
(:goal (and
	(home diamond4)
	(home club4)
	(home heart4)
	(home spade4)
)))
