(define (problem freecell13-4)
(:domain freecell)
(:objects
	diamond club heart spade 
	n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 clubq
	diamonda
	club2
	heart7
	diamondk
	spadeq
	diamond4
	club10
	heart3
	spadej
	diamondj
	club7
	diamond2
	club5
	spade5
	spadea
	diamond5
	spadek
	spade2
	heart5
	heart4
	spade7
	diamond3
	club8
	clubj
	club4
	heartj
	heart9
	diamond8
	club6
	hearta
	heart2
	diamond7
	heart6
	diamond6
	spade10
	spade8
	club9
	spade6
	spade4
	heart8
	heartk
	spade9
	clubk
	heart10
	heartq
	club3
	diamondq
	diamond10
	cluba
	diamond9
	spade3
	diamond0
	club0
	heart0
	spade0
	
)
(:init
	(successor n1 n0)
	(successor n2 n1)
	(successor n3 n2)
	(successor n4 n3)
	(successor n5 n4)
	(successor n6 n5)
	(successor n7 n6)
	(successor n8 n7)
	(successor n9 n8)
	(successor n10 n9)
	(successor n11 n10)
	(successor n12 n11)
	(successor n13 n12)
	(cellspace n4)
	(clear clubq)
	(on clubq heart3)
	(on heart3 diamond5)
	(on diamond5 clubj)
	(on clubj diamond7)
	(on diamond7 heart8)
	(on heart8 diamond10)
	(bottomcol diamond10)
	(clear diamonda)
	(on diamonda spadej)
	(on spadej spadek)
	(on spadek club4)
	(on club4 heart6)
	(on heart6 heartk)
	(on heartk cluba)
	(bottomcol cluba)
	(clear club2)
	(on club2 diamondj)
	(on diamondj spade2)
	(on spade2 heartj)
	(on heartj diamond6)
	(on diamond6 spade9)
	(on spade9 diamond9)
	(bottomcol diamond9)
	(clear heart7)
	(on heart7 club7)
	(on club7 heart5)
	(on heart5 heart9)
	(on heart9 spade10)
	(on spade10 clubk)
	(on clubk spade3)
	(bottomcol spade3)
	(clear diamondk)
	(on diamondk diamond2)
	(on diamond2 heart4)
	(on heart4 diamond8)
	(on diamond8 spade8)
	(on spade8 heart10)
	(bottomcol heart10)
	(clear spadeq)
	(on spadeq club5)
	(on club5 spade7)
	(on spade7 club6)
	(on club6 club9)
	(on club9 heartq)
	(bottomcol heartq)
	(clear diamond4)
	(on diamond4 spade5)
	(on spade5 diamond3)
	(on diamond3 hearta)
	(on hearta spade6)
	(on spade6 club3)
	(bottomcol club3)
	(clear club10)
	(on club10 spadea)
	(on spadea club8)
	(on club8 heart2)
	(on heart2 spade4)
	(on spade4 diamondq)
	(bottomcol diamondq)
	(colspace n0)
	(value clubq n12)
	(suit clubq club)
	(canstack clubq diamondk)
	(canstack clubq heartk)
	(value diamonda n1)
	(suit diamonda diamond)
	(canstack diamonda club2)
	(canstack diamonda spade2)
	(value club2 n2)
	(suit club2 club)
	(canstack club2 diamond3)
	(canstack club2 heart3)
	(value heart7 n7)
	(suit heart7 heart)
	(canstack heart7 club8)
	(canstack heart7 spade8)
	(value diamondk n13)
	(suit diamondk diamond)
	(value spadeq n12)
	(suit spadeq spade)
	(canstack spadeq diamondk)
	(canstack spadeq heartk)
	(value diamond4 n4)
	(suit diamond4 diamond)
	(canstack diamond4 club5)
	(canstack diamond4 spade5)
	(value club10 n10)
	(suit club10 club)
	(canstack club10 diamondj)
	(canstack club10 heartj)
	(value heart3 n3)
	(suit heart3 heart)
	(canstack heart3 club4)
	(canstack heart3 spade4)
	(value spadej n11)
	(suit spadej spade)
	(canstack spadej diamondq)
	(canstack spadej heartq)
	(value diamondj n11)
	(suit diamondj diamond)
	(canstack diamondj clubq)
	(canstack diamondj spadeq)
	(value club7 n7)
	(suit club7 club)
	(canstack club7 diamond8)
	(canstack club7 heart8)
	(value diamond2 n2)
	(suit diamond2 diamond)
	(canstack diamond2 club3)
	(canstack diamond2 spade3)
	(value club5 n5)
	(suit club5 club)
	(canstack club5 diamond6)
	(canstack club5 heart6)
	(value spade5 n5)
	(suit spade5 spade)
	(canstack spade5 diamond6)
	(canstack spade5 heart6)
	(value spadea n1)
	(suit spadea spade)
	(canstack spadea diamond2)
	(canstack spadea heart2)
	(value diamond5 n5)
	(suit diamond5 diamond)
	(canstack diamond5 club6)
	(canstack diamond5 spade6)
	(value spadek n13)
	(suit spadek spade)
	(value spade2 n2)
	(suit spade2 spade)
	(canstack spade2 diamond3)
	(canstack spade2 heart3)
	(value heart5 n5)
	(suit heart5 heart)
	(canstack heart5 club6)
	(canstack heart5 spade6)
	(value heart4 n4)
	(suit heart4 heart)
	(canstack heart4 club5)
	(canstack heart4 spade5)
	(value spade7 n7)
	(suit spade7 spade)
	(canstack spade7 diamond8)
	(canstack spade7 heart8)
	(value diamond3 n3)
	(suit diamond3 diamond)
	(canstack diamond3 club4)
	(canstack diamond3 spade4)
	(value club8 n8)
	(suit club8 club)
	(canstack club8 diamond9)
	(canstack club8 heart9)
	(value clubj n11)
	(suit clubj club)
	(canstack clubj diamondq)
	(canstack clubj heartq)
	(value club4 n4)
	(suit club4 club)
	(canstack club4 diamond5)
	(canstack club4 heart5)
	(value heartj n11)
	(suit heartj heart)
	(canstack heartj clubq)
	(canstack heartj spadeq)
	(value heart9 n9)
	(suit heart9 heart)
	(canstack heart9 club10)
	(canstack heart9 spade10)
	(value diamond8 n8)
	(suit diamond8 diamond)
	(canstack diamond8 club9)
	(canstack diamond8 spade9)
	(value club6 n6)
	(suit club6 club)
	(canstack club6 diamond7)
	(canstack club6 heart7)
	(value hearta n1)
	(suit hearta heart)
	(canstack hearta club2)
	(canstack hearta spade2)
	(value heart2 n2)
	(suit heart2 heart)
	(canstack heart2 club3)
	(canstack heart2 spade3)
	(value diamond7 n7)
	(suit diamond7 diamond)
	(canstack diamond7 club8)
	(canstack diamond7 spade8)
	(value heart6 n6)
	(suit heart6 heart)
	(canstack heart6 club7)
	(canstack heart6 spade7)
	(value diamond6 n6)
	(suit diamond6 diamond)
	(canstack diamond6 club7)
	(canstack diamond6 spade7)
	(value spade10 n10)
	(suit spade10 spade)
	(canstack spade10 diamondj)
	(canstack spade10 heartj)
	(value spade8 n8)
	(suit spade8 spade)
	(canstack spade8 diamond9)
	(canstack spade8 heart9)
	(value club9 n9)
	(suit club9 club)
	(canstack club9 diamond10)
	(canstack club9 heart10)
	(value spade6 n6)
	(suit spade6 spade)
	(canstack spade6 diamond7)
	(canstack spade6 heart7)
	(value spade4 n4)
	(suit spade4 spade)
	(canstack spade4 diamond5)
	(canstack spade4 heart5)
	(value heart8 n8)
	(suit heart8 heart)
	(canstack heart8 club9)
	(canstack heart8 spade9)
	(value heartk n13)
	(suit heartk heart)
	(value spade9 n9)
	(suit spade9 spade)
	(canstack spade9 diamond10)
	(canstack spade9 heart10)
	(value clubk n13)
	(suit clubk club)
	(value heart10 n10)
	(suit heart10 heart)
	(canstack heart10 clubj)
	(canstack heart10 spadej)
	(value heartq n12)
	(suit heartq heart)
	(canstack heartq clubk)
	(canstack heartq spadek)
	(value club3 n3)
	(suit club3 club)
	(canstack club3 diamond4)
	(canstack club3 heart4)
	(value diamondq n12)
	(suit diamondq diamond)
	(canstack diamondq clubk)
	(canstack diamondq spadek)
	(value diamond10 n10)
	(suit diamond10 diamond)
	(canstack diamond10 clubj)
	(canstack diamond10 spadej)
	(value cluba n1)
	(suit cluba club)
	(canstack cluba diamond2)
	(canstack cluba heart2)
	(value diamond9 n9)
	(suit diamond9 diamond)
	(canstack diamond9 club10)
	(canstack diamond9 spade10)
	(value spade3 n3)
	(suit spade3 spade)
	(canstack spade3 diamond4)
	(canstack spade3 heart4)
	(home diamond0)
	(value diamond0 n0)
	(suit diamond0 diamond)
	(home club0)
	(value club0 n0)
	(suit club0 club)
	(home heart0)
	(value heart0 n0)
	(suit heart0 heart)
	(home spade0)
	(value spade0 n0)
	(suit spade0 spade)
)
(:goal (and
	(home diamondk)
	(home clubk)
	(home heartk)
	(home spadek)
)))
