(define (problem freecell6-4)
(:domain freecell)
(:objects
	diamond club heart spade 
	n0 n1 n2 n3 n4 n5 n6 heart6
	diamond3
	spadea
	spade3
	spade5
	heart2
	diamond5
	heart4
	spade6
	club2
	hearta
	club6
	spade4
	heart5
	spade2
	club4
	diamond6
	cluba
	club3
	club5
	diamonda
	heart3
	diamond4
	diamond2
	diamond0
	club0
	heart0
	spade0
	
)
(:init
	(successor n1 n0)
	(successor n2 n1)
	(successor n3 n2)
	(successor n4 n3)
	(successor n5 n4)
	(successor n6 n5)
	(cellspace n3)
	(clear heart6)
	(on heart6 heart2)
	(on heart2 hearta)
	(on hearta club4)
	(on club4 diamonda)
	(bottomcol diamonda)
	(clear diamond3)
	(on diamond3 diamond5)
	(on diamond5 club6)
	(on club6 diamond6)
	(on diamond6 heart3)
	(bottomcol heart3)
	(clear spadea)
	(on spadea heart4)
	(on heart4 spade4)
	(on spade4 cluba)
	(on cluba diamond4)
	(bottomcol diamond4)
	(clear spade3)
	(on spade3 spade6)
	(on spade6 heart5)
	(on heart5 club3)
	(on club3 diamond2)
	(bottomcol diamond2)
	(clear spade5)
	(on spade5 club2)
	(on club2 spade2)
	(on spade2 club5)
	(bottomcol club5)
	(colspace n0)
	(value heart6 n6)
	(suit heart6 heart)
	(value diamond3 n3)
	(suit diamond3 diamond)
	(canstack diamond3 club4)
	(canstack diamond3 spade4)
	(value spadea n1)
	(suit spadea spade)
	(canstack spadea diamond2)
	(canstack spadea heart2)
	(value spade3 n3)
	(suit spade3 spade)
	(canstack spade3 diamond4)
	(canstack spade3 heart4)
	(value spade5 n5)
	(suit spade5 spade)
	(canstack spade5 diamond6)
	(canstack spade5 heart6)
	(value heart2 n2)
	(suit heart2 heart)
	(canstack heart2 club3)
	(canstack heart2 spade3)
	(value diamond5 n5)
	(suit diamond5 diamond)
	(canstack diamond5 club6)
	(canstack diamond5 spade6)
	(value heart4 n4)
	(suit heart4 heart)
	(canstack heart4 club5)
	(canstack heart4 spade5)
	(value spade6 n6)
	(suit spade6 spade)
	(value club2 n2)
	(suit club2 club)
	(canstack club2 diamond3)
	(canstack club2 heart3)
	(value hearta n1)
	(suit hearta heart)
	(canstack hearta club2)
	(canstack hearta spade2)
	(value club6 n6)
	(suit club6 club)
	(value spade4 n4)
	(suit spade4 spade)
	(canstack spade4 diamond5)
	(canstack spade4 heart5)
	(value heart5 n5)
	(suit heart5 heart)
	(canstack heart5 club6)
	(canstack heart5 spade6)
	(value spade2 n2)
	(suit spade2 spade)
	(canstack spade2 diamond3)
	(canstack spade2 heart3)
	(value club4 n4)
	(suit club4 club)
	(canstack club4 diamond5)
	(canstack club4 heart5)
	(value diamond6 n6)
	(suit diamond6 diamond)
	(value cluba n1)
	(suit cluba club)
	(canstack cluba diamond2)
	(canstack cluba heart2)
	(value club3 n3)
	(suit club3 club)
	(canstack club3 diamond4)
	(canstack club3 heart4)
	(value club5 n5)
	(suit club5 club)
	(canstack club5 diamond6)
	(canstack club5 heart6)
	(value diamonda n1)
	(suit diamonda diamond)
	(canstack diamonda club2)
	(canstack diamonda spade2)
	(value heart3 n3)
	(suit heart3 heart)
	(canstack heart3 club4)
	(canstack heart3 spade4)
	(value diamond4 n4)
	(suit diamond4 diamond)
	(canstack diamond4 club5)
	(canstack diamond4 spade5)
	(value diamond2 n2)
	(suit diamond2 diamond)
	(canstack diamond2 club3)
	(canstack diamond2 spade3)
	(home diamond0)
	(value diamond0 n0)
	(suit diamond0 diamond)
	(home club0)
	(value club0 n0)
	(suit club0 club)
	(home heart0)
	(value heart0 n0)
	(suit heart0 heart)
	(home spade0)
	(value spade0 n0)
	(suit spade0 spade)
)
(:goal (and
	(home diamond6)
	(home club6)
	(home heart6)
	(home spade6)
)))
